export {
  PROCUREMENT_OPERATIONAL_SCAFFOLD,
  PROCUREMENT_OPERATIONAL_SLICE_ID,
  PROCUREMENT_OPERATIONAL_STATUS,
  PROCUREMENT_OWNERSHIP_ATTESTATION,
  PROCUREMENT_OWNERSHIP_CONTRACT,
  PROCUREMENT_OWNERSHIP_MATRIX,
  PROCUREMENT_OWNERSHIP_SLICE_ID,
  PROCUREMENT_OWNERSHIP_STATUS,
} from "./procurement/index.js";
