import {
  DENSITIES,
  RADII,
  SHADOWS,
  SIZES,
  STATUS_TONES,
  TOKEN_CATEGORIES,
  type TokenRegistry,
} from "../contracts/token.contract";

export const tokenRegistry = {
  categories: TOKEN_CATEGORIES,
  statusTones: STATUS_TONES,
  densities: DENSITIES,
  sizes: SIZES,
  radii: RADII,
  shadows: SHADOWS,
  tokens: [
    {
      name: "color.surface.canvas",
      category: "color",
      value: "hsl(210 20% 98%)",
      description: "Application canvas background.",
      stable: true,
    },
    {
      name: "color.surface.panel",
      category: "color",
      value: "hsl(0 0% 100%)",
      description: "Panel and card background.",
      stable: true,
    },
    {
      name: "color.border.subtle",
      category: "color",
      value: "hsl(214 16% 88%)",
      description: "Default low-emphasis border.",
      stable: true,
    },
    {
      name: "color.foreground.default",
      category: "color",
      value: "hsl(222 30% 12%)",
      description: "Primary readable foreground.",
      stable: true,
    },
    {
      name: "color.foreground.muted",
      category: "color",
      value: "hsl(218 10% 42%)",
      description: "Secondary readable foreground.",
      stable: true,
    },
    {
      name: "color.focus.ring",
      category: "color",
      value: "hsl(199 89% 48%)",
      description: "Keyboard focus indicator.",
      stable: true,
    },
    {
      name: "statusTone.neutral.surface",
      category: "statusTone",
      value: "hsl(210 18% 96%)",
      description: "Neutral status surface.",
      stable: true,
    },
    {
      name: "statusTone.info.surface",
      category: "statusTone",
      value: "hsl(204 94% 94%)",
      description: "Informational status surface.",
      stable: true,
    },
    {
      name: "statusTone.success.surface",
      category: "statusTone",
      value: "hsl(148 52% 92%)",
      description: "Successful status surface.",
      stable: true,
    },
    {
      name: "statusTone.warning.surface",
      category: "statusTone",
      value: "hsl(43 96% 91%)",
      description: "Warning status surface.",
      stable: true,
    },
    {
      name: "statusTone.danger.surface",
      category: "statusTone",
      value: "hsl(0 86% 94%)",
      description: "Destructive or error status surface.",
      stable: true,
    },
    {
      name: "statusTone.forbidden.surface",
      category: "statusTone",
      value: "hsl(276 45% 94%)",
      description: "Permission denied status surface.",
      stable: true,
    },
    {
      name: "statusTone.invalid.surface",
      category: "statusTone",
      value: "hsl(24 92% 93%)",
      description: "Validation failure status surface.",
      stable: true,
    },
    {
      name: "spacing.1",
      category: "spacing",
      value: "0.25rem",
      description: "Smallest governed spacing unit.",
      stable: true,
    },
    {
      name: "spacing.2",
      category: "spacing",
      value: "0.5rem",
      description: "Compact inline spacing.",
      stable: true,
    },
    {
      name: "spacing.3",
      category: "spacing",
      value: "0.75rem",
      description: "Standard inline spacing.",
      stable: true,
    },
    {
      name: "spacing.4",
      category: "spacing",
      value: "1rem",
      description: "Standard block spacing.",
      stable: true,
    },
    {
      name: "spacing.5",
      category: "spacing",
      value: "1.25rem",
      description: "Standard section spacing.",
      stable: true,
    },
    {
      name: "spacing.6",
      category: "spacing",
      value: "1.5rem",
      description: "Generous section spacing.",
      stable: true,
    },
    {
      name: "spacing.8",
      category: "spacing",
      value: "2rem",
      description: "Large layout spacing.",
      stable: true,
    },
    {
      name: "radius.none",
      category: "radius",
      value: "0",
      description: "No border radius — sharp edges.",
      stable: true,
    },
    {
      name: "radius.sm",
      category: "radius",
      value: "0.25rem",
      description: "Compact control radius.",
      stable: true,
    },
    {
      name: "radius.md",
      category: "radius",
      value: "0.5rem",
      description: "Default component radius.",
      stable: true,
    },
    {
      name: "radius.lg",
      category: "radius",
      value: "0.75rem",
      description: "Large component radius for cards and overlays.",
      stable: true,
    },
    {
      name: "shadow.none",
      category: "shadow",
      value: "none",
      description: "No elevation — flat surface.",
      stable: true,
    },
    {
      name: "shadow.raised",
      category: "shadow",
      value: "0 1px 2px hsl(222 30% 12% / 0.08)",
      description: "Low elevation for enterprise panels.",
      stable: true,
    },
    {
      name: "shadow.overlay",
      category: "shadow",
      value: "0 4px 16px hsl(222 30% 12% / 0.14)",
      description: "High elevation for dialogs and overlays.",
      stable: true,
    },
    {
      name: "typography.body.sm",
      category: "typography",
      value: "0.875rem/1.25rem",
      description: "Compact body text.",
      stable: true,
    },
    {
      name: "typography.label.md",
      category: "typography",
      value: "0.875rem/1rem 600",
      description: "Default control label.",
      stable: true,
    },
    {
      name: "motion.duration.instant",
      category: "motion",
      value: "0ms",
      description: "Zero-duration for programmatic state changes.",
      stable: true,
    },
    {
      name: "motion.duration.feedback",
      category: "motion",
      value: "120ms",
      description: "Fast control feedback (hover, press, focus).",
      stable: true,
    },
    {
      name: "motion.duration.overlay",
      category: "motion",
      value: "160ms",
      description: "Overlay and dialog entrance/exit.",
      stable: true,
    },
    {
      name: "motion.duration.navigation",
      category: "motion",
      value: "200ms",
      description: "Page-level navigation transitions.",
      stable: true,
    },
    {
      name: "motion.easing.standard",
      category: "motion",
      value: "cubic-bezier(0.2, 0, 0, 1)",
      description: "Standard motion easing.",
      stable: true,
    },
  ],
} as const satisfies TokenRegistry;

export type AfendaTokenName = (typeof tokenRegistry.tokens)[number]["name"];
