packages:
  - "apps/*"
  - "packages/*"
  - "packages/features/*"

allowBuilds:
  '@depot/cli': set this to true or false
  '@prisma/client': set this to true or false
  '@swc/core': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  nx: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

catalog:
  next: ^16.2.9
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.8.3
  vitest: ^3.2.4
  "@trigger.dev/sdk": ^4.4.6
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@testing-library/react": ^16.3.0
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/user-event": ^14.6.1
  jsdom: ^26.1.0
  "@vitejs/plugin-react": ^4.7.0
  tailwindcss: ^4.1.11
  "@tailwindcss/postcss": ^4.1.11
  sonner: ^2.0.7
  next-themes: ^0.4.6
