/**
 * CSS Entrypoint Manifest — shared contract and validators.
 *
 * This is the single source of truth for CSS governance rules across the monorepo.
 * The governance script (`scripts/css/check-css-governance.mts`) derives all
 * boundary rules from manifest instances — no path/rule duplication in script body.
 *
 * Design-system cannot import from @afenda/ui (cycle); it mirrors the interface
 * locally in packages/design-system/src/css/css-manifest.ts.
 */

// ── Purpose categories (SMACSS-aligned) ──────────────────────────────────────

/** SMACSS-aligned purpose categories for CSS entrypoints. */
export type CssEntrypointPurpose =
  | "tokens" // :root --afenda-* vars only. No @theme, no class authority.
  | "theme-bridge" // Tailwind v4 @theme inline. Maps --afenda-* to Tailwind utilities.
  | "primitive-structural" // @afenda/ui data-attr hooks. No --afenda-* token definitions.
  | "renderer-structural" // @afenda/metadata-ui .metadata-* classes. No tokens.
  | "shell-structural" // @afenda/appshell .app-shell-* classes. No tokens.
  | "auth-shell-structural" // @afenda/appshell .af-auth-shell* BEM layer. Internal @import only.
  | "studio-patterns" // @afenda/appshell reusable shadcn/studio patterns layer. Internal @import only.
  | "fixture"; // Storybook/demo composition only. Never in production app globals.

// ── Class namespace contracts ─────────────────────────────────────────────────

/** Allowed leading class-selector prefix for a package. */
export type CssClassNamespace =
  | "data-attr-only" // No class selectors — data-attribute hooks only (@afenda/ui)
  | "none" // No class authority (design-system token CSS)
  | "metadata-" // @afenda/metadata-ui production classes
  | "metadata-fixture-" // @afenda/metadata-ui fixture classes
  | "app-shell-" // @afenda/appshell production classes
  | "af-auth-shell"; // @afenda/appshell auth BEM (.af-auth-shell*)

/** Allowed custom-property prefix for a package. Downstream squatting generic
 *  Tailwind/shared namespaces (--color-*, --spacing-*, --font-*, --radius-*) is forbidden. */
export type CssPropertyNamespace =
  | "--afenda-" // design-system authority only
  | "--app-shell-" // @afenda/appshell scoped props
  | "--af-auth-shell-" // @afenda/appshell auth-shell scoped props
  | "--metadata-" // @afenda/metadata-ui scoped props
  | "none"; // file defines no custom properties

// ── Manifest item ─────────────────────────────────────────────────────────────

/**
 * One CSS entrypoint owned by a package.
 * Every `package.json` CSS export must have a corresponding manifest entry.
 * Every manifest `sourceFile` must exist on disk.
 */
export interface CssEntrypointManifestItem {
  /** Export path this entry aliases (points to same dist file). No separate source. */
  readonly aliasOf?: string;
  /** Glob/package patterns permitted to import this file. */
  readonly allowedImporters: readonly string[];
  /** Expected leading class-selector namespace (enforced by governance script). */
  readonly classNamespace: CssClassNamespace;
  /** Export path as declared in package.json, e.g. `"./styles.css"` */
  readonly exportPath: string;
  /** File is generated by a build script — not hand-authored. */
  readonly generated?: boolean;
  /**
   * Internal `@import`-only layer. Not a standalone package.json export — it is
   * consumed exclusively via `@import` from another file in this same package.
   * When `true`: duplicate-export-path validation and package.json export checks
   * are skipped for this entry.
   */
  readonly internalOnly?: true;
  /** Legacy alias — if true, not the preferred export path; will be removed in a future major. */
  readonly legacy?: boolean;
  /** npm package name, e.g. `"@afenda/metadata-ui"` */
  readonly packageName: string;
  /** Safe to import in production app entrypoints. Fixture files = `false`. */
  readonly productionSafe: boolean;
  /** Glob/package patterns explicitly forbidden from importing this file. */
  readonly prohibitedImporters: readonly string[];
  /** Expected custom-property namespace (enforced by governance script). */
  readonly propertyNamespace:
    | CssPropertyNamespace
    | readonly CssPropertyNamespace[];
  /** SMACSS-aligned purpose category. */
  readonly purpose: CssEntrypointPurpose;
  /** Requires a Tailwind v4 `@theme`-aware pipeline (PostCSS or Vite Tailwind plugin). */
  readonly requiresTailwindTheme: boolean;
  /** Source file relative to package root, e.g. `"src/styles.css"` */
  readonly sourceFile: string;
}

// ── Typed manifest tuple ──────────────────────────────────────────────────────

/** Readonly array of manifest items for one package. */
export type CssManifest = readonly CssEntrypointManifestItem[];

// ── Validators ────────────────────────────────────────────────────────────────

/** Internal error record emitted by validators. */
export interface CssManifestViolation {
  readonly exportPath: string;
  readonly message: string;
  readonly packageName: string;
  readonly rule: string;
}

/**
 * Asserts that every fixture entry is `productionSafe: false`.
 * Returns an array of violations (empty = OK).
 */
export function assertFixtureEntriesNotProductionSafe(
  manifest: CssManifest
): readonly CssManifestViolation[] {
  return manifest
    .filter((e) => e.purpose === "fixture" && e.productionSafe)
    .map((e) => ({
      rule: "fixture-not-production-safe",
      exportPath: e.exportPath,
      packageName: e.packageName,
      message: `Fixture entry "${e.exportPath}" must have productionSafe: false`,
    }));
}

/**
 * Asserts every manifest entry has a non-empty sourceFile path.
 * File existence is checked by the governance script (requires fs access).
 */
export function assertManifestSourceFiles(
  manifest: CssManifest
): readonly CssManifestViolation[] {
  return manifest
    .filter((e) => e.sourceFile.trim().length === 0)
    .map((e) => ({
      rule: "manifest-source-file-defined",
      exportPath: e.exportPath,
      packageName: e.packageName,
      message: `Manifest entry "${e.exportPath}" has no sourceFile`,
    }));
}

/**
 * Asserts no duplicate export paths within a manifest.
 * Entries marked `internalOnly: true` are excluded — they intentionally share
 * an `exportPath` with their parent file (internal `@import` layers).
 */
export function assertNoDuplicateExportPaths(
  manifest: CssManifest
): readonly CssManifestViolation[] {
  const seen = new Set<string>();
  const violations: CssManifestViolation[] = [];
  for (const entry of manifest) {
    if (entry.internalOnly) continue;
    if (seen.has(entry.exportPath)) {
      violations.push({
        rule: "no-duplicate-export-paths",
        exportPath: entry.exportPath,
        packageName: entry.packageName,
        message: `Duplicate export path "${entry.exportPath}" in manifest`,
      });
    }
    seen.add(entry.exportPath);
  }
  return violations;
}

/**
 * Returns all violations for a manifest (pure, no fs access).
 * Combine with file-existence checks in the governance script.
 */
export function validateManifest(
  manifest: CssManifest
): readonly CssManifestViolation[] {
  return [
    ...assertFixtureEntriesNotProductionSafe(manifest),
    ...assertManifestSourceFiles(manifest),
    ...assertNoDuplicateExportPaths(manifest),
  ];
}
