// Authority vocabulary — re-exported from the design-system bridge.

export {
  type ComponentAccessibilityDefinition,
  getAccessibilityPolicy,
  getComponentAccessibilityDefinition,
  getComponentAccessibilityRequirement,
  getRecipeAccessibilityDefinitions,
  hasComponentAccessibilityDefinition,
} from "./accessibility";
// Runtime implementation helpers.
export {
  assertAllowedLayoutClassName,
  assertAllowedLayoutClassNameStrict,
  getClassNamePolicy,
  resolveLayoutClassName,
  validateLayoutClassName,
} from "./class-name";
// Governed component prop surfaces.
export type {
  AfendaBadgeProps,
  AfendaButtonProps,
  AfendaCardProps,
  GOVERNED_CARD_LAYOUT_SIZES,
  GovernedAccordionProps,
  GovernedAlertDialogProps,
  GovernedAlertDialogContentSize,
  GovernedAspectRatioProps,
  GovernedAvatarBadgeProps,
  GovernedAvatarProps,
  GovernedAvatarSize,
  GovernedBadgeProps,
  GovernedButtonProps,
  GovernedCardLayoutSize,
  GovernedCardProps,
  GovernedCardRadius,
  GovernedCardShadow,
  GovernedCommandProps,
  GovernedEmptyMediaVariant,
  GovernedFormControlProps,
  GovernedPanelRadius,
  GovernedPanelShadow,
  GovernedStatusProps,
  GovernedSurfaceProps,
  GovernedTableProps,
  GovernedToggleProps,
  GovernedToggleSize,
  GovernedToggleVariant,
} from "./component-props";
export {
  GOVERNED_AVATAR_SIZES,
  GOVERNED_CARD_RADII,
  GOVERNED_CARD_SHADOWS,
  GOVERNED_PANEL_RADII,
  GOVERNED_PANEL_SHADOWS,
  isGovernedCardLayoutSize,
  isGovernedAvatarSize,
  isGovernedCardRadius,
  isGovernedCardShadow,
  isGovernedPanelRadius,
  isGovernedPanelShadow,
} from "./component-props";
export {
  createGovernedDivSlot,
  createGovernedSpanSlot,
} from "./create-governed-slot";
// Authority types — re-exported from the design-system bridge.
export type {
  AccessibilityContract,
  AccessibilityRequirement,
  AfendaCssVariableName,
  AfendaTokenCategory,
  AfendaTokenCssVariable,
  AfendaTokenName,
  AiAntiDriftRules,
  ClassNamePolicyContract,
  Density,
  DesignAuthorityAcceptanceCriteria,
  DesignAuthorityDomain,
  DesignAuthorityIdentity,
  DesignSystemAuthorityContract,
  DesignSystemContract,
  DesignSystemPackageBoundary,
  GovernedComponentContract,
  GovernedExample,
  GovernedRadius,
  GovernedShadow,
  GovernedSize,
  GovernedState,
  MotionContract,
  MotionIntent,
  OwnershipDomainAuthority,
  ProhibitedOverlapRule,
  PublicExportContract,
  RecipeDeclaration,
  RecipeDefinition,
  RecipeRegistry,
  SlotContract,
  SlotRole,
  StateContract,
  StatePattern,
  StatusTone,
  Tip004DownstreamContract,
  TokenCategory,
  TokenDefinition,
  TokenName,
  TokenRegistry,
  VariantAxis,
  VariantDefinition,
  VariantEmphasis,
  VariantIntent,
  VariantRegistry,
  VariantSelection,
} from "./design-system";
export {
  ACCESSIBILITY_REQUIREMENTS,
  AFENDA_TOKEN_CATEGORIES,
  ALLOWED_LAYOUT_CLASSNAME_PATTERNS,
  accessibilityContract,
  accessibilityPolicy,
  assertAfendaTokenName,
  classNamePolicyContract,
  componentContract,
  DENSITIES,
  DENSITY_ATTRIBUTES,
  densityContract,
  DESIGN_AUTHORITY_DOMAINS,
  designSystemAuthorityContract,
  exampleContract,
  exportContract,
  GOVERNED_STATES,
  isAfendaTokenName,
  MOTION_INTENTS,
  motionContract,
  motionPolicy,
  PROHIBITED_CLASSNAME_PATTERNS,
  RADII,
  recipeContract,
  SHADOWS,
  SIZES,
  SLOT_ROLES,
  STATUS_TONES,
  slotContract,
  stateContract,
  TIP_004_DOWNSTREAM_CONTRACTS,
  TOKEN_CATEGORIES,
  tokenContract,
  tokenNameToCssVariable,
  VARIANT_AXES,
  VARIANT_EMPHASES,
  VARIANT_INTENTS,
  variantContract,
} from "./design-system";
export {
  resolveAppShellClassName,
  resolveAppShellSlotClassName,
  resolveAppShellVariant,
  resolveAuthorityRecipeSlotClassName,
  resolveMetadataUiClassName,
  resolveMetadataUiSlotClassName,
  resolveMetadataUiVariant,
  APP_SHELL_RECIPE_SLOTS,
  APP_SHELL_SLOT_CLASS_NAMES,
  METADATA_UI_RECIPE_SLOTS,
  METADATA_UI_SLOT_CLASS_NAMES,
  type AppShellRecipeSlot,
  type AuthorityRecipeName,
  type MetadataUiRecipeSlot,
  isAppShellRecipeSlot,
  isAuthorityRecipeName,
  isMetadataUiRecipeSlot,
} from "./authority-recipe";
export {
  densityAttributeSelector,
  densityFromAttribute,
  densityToAttribute,
  isDensity,
  isDensityAttribute,
} from "./density";
export { applyGovernedPresentation } from "./governed-render";
export {
  assertMotionPolicyCoverageStrict,
  getMissingMotionIntents,
  getMotionIntent,
  getMotionPolicy,
  isMotionIntent,
  resolveMotionIntent,
} from "./motion";
export type {
  FieldOrientation,
  GovernedPrimitiveDefinition,
  PrimitiveGovernanceInput,
  PrimitiveGovernanceResult,
} from "./primitive-contract";
export { resolvePrimitiveGovernance } from "./primitive-governance";
export { resolvePrimitiveGovernance as resolvePrimitiveGovernanceFromCanonical } from "./resolve-primitive-governance";
export {
  assertGuardedClassName,
  guardClassName,
} from "./class-name-guard";
export {
  classNamePolicyError,
  invalidSlotError,
  invalidSlotKeyError,
  PRIMITIVE_GOVERNANCE_ERROR_PREFIX,
  primitiveGovernanceError,
  unknownPrimitiveError,
} from "./primitive-errors";
export {
  CORE_PRIMITIVE_NAMES,
  getPrimitiveRegistryEntry,
  PRIMITIVE_REGISTRY_ENTRIES,
  type CorePrimitiveName,
  type PrimitiveRegistryEntry,
} from "./primitive-registry-meta";
export type { StockShadcnPendingFile } from "./primitive-registry";
export {
  assertComponentExportCoverage,
  EXPORTED_STOCK_COMPONENTS,
  GOVERNED_COMPONENT_SOURCE_FILES,
  GOVERNED_PRIMITIVE_REGISTRY,
  getPrimitiveDefinition,
  isGovernedPrimitive,
  isGovernedSourceFile,
  isStockPendingSourceFile,
  PRIMARY_UI_EXPORTS,
  STOCK_SHADCN_PENDING,
} from "./primitive-registry";

export {
  resolveBadgeClassName,
  resolveButtonClassName,
  resolveCardClassName,
  resolveFieldOrientationClassName,
  resolveFormControlClassName,
  resolveGovernedRecipe,
  resolveGovernedRecipeClassName,
  resolveStatusClassName,
  resolveSurfaceClassName,
  resolveTableClassName,
  resolveToggleClassName,
} from "./recipe";
export {
  BADGE_VARIANT_AXES,
  BUTTON_VARIANT_AXES,
  CARD_VARIANT_AXES,
  FORM_CONTROL_VARIANT_AXES,
  GOVERNED_RECIPE_VARIANT_AXES,
  APP_SHELL_VARIANT_AXES,
  METADATA_UI_VARIANT_AXES,
  getRecipeVariantAxes,
  STATUS_VARIANT_AXES,
  SURFACE_VARIANT_AXES,
  TABLE_VARIANT_AXES,
} from "./recipe-coverage";
export {
  assertSlotContract,
  assertSlotRole,
  getSlotRoles,
  getUnknownSlotRoles,
  isSlotRole,
  resolveSlotRole,
} from "./slot";
export {
  assertGovernedState,
  assertGovernedStates,
  getGovernedStates,
  getUnknownGovernedStates,
  isGovernedState,
  resolveGovernedState,
} from "./state";
export {
  mapStockButtonProps,
  mapStockButtonSize,
  mapStockButtonVisualToGoverned,
  type StockButtonSize,
  type StockButtonVisual,
} from "./stock-shadcn-compat";
// CSS governance contract — shared across appshell, metadata-ui, and the governance script.
export type {
  CssClassNamespace,
  CssEntrypointManifestItem,
  CssEntrypointPurpose,
  CssManifest,
  CssManifestViolation,
  CssPropertyNamespace,
} from "./css-manifest";
export {
  assertFixtureEntriesNotProductionSafe,
  assertManifestSourceFiles,
  assertNoDuplicateExportPaths,
  validateManifest,
} from "./css-manifest";
// Governed UI vocabulary.
export type {
  ClassNamePolicyResult,
  ClassNamePolicyViolation,
  GovernedRecipeName,
  GovernedRecipeResult,
  GovernedUiComponentName,
} from "./types";
export {
  GOVERNED_UI_COMPONENTS,
  GOVERNED_UI_RECIPES,
  isGovernedRecipeName,
  isGovernedUiComponentName,
} from "./types";
export {
  assertGovernedVariantStrict,
  resolveBadgeVariant,
  resolveBadgeVariantStrict,
  resolveButtonVariant,
  resolveButtonVariantStrict,
  resolveCardVariant,
  resolveCardVariantStrict,
  resolveFormControlVariant,
  resolveFormControlVariantStrict,
  resolveGovernedVariant,
  resolveGovernedVariantStrict,
  resolveStatusVariant,
  resolveStatusVariantStrict,
  resolveSurfaceVariant,
  resolveSurfaceVariantStrict,
  resolveTableVariant,
  resolveTableVariantStrict,
  type VariantPolicyResult,
  type VariantPolicyViolation,
  validateGovernedVariant,
} from "./variant";
