import type { GovernedPrimitiveDefinition } from "./primitive-contract";
import {
  accordionSlotClassNames,
  accordionSlotClassNamesByKey,
  alertDialogSlotClassNames,
  alertDialogSlotClassNamesByKey,
  alertSlotClassNames,
  avatarSlotClassNames,
  breadcrumbSlotClassNames,
  breadcrumbSlotClassNamesByKey,
  buttonGroupSlotClassNames,
  buttonGroupSlotClassNamesByKey,
  calendarDataSlotByKey,
  calendarSlotClassNames,
  calendarSlotClassNamesByKey,
  cardSlotClassNames,
  carouselSlotClassNames,
  carouselSlotClassNamesByKey,
  chartSlotClassNames,
  chartSlotClassNamesByKey,
  checkboxIndicatorSlotClassName,
  checkboxRootSlotClassName,
  comboboxSlotClassNames,
  comboboxSlotClassNamesByKey,
  commandSlotClassNames,
  commandSlotClassNamesByKey,
  contextMenuSlotClassNames,
  contextMenuSlotClassNamesByKey,
  dataTableEmptyCellSlotClassName,
  dataTableRootSlotClassName,
  dialogSlotClassNames,
  dialogSlotClassNamesByKey,
  drawerSlotClassNames,
  drawerSlotClassNamesByKey,
  dropdownMenuSlotClassNames,
  dropdownMenuSlotClassNamesByKey,
  emptyMediaVariantClassNames,
  emptySlotClassNames,
  fieldSlotClassNames,
  fieldSlotClassNamesByKey,
  formControlLeafSizeClassNames,
  hoverCardSlotClassNames,
  hoverCardSlotClassNamesByKey,
  inputGroupSlotClassNames,
  inputGroupSlotClassNamesByKey,
  inputOtpSlotClassNames,
  inputOtpSlotClassNamesByKey,
  inputRootSlotClassName,
  itemSlotClassNames,
  itemSlotClassNamesByKey,
  kbdSlotClassNames,
  kbdSlotClassNamesByKey,
  labelRootSlotClassName,
  menubarSlotClassNames,
  menubarSlotClassNamesByKey,
  nativeSelectSlotClassNames,
  nativeSelectSlotClassNamesByKey,
  navigationMenuSlotClassNames,
  navigationMenuSlotClassNamesByKey,
  paginationSlotClassNames,
  paginationSlotClassNamesByKey,
  popoverSlotClassNames,
  popoverSlotClassNamesByKey,
  progressSlotClassNames,
  radioGroupSlotClassNames,
  radioGroupSlotClassNamesByKey,
  resizableSlotClassNames,
  resizableSlotClassNamesByKey,
  scrollAreaSlotClassNames,
  selectSlotClassNames,
  selectSlotClassNamesByKey,
  separatorRootSlotClassName,
  sheetSlotClassNames,
  sheetSlotClassNamesByKey,
  sidebarSlotClassNames,
  sidebarSlotClassNamesByKey,
  skeletonRootSlotClassName,
  sliderSlotClassNames,
  spinnerSlotClassNames,
  spinnerSlotClassNamesByKey,
  statusIndicatorDotClassNamesByKey,
  statusIndicatorSlotClassNames,
  switchRootSlotClassName,
  switchSizeClassNamesByKey,
  switchThumbSlotClassName,
  tableSlotClassNames,
  tableSlotClassNamesByKey,
  tabsSlotClassNames,
  tabsSlotClassNamesByKey,
  textareaRootSlotClassName,
  toasterSlotClassNames,
  toasterSlotClassNamesByKey,
  toggleGroupSlotClassNames,
  tooltipSlotClassNames,
  tooltipSlotClassNamesByKey,
} from "./recipe-maps";
import type { GovernedUiComponentName } from "./types";
import { GOVERNED_UI_COMPONENTS } from "./types";

export const GOVERNED_PRIMITIVE_REGISTRY = {
  Button: {
    componentName: "Button",
    recipeName: "button",
    sourceFile: "src/components/button.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "feedback",
    allowAsChild: true,
    dataSlotByRole: { root: "button" },
    slotClassNames: {},
  },
  Badge: {
    componentName: "Badge",
    recipeName: "badge",
    sourceFile: "src/components/badge.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: true,
    dataSlotByRole: { root: "badge" },
    slotClassNames: {},
  },
  Card: {
    componentName: "Card",
    recipeName: "card",
    sourceFile: "src/components/card.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "header", "label", "body", "actions", "content", "footer"],
    motion: "instant",
    allowAsChild: false,
    dataSlotByRole: {
      root: "card",
      header: "card-header",
      content: "card-content",
      footer: "card-footer",
      actions: "card-action",
      label: "card-title",
      body: "card-description",
    },
    slotClassNames: cardSlotClassNames,
  },
  Alert: {
    componentName: "Alert",
    recipeName: "status",
    sourceFile: "src/components/alert.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "label", "body", "actions"],
    motion: "instant",
    allowAsChild: false,
    dataSlotByRole: {
      root: "alert",
      label: "alert-title",
      body: "alert-description",
      actions: "alert-action",
    },
    slotClassNames: alertSlotClassNames,
  },
  Field: {
    componentName: "Field",
    recipeName: "form-control",
    sourceFile: "src/components/field.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "header",
      "body",
      "label",
      "content",
      "control",
      "state",
      "footer",
      "actions",
    ],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "group",
    dataSlotByRole: {
      root: "field",
      header: "field-set",
      body: "field-group",
      label: "field-legend",
      content: "field-content",
      control: "field-label",
      state: "field-description",
      footer: "field-separator",
      actions: "field-error",
    },
    slotClassNames: fieldSlotClassNames,
    slotClassNamesByKey: fieldSlotClassNamesByKey,
    dataSlotByKey: {
      title: "field-label",
      separatorLine: "field-separator-line",
      separatorContent: "field-separator-content",
      errorList: "field-error-list",
    },
  },
  Table: {
    componentName: "Table",
    recipeName: "table",
    sourceFile: "src/components/table.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "header", "content", "footer"],
    motion: "instant",
    allowAsChild: false,
    dataSlotByRole: {
      root: "table",
      header: "table-header",
      content: "table-body",
      footer: "table-footer",
    },
    slotClassNames: tableSlotClassNames,
    slotClassNamesByKey: tableSlotClassNamesByKey,
    dataSlotByKey: {
      container: "table-container",
      row: "table-row",
      head: "table-head",
      cell: "table-cell",
      caption: "table-caption",
    },
  },
  Input: {
    componentName: "Input",
    recipeName: "form-control",
    sourceFile: "src/components/input.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "input" },
    slotClassNames: { root: inputRootSlotClassName },
    slotClassNamesByKey: formControlLeafSizeClassNames,
  },
  Label: {
    componentName: "Label",
    recipeName: "form-control",
    sourceFile: "src/components/label.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "label" },
    slotClassNames: { root: labelRootSlotClassName },
  },
  Textarea: {
    componentName: "Textarea",
    recipeName: "form-control",
    sourceFile: "src/components/textarea.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "textarea" },
    slotClassNames: { root: textareaRootSlotClassName },
    slotClassNamesByKey: formControlLeafSizeClassNames,
  },
  Checkbox: {
    componentName: "Checkbox",
    recipeName: "form-control",
    sourceFile: "src/components/checkbox.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "checkbox" },
    slotClassNames: { root: checkboxRootSlotClassName },
    slotClassNamesByKey: { indicator: checkboxIndicatorSlotClassName },
    dataSlotByKey: { indicator: "checkbox-indicator" },
  },
  Switch: {
    componentName: "Switch",
    recipeName: "form-control",
    sourceFile: "src/components/switch.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "feedback",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "switch" },
    slotClassNames: { root: switchRootSlotClassName },
    slotClassNamesByKey: {
      thumb: switchThumbSlotClassName,
      ...switchSizeClassNamesByKey,
    },
    dataSlotByKey: { thumb: "switch-thumb" },
  },
  Dialog: {
    componentName: "Dialog",
    recipeName: "surface",
    sourceFile: "src/components/dialog.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "header", "footer", "label", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "dialog-content",
      body: "dialog-overlay",
      header: "dialog-header",
      footer: "dialog-footer",
      label: "dialog-title",
      state: "dialog-description",
    },
    slotClassNames: dialogSlotClassNames,
    slotClassNamesByKey: dialogSlotClassNamesByKey,
    dataSlotByKey: {
      "close-button": "dialog-close-button",
      "close-label": "dialog-close-label",
    },
  },
  Popover: {
    componentName: "Popover",
    recipeName: "surface",
    sourceFile: "src/components/popover.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "header", "label", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "popover-content",
      header: "popover-header",
      label: "popover-title",
      state: "popover-description",
    },
    slotClassNames: popoverSlotClassNames,
    slotClassNamesByKey: popoverSlotClassNamesByKey,
    dataSlotByKey: {
      "menu-root": "popover",
      trigger: "popover-trigger",
    },
  },
  Tooltip: {
    componentName: "Tooltip",
    recipeName: "surface",
    sourceFile: "src/components/tooltip.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "tooltip-content" },
    slotClassNames: tooltipSlotClassNames,
    slotClassNamesByKey: tooltipSlotClassNamesByKey,
    dataSlotByKey: {
      arrow: "tooltip-arrow",
      provider: "tooltip-provider",
      "menu-root": "tooltip",
      trigger: "tooltip-trigger",
    },
  },
  Tabs: {
    componentName: "Tabs",
    recipeName: "surface",
    sourceFile: "src/components/tabs.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "header", "control", "content"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "tabs",
      header: "tabs-list",
      control: "tabs-trigger",
      content: "tabs-content",
    },
    dataSlotByKey: {
      "list-default": "tabs-list",
      "list-line": "tabs-list",
    },
    slotClassNames: tabsSlotClassNames,
    slotClassNamesByKey: tabsSlotClassNamesByKey,
  },
  Select: {
    componentName: "Select",
    recipeName: "form-control",
    sourceFile: "src/components/select.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control", "body", "state", "label", "footer", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "select-content",
      control: "select-trigger",
      body: "select-group",
      state: "select-label",
      label: "select-item",
      footer: "select-separator",
      icon: "select-scroll-up-button",
    },
    slotClassNames: selectSlotClassNames,
    slotClassNamesByKey: selectSlotClassNamesByKey,
    dataSlotByKey: {
      "select-root": "select",
      "select-value": "select-value",
      "content-popper": "select-content",
      "trigger-size-sm": "select-trigger",
      "trigger-size-md": "select-trigger",
      viewport: "select-viewport",
      "viewport-popper": "select-viewport",
      "scroll-down": "select-scroll-down-button",
      "item-indicator": "select-item-indicator",
      "trigger-chevron": "select-icon",
      "item-check-icon": "select-item-indicator",
    },
  },
  DropdownMenu: {
    componentName: "DropdownMenu",
    recipeName: "surface",
    sourceFile: "src/components/dropdown-menu.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "content", "control", "state", "footer", "actions"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "dropdown-menu-content",
      content: "dropdown-menu-sub-content",
      control: "dropdown-menu-item",
      state: "dropdown-menu-label",
      footer: "dropdown-menu-separator",
      actions: "dropdown-menu-shortcut",
    },
    slotClassNames: dropdownMenuSlotClassNames,
    slotClassNamesByKey: dropdownMenuSlotClassNamesByKey,
    dataSlotByKey: {
      "menu-root": "dropdown-menu",
      trigger: "dropdown-menu-trigger",
      "checkbox-item": "dropdown-menu-checkbox-item",
      "radio-item": "dropdown-menu-radio-item",
      "sub-trigger": "dropdown-menu-sub-trigger",
      "sub-trigger-chevron": "dropdown-menu-sub-trigger",
      "item-indicator": "dropdown-menu-checkbox-item-indicator",
    },
  },
  ContextMenu: {
    componentName: "ContextMenu",
    recipeName: "surface",
    sourceFile: "src/components/context-menu.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "content", "control", "state", "footer", "actions"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "context-menu-content",
      content: "context-menu-sub-content",
      control: "context-menu-item",
      state: "context-menu-label",
      footer: "context-menu-separator",
      actions: "context-menu-shortcut",
    },
    slotClassNames: contextMenuSlotClassNames,
    slotClassNamesByKey: contextMenuSlotClassNamesByKey,
    dataSlotByKey: {
      "menu-root": "context-menu",
      trigger: "context-menu-trigger",
      "checkbox-item": "context-menu-checkbox-item",
      "radio-item": "context-menu-radio-item",
      "sub-trigger": "context-menu-sub-trigger",
      "sub-trigger-chevron": "context-menu-sub-trigger",
      "item-indicator": "context-menu-checkbox-item-indicator",
    },
  },
  Menubar: {
    componentName: "Menubar",
    recipeName: "surface",
    sourceFile: "src/components/menubar.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "content", "control", "state", "footer", "actions"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "menubar",
      content: "menubar-content",
      control: "menubar-item",
      state: "menubar-label",
      footer: "menubar-separator",
      actions: "menubar-shortcut",
    },
    slotClassNames: menubarSlotClassNames,
    slotClassNamesByKey: menubarSlotClassNamesByKey,
    dataSlotByKey: {
      trigger: "menubar-trigger",
      "checkbox-item": "menubar-checkbox-item",
      "radio-item": "menubar-radio-item",
      "sub-trigger": "menubar-sub-trigger",
      "sub-trigger-chevron": "menubar-sub-trigger",
      "sub-content": "menubar-sub-content",
      "item-indicator": "menubar-checkbox-item-indicator",
    },
  },
  Breadcrumb: {
    componentName: "Breadcrumb",
    recipeName: "surface",
    sourceFile: "src/components/breadcrumb.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "content", "control", "label", "icon", "state"],
    motion: "instant",
    allowAsChild: true,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "breadcrumb",
      body: "breadcrumb-list",
      content: "breadcrumb-item",
      control: "breadcrumb-link",
      label: "breadcrumb-page",
      icon: "breadcrumb-separator",
      state: "breadcrumb-ellipsis",
    },
    slotClassNames: breadcrumbSlotClassNames,
    slotClassNamesByKey: breadcrumbSlotClassNamesByKey,
    dataSlotByKey: {
      "ellipsis-label": "breadcrumb-ellipsis",
    },
  },
  Pagination: {
    componentName: "Pagination",
    recipeName: "surface",
    sourceFile: "src/components/pagination.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "pagination",
      body: "pagination-content",
      icon: "pagination-ellipsis",
    },
    slotClassNames: paginationSlotClassNames,
    slotClassNamesByKey: paginationSlotClassNamesByKey,
    dataSlotByKey: {
      "link-padding-start": "pagination-link",
      "link-padding-end": "pagination-link",
      "link-text": "pagination-link",
      "ellipsis-label": "pagination-ellipsis",
    },
  },
  NavigationMenu: {
    componentName: "NavigationMenu",
    recipeName: "surface",
    sourceFile: "src/components/navigation-menu.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "content",
      "control",
      "header",
      "label",
      "state",
      "footer",
      "actions",
    ],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "navigation-menu",
      body: "navigation-menu-list",
      content: "navigation-menu-item",
      control: "navigation-menu-trigger",
      header: "navigation-menu-content",
      label: "navigation-menu-link",
      state: "navigation-menu-indicator",
      footer: "navigation-menu-viewport-wrapper",
      actions: "navigation-menu-viewport",
    },
    slotClassNames: navigationMenuSlotClassNames,
    slotClassNamesByKey: navigationMenuSlotClassNamesByKey,
    dataSlotByKey: {
      "trigger-style": "navigation-menu-trigger",
      "trigger-chevron": "navigation-menu-trigger-chevron",
      "indicator-arrow": "navigation-menu-indicator-arrow",
    },
  },
  ButtonGroup: {
    componentName: "ButtonGroup",
    recipeName: "surface",
    sourceFile: "src/components/button-group.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control", "footer"],
    motion: "instant",
    allowAsChild: true,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "button-group",
      control: "button-group-text",
      footer: "button-group-separator",
    },
    slotClassNames: buttonGroupSlotClassNames,
    slotClassNamesByKey: buttonGroupSlotClassNamesByKey,
    dataSlotByKey: {
      "orientation-horizontal": "button-group",
      "orientation-vertical": "button-group",
    },
  },
  Item: {
    componentName: "Item",
    recipeName: "surface",
    sourceFile: "src/components/item.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "control",
      "content",
      "label",
      "state",
      "actions",
      "header",
      "footer",
      "icon",
    ],
    motion: "instant",
    allowAsChild: true,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "item",
      body: "item-group",
      control: "item-media",
      content: "item-content",
      label: "item-title",
      state: "item-description",
      actions: "item-actions",
      header: "item-header",
      footer: "item-footer",
      icon: "item-separator",
    },
    slotClassNames: itemSlotClassNames,
    slotClassNamesByKey: itemSlotClassNamesByKey,
    dataSlotByKey: {
      "default-default": "item",
      "default-sm": "item",
      "default-xs": "item",
      "outline-default": "item",
      "outline-sm": "item",
      "outline-xs": "item",
      "muted-default": "item",
      "muted-sm": "item",
      "muted-xs": "item",
      "media-default": "item-media",
      "media-icon": "item-media",
      "media-image": "item-media",
    },
  },
  Sheet: {
    componentName: "Sheet",
    recipeName: "surface",
    sourceFile: "src/components/sheet.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "header", "footer", "label", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "sheet-content",
      body: "sheet-overlay",
      header: "sheet-header",
      footer: "sheet-footer",
      label: "sheet-title",
      state: "sheet-description",
    },
    slotClassNames: sheetSlotClassNames,
    slotClassNamesByKey: sheetSlotClassNamesByKey,
    dataSlotByKey: {
      "close-button": "sheet-close-button",
      "close-label": "sheet-close-label",
    },
  },
  Drawer: {
    componentName: "Drawer",
    recipeName: "surface",
    sourceFile: "src/components/drawer.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "header", "footer", "label", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "drawer-content",
      body: "drawer-overlay",
      header: "drawer-header",
      footer: "drawer-footer",
      label: "drawer-title",
      state: "drawer-description",
    },
    slotClassNames: drawerSlotClassNames,
    slotClassNamesByKey: drawerSlotClassNamesByKey,
    dataSlotByKey: { handle: "drawer-handle" },
  },
  RadioGroup: {
    componentName: "RadioGroup",
    recipeName: "form-control",
    sourceFile: "src/components/radio-group.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "radio-group",
      control: "radio-group-item",
    },
    slotClassNames: radioGroupSlotClassNames,
    slotClassNamesByKey: radioGroupSlotClassNamesByKey,
    dataSlotByKey: {
      indicator: "radio-group-indicator",
      "indicator-dot": "radio-group-indicator-dot",
    },
  },
  Separator: {
    componentName: "Separator",
    recipeName: "form-control",
    sourceFile: "src/components/separator.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "separator" },
    slotClassNames: { root: separatorRootSlotClassName },
  },
  Skeleton: {
    componentName: "Skeleton",
    recipeName: "form-control",
    sourceFile: "src/components/skeleton.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "skeleton" },
    slotClassNames: { root: skeletonRootSlotClassName },
  },
  ScrollArea: {
    componentName: "ScrollArea",
    recipeName: "form-control",
    sourceFile: "src/components/scroll-area.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "control", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "scroll-area",
      body: "scroll-area-viewport",
      control: "scroll-area-scrollbar",
      icon: "scroll-area-thumb",
    },
    slotClassNames: scrollAreaSlotClassNames,
  },
  Avatar: {
    componentName: "Avatar",
    recipeName: "form-control",
    sourceFile: "src/components/avatar.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "control", "icon", "header", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "avatar",
      body: "avatar-image",
      control: "avatar-fallback",
      icon: "avatar-badge",
      header: "avatar-group",
      state: "avatar-group-count",
    },
    slotClassNames: avatarSlotClassNames,
  },
  AlertDialog: {
    componentName: "AlertDialog",
    recipeName: "surface",
    sourceFile: "src/components/alert-dialog.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "header", "footer", "label", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "alert-dialog-content",
      body: "alert-dialog-overlay",
      header: "alert-dialog-header",
      footer: "alert-dialog-footer",
      label: "alert-dialog-title",
      state: "alert-dialog-description",
    },
    slotClassNames: alertDialogSlotClassNames,
    slotClassNamesByKey: alertDialogSlotClassNamesByKey,
    dataSlotByKey: { media: "alert-dialog-media" },
  },
  Form: {
    componentName: "Form",
    recipeName: "form-control",
    sourceFile: "src/components/form.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "form" },
    slotClassNames: {},
  },
  DataTable: {
    componentName: "DataTable",
    recipeName: "table",
    sourceFile: "src/components/data-table.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "data-table",
      icon: "data-table-empty-cell",
    },
    slotClassNames: {
      root: dataTableRootSlotClassName,
      icon: dataTableEmptyCellSlotClassName,
    },
  },
  Toaster: {
    componentName: "Toaster",
    recipeName: "surface",
    sourceFile: "src/components/sonner.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "toaster",
      icon: "toaster-icon",
    },
    slotClassNames: toasterSlotClassNames,
    slotClassNamesByKey: toasterSlotClassNamesByKey,
    dataSlotByKey: {
      loading: "toaster-loading-icon",
      success: "toaster-success-icon",
      info: "toaster-info-icon",
      warning: "toaster-warning-icon",
      error: "toaster-error-icon",
    },
  },
  Progress: {
    componentName: "Progress",
    recipeName: "form-control",
    sourceFile: "src/components/progress.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "progress",
      control: "progress-indicator",
    },
    slotClassNames: progressSlotClassNames,
  },
  Toggle: {
    componentName: "Toggle",
    recipeName: "form-control",
    sourceFile: "src/components/toggle.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "feedback",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "toggle" },
    slotClassNames: { root: "" },
  },
  ToggleGroup: {
    componentName: "ToggleGroup",
    recipeName: "form-control",
    sourceFile: "src/components/toggle-group.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control"],
    motion: "feedback",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "toggle-group",
      control: "toggle-group-item",
    },
    slotClassNames: toggleGroupSlotClassNames,
  },
  Slider: {
    componentName: "Slider",
    recipeName: "form-control",
    sourceFile: "src/components/slider.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "content", "control"],
    motion: "feedback",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "slider",
      body: "slider-track",
      content: "slider-range",
      control: "slider-thumb",
    },
    slotClassNames: sliderSlotClassNames,
  },
  Accordion: {
    componentName: "Accordion",
    recipeName: "surface",
    sourceFile: "src/components/accordion.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "label", "control", "content", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "accordion",
      label: "accordion-item",
      control: "accordion-trigger",
      content: "accordion-content",
      icon: "accordion-trigger-icon",
    },
    slotClassNames: accordionSlotClassNames,
    slotClassNamesByKey: accordionSlotClassNamesByKey,
    dataSlotByKey: {
      header: "accordion-header",
      "content-inner": "accordion-content-inner",
      "trigger-icon-down": "accordion-trigger-icon",
      "trigger-icon-up": "accordion-trigger-icon",
    },
  },
  HoverCard: {
    componentName: "HoverCard",
    recipeName: "surface",
    sourceFile: "src/components/hover-card.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "hover-card-content",
    },
    slotClassNames: hoverCardSlotClassNames,
    slotClassNamesByKey: hoverCardSlotClassNamesByKey,
    dataSlotByKey: {
      trigger: "hover-card-trigger",
      portal: "hover-card-portal",
    },
  },
  Kbd: {
    componentName: "Kbd",
    recipeName: "form-control",
    sourceFile: "src/components/kbd.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "kbd" },
    slotClassNames: kbdSlotClassNames,
    slotClassNamesByKey: kbdSlotClassNamesByKey,
    dataSlotByKey: { group: "kbd-group" },
  },
  Spinner: {
    componentName: "Spinner",
    recipeName: "form-control",
    sourceFile: "src/components/spinner.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "spinner" },
    slotClassNames: spinnerSlotClassNames,
    slotClassNamesByKey: spinnerSlotClassNamesByKey,
  },
  StatusIndicator: {
    componentName: "StatusIndicator",
    recipeName: "status",
    sourceFile: "src/components/status-indicator.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "label"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "status-indicator",
      label: "status-indicator-label",
    },
    slotClassNames: statusIndicatorSlotClassNames,
    slotClassNamesByKey: statusIndicatorDotClassNamesByKey,
    dataSlotByKey: {
      "dot-neutral": "status-indicator-dot",
      "dot-info": "status-indicator-dot",
      "dot-success": "status-indicator-dot",
      "dot-warning": "status-indicator-dot",
      "dot-danger": "status-indicator-dot",
      "dot-critical": "status-indicator-dot",
      "dot-pending": "status-indicator-dot",
      "dot-forbidden": "status-indicator-dot",
      "dot-invalid": "status-indicator-dot",
    },
  },
  Empty: {
    componentName: "Empty",
    recipeName: "surface",
    sourceFile: "src/components/empty.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "header", "icon", "label", "body", "content"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "empty",
      header: "empty-header",
      icon: "empty-icon",
      label: "empty-title",
      body: "empty-description",
      content: "empty-content",
    },
    slotClassNames: emptySlotClassNames,
    slotClassNamesByKey: {
      "media-default": emptyMediaVariantClassNames.default,
      "media-icon": emptyMediaVariantClassNames.icon,
    },
  },
  Collapsible: {
    componentName: "Collapsible",
    recipeName: "surface",
    sourceFile: "src/components/collapsible.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control", "content"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "collapsible",
      control: "collapsible-trigger",
      content: "collapsible-content",
    },
    slotClassNames: {},
  },
  AspectRatio: {
    componentName: "AspectRatio",
    recipeName: "surface",
    sourceFile: "src/components/aspect-ratio.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "aspect-ratio" },
    slotClassNames: {},
  },
  Direction: {
    componentName: "Direction",
    recipeName: "surface",
    sourceFile: "src/components/direction.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: { root: "direction" },
    slotClassNames: {},
  },
  InputGroup: {
    componentName: "InputGroup",
    recipeName: "form-control",
    sourceFile: "src/components/input-group.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control", "actions", "body", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "input-group",
      control: "input-group-addon",
      actions: "input-group-button",
      body: "input-group-text",
      state: "input-group-control",
    },
    slotClassNames: inputGroupSlotClassNames,
    slotClassNamesByKey: inputGroupSlotClassNamesByKey,
    dataSlotByKey: {
      "addon-inline-start": "input-group-addon",
      "addon-inline-end": "input-group-addon",
      "addon-block-start": "input-group-addon",
      "addon-block-end": "input-group-addon",
      "button-xs": "input-group-button",
      "button-sm": "input-group-button",
      "button-icon-xs": "input-group-button",
      "button-icon-sm": "input-group-button",
      "control-input": "input-group-control",
      "control-textarea": "input-group-control",
    },
  },
  InputOTP: {
    componentName: "InputOTP",
    recipeName: "form-control",
    sourceFile: "src/components/input-otp.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "control", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "input-otp",
      body: "input-otp-group",
      control: "input-otp-slot",
      icon: "input-otp-separator",
    },
    slotClassNames: inputOtpSlotClassNames,
    slotClassNamesByKey: inputOtpSlotClassNamesByKey,
    dataSlotByKey: {
      "group-shell": "input-otp-group",
      "caret-blink": "input-otp-slot",
      "caret-line": "input-otp-slot",
    },
  },
  NativeSelect: {
    componentName: "NativeSelect",
    recipeName: "form-control",
    sourceFile: "src/components/native-select.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "control", "state"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "native-select-wrapper",
      control: "native-select",
      state: "native-select-option",
    },
    slotClassNames: nativeSelectSlotClassNames,
    slotClassNamesByKey: nativeSelectSlotClassNamesByKey,
    dataSlotByKey: {
      icon: "native-select-icon",
      optgroup: "native-select-optgroup",
    },
  },
  Command: {
    componentName: "Command",
    recipeName: "surface",
    sourceFile: "src/components/command.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "control",
      "content",
      "state",
      "label",
      "footer",
      "actions",
      "header",
    ],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "command",
      body: "command-input-wrapper",
      control: "command-input",
      content: "command-list",
      state: "command-empty",
      label: "command-group",
      footer: "command-separator",
      actions: "command-item",
      header: "command-shortcut",
    },
    slotClassNames: commandSlotClassNames,
    slotClassNamesByKey: commandSlotClassNamesByKey,
    dataSlotByKey: {
      "dialog-content": "dialog-content",
      "dialog-header-sr": "dialog-header",
      "input-group-shell": "input-group",
      "input-search-icon": "command-search-icon",
      "item-check": "command-item",
    },
  },
  Combobox: {
    componentName: "Combobox",
    recipeName: "surface",
    sourceFile: "src/components/combobox.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "content",
      "control",
      "state",
      "footer",
      "label",
      "actions",
      "header",
      "icon",
    ],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "combobox-trigger",
      body: "combobox-content",
      content: "combobox-list",
      control: "combobox-item",
      state: "combobox-label",
      footer: "combobox-separator",
      label: "combobox-empty",
      actions: "combobox-chips",
      header: "combobox-chip",
      icon: "combobox-chip-input",
    },
    slotClassNames: comboboxSlotClassNames,
    slotClassNamesByKey: comboboxSlotClassNamesByKey,
    dataSlotByKey: {
      positioner: "combobox-content",
      "trigger-chevron": "combobox-trigger",
      "item-indicator": "combobox-item",
      "chip-remove": "combobox-chip-remove",
      "input-group-shell": "input-group",
      "input-group-button": "input-group-button",
      value: "combobox-value",
      collection: "combobox-collection",
      group: "combobox-group",
      clear: "combobox-clear",
      "clear-icon": "combobox-clear",
      "check-icon": "combobox-item",
      "chip-remove-icon": "combobox-chip-remove",
    },
  },
  Carousel: {
    componentName: "Carousel",
    recipeName: "surface",
    sourceFile: "src/components/carousel.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "content", "label", "control"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "carousel",
      body: "carousel-content",
      content: "carousel-content",
      label: "carousel-item",
      control: "carousel-previous",
    },
    slotClassNames: carouselSlotClassNames,
    slotClassNamesByKey: carouselSlotClassNamesByKey,
    dataSlotByKey: {
      "content-horizontal": "carousel-content",
      "content-vertical": "carousel-content",
      "item-horizontal": "carousel-item",
      "item-vertical": "carousel-item",
      "previous-horizontal": "carousel-previous",
      "previous-vertical": "carousel-previous",
      "next-horizontal": "carousel-next",
      "next-vertical": "carousel-next",
      "sr-only": "carousel-previous",
    },
  },
  Calendar: {
    componentName: "Calendar",
    recipeName: "surface",
    sourceFile: "src/components/calendar.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "control", "content", "label", "state", "icon"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "calendar",
      body: "calendar",
      control: "button",
      content: "calendar",
      label: "calendar",
      state: "calendar",
      icon: "calendar",
    },
    slotClassNames: calendarSlotClassNames,
    slotClassNamesByKey: calendarSlotClassNamesByKey,
    dataSlotByKey: calendarDataSlotByKey,
  },
  Chart: {
    componentName: "Chart",
    recipeName: "surface",
    sourceFile: "src/components/chart.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "content",
      "control",
      "label",
      "state",
      "actions",
      "header",
      "icon",
      "footer",
    ],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "chart",
      body: "chart-tooltip",
      content: "chart-tooltip",
      control: "chart-tooltip",
      label: "chart-tooltip",
      state: "chart-tooltip",
      actions: "chart-tooltip",
      header: "chart-legend",
      icon: "chart-legend",
      footer: "chart-tooltip",
    },
    slotClassNames: chartSlotClassNames,
    slotClassNamesByKey: chartSlotClassNamesByKey,
    dataSlotByKey: {
      "tooltip-row-dot": "chart-tooltip-row",
      "tooltip-row-default": "chart-tooltip-row",
      "tooltip-label-end": "chart-tooltip-footer",
      "tooltip-label-center": "chart-tooltip-footer",
      "tooltip-label-grid": "chart-tooltip-label-grid",
      "indicator-dot": "chart-tooltip-indicator",
      "indicator-line": "chart-tooltip-indicator",
      "indicator-dashed": "chart-tooltip-indicator",
      "indicator-dashed-nested": "chart-tooltip-indicator",
      "legend-top": "chart-legend",
      "legend-bottom": "chart-legend",
      "legend-swatch": "chart-legend-swatch",
    },
  },
  Resizable: {
    componentName: "Resizable",
    recipeName: "surface",
    sourceFile: "src/components/resizable.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: ["root", "body", "control"],
    motion: "instant",
    allowAsChild: false,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "resizable-panel-group",
      body: "resizable-panel",
      control: "resizable-handle",
    },
    slotClassNames: resizableSlotClassNames,
    slotClassNamesByKey: resizableSlotClassNamesByKey,
    dataSlotByKey: { "handle-grip": "resizable-handle-grip" },
  },
  Sidebar: {
    componentName: "Sidebar",
    recipeName: "surface",
    sourceFile: "src/components/sidebar.tsx",
    defaultState: "ready",
    defaultSlot: "root",
    slots: [
      "root",
      "body",
      "content",
      "header",
      "footer",
      "label",
      "control",
      "state",
      "actions",
      "icon",
    ],
    motion: "instant",
    allowAsChild: true,
    controlPresentation: "leaf",
    dataSlotByRole: {
      root: "sidebar-wrapper",
      body: "sidebar",
      content: "sidebar-content",
      header: "sidebar-header",
      footer: "sidebar-footer",
      label: "sidebar-group-label",
      control: "sidebar-group-action",
      state: "sidebar-group-content",
      actions: "sidebar-menu",
      icon: "sidebar-menu-item",
    },
    slotClassNames: sidebarSlotClassNames,
    slotClassNamesByKey: sidebarSlotClassNamesByKey,
    dataSlotByKey: {
      sidebar: "sidebar",
      "mobile-content": "sidebar",
      "mobile-inner": "sidebar",
      "mobile-header": "sidebar",
      gap: "sidebar-gap",
      "gap-floating": "sidebar-gap",
      "gap-sidebar": "sidebar-gap",
      container: "sidebar-container",
      "container-floating": "sidebar-container",
      "container-sidebar": "sidebar-container",
      inner: "sidebar-inner",
      rail: "sidebar-rail",
      inset: "sidebar-inset",
      input: "sidebar-input",
      separator: "sidebar-separator",
      "content-scroll": "sidebar-content",
      group: "sidebar-group",
      "menu-action": "sidebar-menu-action",
      "menu-action-hover": "sidebar-menu-action",
      "menu-badge": "sidebar-menu-badge",
      "menu-skeleton": "sidebar-menu-skeleton",
      "menu-skeleton-icon": "sidebar-menu-skeleton",
      "menu-skeleton-text": "sidebar-menu-skeleton",
      "menu-sub": "sidebar-menu-sub",
      "menu-sub-item": "sidebar-menu-sub-item",
      "menu-sub-button": "sidebar-menu-sub-button",
      "menu-button-default-default": "sidebar-menu-button",
      "menu-button-default-sm": "sidebar-menu-button",
      "menu-button-default-lg": "sidebar-menu-button",
      "menu-button-outline-default": "sidebar-menu-button",
      "menu-button-outline-sm": "sidebar-menu-button",
      "menu-button-outline-lg": "sidebar-menu-button",
      trigger: "sidebar-trigger",
      "sr-only": "sidebar-trigger",
    },
  },
} as const satisfies Record<
  GovernedUiComponentName,
  GovernedPrimitiveDefinition
>;

/** Governed component source paths — enforced by CI in phase 1. */
export const GOVERNED_COMPONENT_SOURCE_FILES = GOVERNED_UI_COMPONENTS.map(
  (componentName) => GOVERNED_PRIMITIVE_REGISTRY[componentName].sourceFile
);

/**
 * Stock shadcn/Radix components not yet wired through primitive governance.
 * Every exported component must appear here or in {@link GOVERNED_PRIMITIVE_REGISTRY}.
 */
export const STOCK_SHADCN_PENDING = [] as const;

export type StockShadcnPendingFile = (typeof STOCK_SHADCN_PENDING)[number];

/** PascalCase exports from index.ts that map to stock pending files. */
export const EXPORTED_STOCK_COMPONENTS = [] as const;

const governedSourceFileSet = new Set<string>(GOVERNED_COMPONENT_SOURCE_FILES);
const stockPendingSourceFileSet = new Set<string>(STOCK_SHADCN_PENDING);

export function isGovernedPrimitive(
  componentName: string
): componentName is GovernedUiComponentName {
  return Object.hasOwn(GOVERNED_PRIMITIVE_REGISTRY, componentName);
}

export function getPrimitiveDefinition(
  componentName: GovernedUiComponentName
): GovernedPrimitiveDefinition {
  return GOVERNED_PRIMITIVE_REGISTRY[componentName];
}

export function isGovernedSourceFile(relativePath: string): boolean {
  return governedSourceFileSet.has(relativePath);
}

export function isStockPendingSourceFile(relativePath: string): boolean {
  return stockPendingSourceFileSet.has(relativePath);
}

export const PRIMARY_UI_EXPORTS = [
  ...GOVERNED_UI_COMPONENTS,
  ...EXPORTED_STOCK_COMPONENTS,
] as const;

export function assertComponentExportCoverage(
  componentExportName: string
): void {
  if (isGovernedPrimitive(componentExportName)) {
    return;
  }

  if (
    (EXPORTED_STOCK_COMPONENTS as readonly string[]).includes(
      componentExportName
    )
  ) {
    return;
  }

  throw new Error(
    `Governed UI export coverage violation. "${componentExportName}" is exported from @afenda/ui but is not registered as governed or stock pending.`
  );
}
