export {
  assertTenantHumanReferenceWireText,
  TENANT_HUMAN_REFERENCE_MAX_WIRE_LENGTH,
  type WireTenantHumanReference,
} from "./tenant-human-reference.assert.js";
export {
  type AssetNo,
  type CustomerNo,
  type DocumentNo,
  type EmployeeNo,
  normalizeAssetNoForWire,
  normalizeCustomerNoForWire,
  normalizeDocumentNoForWire,
  normalizeEmployeeNoForWire,
  normalizeSkuNoForWire,
  normalizeSupplierNoForWire,
  normalizeTenantHumanReferenceForWire,
  normalizeWarehouseCodeForWire,
  parseAssetNo,
  parseCustomerNo,
  parseDocumentNo,
  parseEmployeeNo,
  parseOptionalAssetNo,
  parseOptionalCustomerNo,
  parseOptionalDocumentNo,
  parseOptionalEmployeeNo,
  parseOptionalSkuNo,
  parseOptionalSupplierNo,
  parseOptionalTenantHumanReference,
  parseOptionalTenantHumanReferenceForScope,
  parseOptionalWarehouseCode,
  parseSkuNo,
  parseSupplierNo,
  parseTenantHumanReference,
  parseTenantHumanReferenceForScope,
  parseWarehouseCode,
  type SkuNo,
  type SupplierNo,
  TENANT_HUMAN_REFERENCE_SCOPE_DEFINITIONS,
  TENANT_HUMAN_REFERENCE_SCOPES,
  type TenantHumanReference,
  type TenantHumanReferenceScope,
  type TenantHumanReferenceScopeDefinition,
  type WarehouseCode,
} from "./tenant-human-reference.contract.js";
export {
  parseOptionalTenantHumanReferenceWireForScope,
  parseTenantHumanReferenceWireForScope,
  parseUnknownTenantHumanReferenceWireForScope,
} from "./tenant-human-reference.parser.js";
