// biome-ignore-all lint/performance/noBarrelFile: package root is the curated public API surface.

export const PACKAGE_NAME = "@afenda/metadata" as const;

export function getPackageName(): typeof PACKAGE_NAME {
  return PACKAGE_NAME;
}

export type {
  CrossPackageAuthority,
  CrossPackageAuthorityEntry,
  CrossPackageName,
  LayoutContract,
  LayoutDefinition,
  LayoutType,
  MetadataAiGovernanceRules,
  MetadataAuthorityDecision,
  MetadataAuthorityKey,
  MetadataAuthorityOwnership,
  MetadataContract,
  MetadataDensityMode,
  MetadataIdentity,
  MetadataLifecycleState,
  MetadataRuntimeContext,
  PresentationContract,
  PresentationDefinition,
  PresentationMode,
  ReadonlyMode,
  RegistrationLifecycleState,
  RegistryContract,
  RegistryEntry,
  RendererCapability,
  RendererCompatibilityRule,
  RendererContract,
  RuntimeContract,
  RuntimeDiagnostic,
  RuntimeDiagnosticLevel,
  SectionContract,
  SectionDefinition,
  SectionType,
  SurfaceContract,
  SurfaceDefinition,
  SurfaceType,
  VisibilityMode,
} from "./contracts/index.js";
export {
  CROSS_PACKAGE_NAMES,
  crossPackageAuthority,
  DENSITY_MODES,
  LAYOUT_TYPES,
  layoutContract,
  METADATA_AUTHORITY_KEYS,
  METADATA_LIFECYCLE_STATES,
  metadataAiGovernanceRules,
  metadataAuthorityMap,
  metadataContract,
  PRESENTATION_MODES,
  presentationContract,
  READONLY_MODES,
  REGISTRATION_LIFECYCLE_STATES,
  RENDERER_CAPABILITIES,
  RUNTIME_DIAGNOSTIC_LEVELS,
  registryContract,
  rendererContract,
  runtimeContract,
  SECTION_TYPES,
  SURFACE_TYPES,
  sectionContract,
  surfaceContract,
  VISIBILITY_MODES,
} from "./contracts/index.js";
