"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mapPlatformRolloutToEvaluationData = exports.mapDatabaseBundleToEvaluationData = exports.resolveLocalizationAccess = exports.localization = exports.resolveUsageLimit = exports.limit = exports.resolveKillSwitch = exports.FEATURE_FLAG_STRICT_POLICY = exports.FEATURE_FLAG_ROLLOUT_POLICY = exports.FEATURE_FLAG_FAIL_OPEN_DEFAULT = exports.resolveFeatureFlagStrict = exports.resolveFeatureFlag = exports.featureFlag = exports.proTierFixture = exports.enterpriseTierFixture = exports.disabledStateFixture = exports.buildContext = exports.betaTierFixture = exports.basicTierFixture = exports.governedUsageLimitsExample = exports.governedLocalizationsExample = exports.governedKillSwitchesExample = exports.governedFeatureFlagsExample = exports.governedEntitlementsExample = exports.governedEntitlementContextExample = exports.governedBetaFlagsExample = exports.featureManifests = exports.resolveEntitlement = exports.entitlement = exports.getCapability = exports.capabilityList = exports.capabilities = exports.evaluateCapability = exports.requiredUsageLimitKeys = exports.entitlementDecisionResults = exports.entitlementTypes = exports.createUpstashEvaluationCache = exports.probeUpstashRedisConnectivity = exports.MissingUpstashRedisConfigError = exports.hasUpstashRedisConfig = exports.getUpstashRedisConfig = exports.createUpstashEvaluationCacheFromEnv = exports.createEvaluationCacheFromEnv = exports.createMemoryEvaluationCache = exports.createCachedCapabilityEvaluator = exports.buildEvaluationCacheKey = exports.resolveBetaAccess = exports.beta = exports.createEntitlementAuditEvent = exports.PACKAGE_NAME = void 0;
exports.getPackageName = getPackageName;
// biome-ignore-all lint/performance/noBarrelFile: TIP-008 requires a stable public root export surface.
exports.PACKAGE_NAME = "@afenda/entitlements";
function getPackageName() {
    return exports.PACKAGE_NAME;
}
var entitlement_audit_1 = require("./audit/entitlement-audit");
Object.defineProperty(exports, "createEntitlementAuditEvent", { enumerable: true, get: function () { return entitlement_audit_1.createEntitlementAuditEvent; } });
var beta_access_engine_1 = require("./beta/beta-access-engine");
Object.defineProperty(exports, "beta", { enumerable: true, get: function () { return beta_access_engine_1.beta; } });
Object.defineProperty(exports, "resolveBetaAccess", { enumerable: true, get: function () { return beta_access_engine_1.resolveBetaAccess; } });
var evaluation_cache_1 = require("./cache/evaluation-cache");
Object.defineProperty(exports, "buildEvaluationCacheKey", { enumerable: true, get: function () { return evaluation_cache_1.buildEvaluationCacheKey; } });
Object.defineProperty(exports, "createCachedCapabilityEvaluator", { enumerable: true, get: function () { return evaluation_cache_1.createCachedCapabilityEvaluator; } });
Object.defineProperty(exports, "createMemoryEvaluationCache", { enumerable: true, get: function () { return evaluation_cache_1.createMemoryEvaluationCache; } });
var redis_env_1 = require("./cache/redis-env");
Object.defineProperty(exports, "createEvaluationCacheFromEnv", { enumerable: true, get: function () { return redis_env_1.createEvaluationCacheFromEnv; } });
Object.defineProperty(exports, "createUpstashEvaluationCacheFromEnv", { enumerable: true, get: function () { return redis_env_1.createUpstashEvaluationCacheFromEnv; } });
Object.defineProperty(exports, "getUpstashRedisConfig", { enumerable: true, get: function () { return redis_env_1.getUpstashRedisConfig; } });
Object.defineProperty(exports, "hasUpstashRedisConfig", { enumerable: true, get: function () { return redis_env_1.hasUpstashRedisConfig; } });
Object.defineProperty(exports, "MissingUpstashRedisConfigError", { enumerable: true, get: function () { return redis_env_1.MissingUpstashRedisConfigError; } });
Object.defineProperty(exports, "probeUpstashRedisConnectivity", { enumerable: true, get: function () { return redis_env_1.probeUpstashRedisConnectivity; } });
var upstash_evaluation_cache_1 = require("./cache/upstash-evaluation-cache");
Object.defineProperty(exports, "createUpstashEvaluationCache", { enumerable: true, get: function () { return upstash_evaluation_cache_1.createUpstashEvaluationCache; } });
var entitlement_contract_1 = require("./contracts/entitlement.contract");
Object.defineProperty(exports, "entitlementTypes", { enumerable: true, get: function () { return entitlement_contract_1.entitlementTypes; } });
var entitlement_decision_contract_1 = require("./contracts/entitlement-decision.contract");
Object.defineProperty(exports, "entitlementDecisionResults", { enumerable: true, get: function () { return entitlement_decision_contract_1.entitlementDecisionResults; } });
var usage_limit_contract_1 = require("./contracts/usage-limit.contract");
Object.defineProperty(exports, "requiredUsageLimitKeys", { enumerable: true, get: function () { return usage_limit_contract_1.requiredUsageLimitKeys; } });
var capability_evaluation_1 = require("./evaluation/capability-evaluation");
Object.defineProperty(exports, "evaluateCapability", { enumerable: true, get: function () { return capability_evaluation_1.evaluateCapability; } });
var capability_registry_1 = require("./evaluation/capability-registry");
Object.defineProperty(exports, "capabilities", { enumerable: true, get: function () { return capability_registry_1.capabilities; } });
Object.defineProperty(exports, "capabilityList", { enumerable: true, get: function () { return capability_registry_1.capabilityList; } });
Object.defineProperty(exports, "getCapability", { enumerable: true, get: function () { return capability_registry_1.getCapability; } });
var entitlement_engine_1 = require("./evaluation/entitlement-engine");
Object.defineProperty(exports, "entitlement", { enumerable: true, get: function () { return entitlement_engine_1.entitlement; } });
Object.defineProperty(exports, "resolveEntitlement", { enumerable: true, get: function () { return entitlement_engine_1.resolveEntitlement; } });
var feature_manifest_1 = require("./evaluation/feature-manifest");
Object.defineProperty(exports, "featureManifests", { enumerable: true, get: function () { return feature_manifest_1.featureManifests; } });
var governed_entitlement_example_1 = require("./examples/governed-entitlement.example");
Object.defineProperty(exports, "governedBetaFlagsExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedBetaFlagsExample; } });
Object.defineProperty(exports, "governedEntitlementContextExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedEntitlementContextExample; } });
Object.defineProperty(exports, "governedEntitlementsExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedEntitlementsExample; } });
Object.defineProperty(exports, "governedFeatureFlagsExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedFeatureFlagsExample; } });
Object.defineProperty(exports, "governedKillSwitchesExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedKillSwitchesExample; } });
Object.defineProperty(exports, "governedLocalizationsExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedLocalizationsExample; } });
Object.defineProperty(exports, "governedUsageLimitsExample", { enumerable: true, get: function () { return governed_entitlement_example_1.governedUsageLimitsExample; } });
var tier_fixtures_1 = require("./fixtures/tier-fixtures");
Object.defineProperty(exports, "basicTierFixture", { enumerable: true, get: function () { return tier_fixtures_1.basicTierFixture; } });
Object.defineProperty(exports, "betaTierFixture", { enumerable: true, get: function () { return tier_fixtures_1.betaTierFixture; } });
Object.defineProperty(exports, "buildContext", { enumerable: true, get: function () { return tier_fixtures_1.buildContext; } });
Object.defineProperty(exports, "disabledStateFixture", { enumerable: true, get: function () { return tier_fixtures_1.disabledStateFixture; } });
Object.defineProperty(exports, "enterpriseTierFixture", { enumerable: true, get: function () { return tier_fixtures_1.enterpriseTierFixture; } });
Object.defineProperty(exports, "proTierFixture", { enumerable: true, get: function () { return tier_fixtures_1.proTierFixture; } });
var feature_flag_engine_1 = require("./flags/feature-flag-engine");
Object.defineProperty(exports, "featureFlag", { enumerable: true, get: function () { return feature_flag_engine_1.featureFlag; } });
Object.defineProperty(exports, "resolveFeatureFlag", { enumerable: true, get: function () { return feature_flag_engine_1.resolveFeatureFlag; } });
Object.defineProperty(exports, "resolveFeatureFlagStrict", { enumerable: true, get: function () { return feature_flag_engine_1.resolveFeatureFlagStrict; } });
var feature_flag_policy_1 = require("./flags/feature-flag-policy");
Object.defineProperty(exports, "FEATURE_FLAG_FAIL_OPEN_DEFAULT", { enumerable: true, get: function () { return feature_flag_policy_1.FEATURE_FLAG_FAIL_OPEN_DEFAULT; } });
Object.defineProperty(exports, "FEATURE_FLAG_ROLLOUT_POLICY", { enumerable: true, get: function () { return feature_flag_policy_1.FEATURE_FLAG_ROLLOUT_POLICY; } });
Object.defineProperty(exports, "FEATURE_FLAG_STRICT_POLICY", { enumerable: true, get: function () { return feature_flag_policy_1.FEATURE_FLAG_STRICT_POLICY; } });
var kill_switch_engine_1 = require("./flags/kill-switch-engine");
Object.defineProperty(exports, "resolveKillSwitch", { enumerable: true, get: function () { return kill_switch_engine_1.resolveKillSwitch; } });
var usage_limit_engine_1 = require("./limits/usage-limit-engine");
Object.defineProperty(exports, "limit", { enumerable: true, get: function () { return usage_limit_engine_1.limit; } });
Object.defineProperty(exports, "resolveUsageLimit", { enumerable: true, get: function () { return usage_limit_engine_1.resolveUsageLimit; } });
var localization_engine_1 = require("./localization/localization-engine");
Object.defineProperty(exports, "localization", { enumerable: true, get: function () { return localization_engine_1.localization; } });
Object.defineProperty(exports, "resolveLocalizationAccess", { enumerable: true, get: function () { return localization_engine_1.resolveLocalizationAccess; } });
var database_bundle_mapper_1 = require("./provisioning/database-bundle.mapper");
Object.defineProperty(exports, "mapDatabaseBundleToEvaluationData", { enumerable: true, get: function () { return database_bundle_mapper_1.mapDatabaseBundleToEvaluationData; } });
var rollout_bundle_mapper_1 = require("./provisioning/rollout-bundle.mapper");
Object.defineProperty(exports, "mapPlatformRolloutToEvaluationData", { enumerable: true, get: function () { return rollout_bundle_mapper_1.mapPlatformRolloutToEvaluationData; } });
