/**
 * PAS-001 §4.1 — public identity surface.
 *
 * Downstream packages import family parsers and branded types from here.
 * Do not import `Brand` to define local enterprise ID aliases.
 */
export { type Brand, unbrand } from "./brand/index.js";
export {
  ANY_CANONICAL_ENTERPRISE_ID_PATTERN,
  assertCanonicalIdBody,
  assertEnterpriseIdPrefix,
  assertRegisteredEnterpriseIdPrefix,
  buildCanonicalEnterpriseIdPatternSource,
  buildCanonicalEnterpriseIdRegex,
  CANONICAL_ID_BODY_LENGTH,
  CANONICAL_ID_BODY_PATTERN,
  CANONICAL_ID_PATTERN,
  CANONICAL_ID_PATTERN_SOURCE,
  CANONICAL_ID_PREFIX_LENGTH,
  CANONICAL_ID_PREFIX_PATTERN,
  CANONICAL_ID_SEPARATOR,
  type CanonicalEnterpriseId,
  type CanonicalId,
  type CanonicalIdBodyGenerator,
  createCanonicalId,
  createFixtureCanonicalIdBodyGenerator,
  FIXTURE_CANONICAL_ID_BODY,
  InvalidCanonicalIdError,
  isCanonicalEnterpriseId,
  isCanonicalEnterpriseIdForFamily,
  isCanonicalIdBody,
  isRegisteredCanonicalEnterpriseId,
  type ParsedRegisteredCanonicalEnterpriseId,
  parseCanonicalId,
  parseOptionalCanonicalId,
  parseRegisteredCanonicalEnterpriseId,
  tryParseCanonicalId,
  tryParseRegisteredCanonicalEnterpriseId,
} from "./canonical/index.js";
export {
  type AssetId,
  type AuditEventId,
  type CompanyId,
  type CorrelationId,
  type CustomerId,
  createAssetId,
  createAuditEventId,
  createCompanyId,
  createCorrelationId,
  createCustomerId,
  createDocumentId,
  createEmployeeId,
  createEntityGroupId,
  createExecutionId,
  createMembershipId,
  createOrganizationId,
  createOwnershipInterestId,
  createPermissionId,
  createPolicyId,
  createProductId,
  createProjectId,
  createRoleId,
  createSupplierId,
  createTeamId,
  createTenantId,
  createTestEnterpriseId,
  createUserId,
  createWarehouseId,
  type DocumentId,
  type EmployeeId,
  type EnterpriseBrand,
  type EntityGroupId,
  type ExecutionId,
  type MembershipId,
  normalizeAssetIdForWire,
  normalizeAuditEventIdForWire,
  normalizeCompanyIdForWire,
  normalizeCorrelationIdForWire,
  normalizeCustomerIdForWire,
  normalizeDocumentIdForWire,
  normalizeEmployeeIdForWire,
  normalizeEntityGroupIdForWire,
  normalizeExecutionIdForWire,
  normalizeMembershipIdForWire,
  normalizeOrganizationIdForWire,
  normalizeOwnershipInterestIdForWire,
  normalizePermissionIdForWire,
  normalizePolicyIdForWire,
  normalizeProductIdForWire,
  normalizeProjectIdForWire,
  normalizeRoleIdForWire,
  normalizeSupplierIdForWire,
  normalizeTeamIdForWire,
  normalizeTenantIdForWire,
  normalizeUserIdForWire,
  normalizeWarehouseIdForWire,
  type OrganizationId,
  type OwnershipInterestId,
  type PermissionId,
  type PolicyId,
  type ProductId,
  type ProjectId,
  parseAssetId,
  parseAuditEventId,
  parseCompanyId,
  parseCorrelationId,
  parseCustomerId,
  parseDocumentId,
  parseEmployeeId,
  parseEntityGroupId,
  parseExecutionId,
  parseMembershipId,
  parseOptionalAssetId,
  parseOptionalAuditEventId,
  parseOptionalCompanyId,
  parseOptionalCustomerId,
  parseOptionalDocumentId,
  parseOptionalEmployeeId,
  parseOptionalEntityGroupId,
  parseOptionalMembershipId,
  parseOptionalOrganizationId,
  parseOptionalOwnershipInterestId,
  parseOptionalPermissionId,
  parseOptionalPolicyId,
  parseOptionalProductId,
  parseOptionalProjectId,
  parseOptionalRoleId,
  parseOptionalSupplierId,
  parseOptionalTeamId,
  parseOptionalTenantId,
  parseOptionalUserId,
  parseOptionalWarehouseId,
  parseOrganizationId,
  parseOwnershipInterestId,
  parsePermissionId,
  parsePolicyId,
  parseProductId,
  parseProjectId,
  parseRoleId,
  parseSupplierId,
  parseTeamId,
  parseTenantId,
  parseUserId,
  parseWarehouseId,
  type RoleId,
  type SupplierId,
  type TeamId,
  type TenantId,
  toAssetId,
  toAuditEventId,
  toCompanyId,
  toCorrelationId,
  toCustomerId,
  toDocumentId,
  toEmployeeId,
  toEntityGroupId,
  toExecutionId,
  toMembershipId,
  toOrganizationId,
  toOwnershipInterestId,
  toPermissionId,
  toPolicyId,
  toProductId,
  toProjectId,
  toRoleId,
  toSupplierId,
  toTeamId,
  toTenantId,
  toUserId,
  toWarehouseId,
  type UserId,
  type WarehouseId,
} from "./families/index.js";
export {
  IDENTITY_BOUNDARY_POLICY,
  IDENTITY_BOUNDARY_PROHIBITED_PATTERNS,
} from "./governance/identity-boundary-policy.contract.js";
export {
  getIdentityStackLayer,
  IDENTITY_STACK_LAYER_IDS,
  IDENTITY_STACK_LAYERS,
  IDENTITY_STACK_POLICY,
  type IdentityStackLayerDefinition,
  type IdentityStackLayerId,
  type IdentityStackProhibitedCrossLayerPattern,
  isIdentityStackLayerId,
} from "./governance/identity-stack.contract.js";
export {
  IDENTITY_TRUST_BOUNDARY_POLICY,
  IDENTITY_TRUST_BOUNDARY_PROHIBITED_PATTERNS,
  type IdentityTrustBoundaryProhibitedPattern,
} from "./governance/identity-trust-boundary.policy.js";
export {
  buildCanonicalEnterpriseIdCheckPattern,
  CANONICAL_ID_POSTGRES_CHECKS,
  getCanonicalIdPostgresCheckPattern,
  getPostgresCanonicalIdCheckPattern,
  POSTGRES_CANONICAL_ID_CHECK_PATTERNS,
  type PostgresCanonicalIdCheckPattern,
} from "./postgres/index.js";
export {
  brandCountryCode,
  brandCurrencyCode,
  brandDateFormat,
  brandLocaleCode,
  brandNumberFormat,
  brandRequiredCountryCode,
  brandRequiredCurrencyCode,
  brandRequiredUomCode,
  brandTimezoneId,
  brandUomCode,
  type CountryCode,
  type CurrencyCode,
  type DateFormat,
  type LocaleCode,
  type NumberFormat,
  normalizeCountryCodeForWire,
  normalizeCurrencyCodeForWire,
  normalizeDateFormatForWire,
  normalizeLocaleCodeForWire,
  normalizeNumberFormatForWire,
  normalizeTimezoneIdForWire,
  normalizeUomCodeForWire,
  parseCountryCode,
  parseCurrencyCode,
  parseDateFormat,
  parseLocaleCode,
  parseNumberFormat,
  parseTimezoneId,
  parseUomCode,
  type TimezoneId,
  toCountryCode,
  toCurrencyCode,
  toDateFormat,
  toLocaleCode,
  toNumberFormat,
  toTimezoneId,
  toUomCode,
  type UomCode,
} from "./primitives/index.js";
export {
  ENTERPRISE_ID_FAMILIES,
  ENTERPRISE_ID_FAMILY_KEYS,
  ENTERPRISE_ID_FAMILY_PREFIX_AUTHORITY,
  ENTERPRISE_ID_PREFIX_TO_FAMILY,
  ENTERPRISE_ID_TYPE_NAMES,
  type EnterpriseIdFamily,
  type EnterpriseIdPrefix,
  extractCanonicalEnterpriseIdPrefix,
  FORBIDDEN_PLATFORM_FLOOR_ID_SYMBOLS,
  type ForbiddenPlatformFloorIdSymbol,
  getEnterpriseIdFamiliesByCategory,
  getIdentityProhibitedPattern,
  getIdentityPromotionRequirement,
  getIdFamilyDefinition,
  getKernelIdentityGovernanceGate,
  getPlatformIdFamilyDefinition,
  ID_FAMILIES,
  ID_FAMILY_CATEGORIES,
  ID_FAMILY_COUNT,
  IDENTITY_AUTHORITY_ADR,
  IDENTITY_AUTHORITY_PAS,
  IDENTITY_AUTHORITY_SECTION,
  IDENTITY_GOVERNANCE_AUTHORITY,
  IDENTITY_PROHIBITED_PATTERN_IDS,
  IDENTITY_PROHIBITED_PATTERNS,
  IDENTITY_PROMOTION_PAS_CHECKLIST_STEPS,
  IDENTITY_PROMOTION_REQUIREMENT_IDS,
  IDENTITY_PROMOTION_REQUIREMENTS,
  type IdentityProhibitedPatternDefinition,
  type IdentityProhibitedPatternId,
  type IdentityPromotionPasChecklistStep,
  type IdentityPromotionPasChecklistStepDefinition,
  type IdentityPromotionRequirementDefinition,
  type IdentityPromotionRequirementId,
  type IdFamily,
  type IdFamilyCategory,
  type IdFamilyDefinition,
  type IdPrefix,
  isEnterpriseIdFamily,
  isForbiddenPlatformFloorIdSymbol,
  isIdentityProhibitedPatternId,
  isIdentityPromotionRequirementId,
  isKernelIdentityGovernanceGateId,
  isRegisteredEnterpriseIdPrefix,
  KERNEL_IDENTITY_GOVERNANCE_BUNDLE,
  KERNEL_IDENTITY_GOVERNANCE_GATE_SCRIPTS,
  KERNEL_IDENTITY_GOVERNANCE_GATES,
  type KernelIdentityGovernanceGateDefinition,
  type KernelIdentityGovernanceGateId,
  listIdentityProhibitedPatternsWithGate,
  listIdentityPromotionRequirementsForPasStep,
  PLATFORM_ID_AUTHORITY_PAS,
  PLATFORM_ID_AUTHORITY_SECTION,
  PLATFORM_ID_FAMILY_REGISTRY,
  PLATFORM_ID_FAMILY_TYPE_NAMES,
  type PlatformIdCategory,
  type PlatformIdFamilyDefinition,
  type PlatformIdFamilyTypeName,
  PRIMITIVE_ID_FAMILY_COUNT,
  PRIMITIVE_ID_FAMILY_KEYS,
  REGISTERED_ENTERPRISE_ID_PREFIXES,
  REGISTRY_FAMILY_COUNT,
  type RegisteredEnterpriseIdPrefix,
  resolveEnterpriseIdFamilyFromPrefix,
} from "./registry/index.js";
export {
  type AssetNo,
  type CustomerNo,
  type DocumentNo,
  type EmployeeNo,
  normalizeAssetNoForWire,
  normalizeCustomerNoForWire,
  normalizeDocumentNoForWire,
  normalizeEmployeeNoForWire,
  normalizeSkuNoForWire,
  normalizeSupplierNoForWire,
  normalizeTenantHumanReferenceForWire,
  normalizeWarehouseCodeForWire,
  parseAssetNo,
  parseCustomerNo,
  parseDocumentNo,
  parseEmployeeNo,
  parseOptionalAssetNo,
  parseOptionalCustomerNo,
  parseOptionalDocumentNo,
  parseOptionalEmployeeNo,
  parseOptionalSkuNo,
  parseOptionalSupplierNo,
  parseOptionalTenantHumanReference,
  parseOptionalWarehouseCode,
  parseSkuNo,
  parseSupplierNo,
  parseTenantHumanReference,
  parseWarehouseCode,
  type SkuNo,
  type SupplierNo,
  TENANT_HUMAN_REFERENCE_SCOPE_DEFINITIONS,
  TENANT_HUMAN_REFERENCE_SCOPES,
  type TenantHumanReference,
  type TenantHumanReferenceScope,
  type WarehouseCode,
} from "./tenant-human-reference/index.js";
export {
  type AuditEntityIdentity,
  type InternalEntityPk,
  parseAuditEntityIdentity,
  parseInternalEntityPk,
  parseWireCanonicalId,
  parseWireRegisteredCanonicalId,
  serializeAuditEntityIdentity,
  serializeCanonicalId,
  toInternalEntityPk,
  type WireAuditEntityIdentity,
  type WireCanonicalId,
} from "./wire/index.js";

import {
  normalizeAssetIdForWire,
  normalizeAuditEventIdForWire,
  normalizeCompanyIdForWire,
  normalizeCorrelationIdForWire,
  normalizeCustomerIdForWire,
  normalizeDocumentIdForWire,
  normalizeEmployeeIdForWire,
  normalizeEntityGroupIdForWire,
  normalizeExecutionIdForWire,
  normalizeMembershipIdForWire,
  normalizeOrganizationIdForWire,
  normalizeOwnershipInterestIdForWire,
  normalizePermissionIdForWire,
  normalizePolicyIdForWire,
  normalizeProductIdForWire,
  normalizeProjectIdForWire,
  normalizeRoleIdForWire,
  normalizeSupplierIdForWire,
  normalizeTeamIdForWire,
  normalizeTenantIdForWire,
  normalizeUserIdForWire,
  normalizeWarehouseIdForWire,
} from "./families/index.js";
import {
  normalizeCountryCodeForWire,
  normalizeCurrencyCodeForWire,
  normalizeDateFormatForWire,
  normalizeLocaleCodeForWire,
  normalizeNumberFormatForWire,
  normalizeTimezoneIdForWire,
  normalizeUomCodeForWire,
} from "./primitives/index.js";
import type { PLATFORM_ID_FAMILY_REGISTRY } from "./registry/index.js";

type RegistryFamily = (typeof PLATFORM_ID_FAMILY_REGISTRY)[number];

export const PLATFORM_ID_BOUNDARY_WIRE_NORMALIZERS = {
  normalizeTenantIdForWire,
  normalizeEntityGroupIdForWire,
  normalizeCompanyIdForWire,
  normalizeOrganizationIdForWire,
  normalizeTeamIdForWire,
  normalizeProjectIdForWire,
  normalizeUserIdForWire,
  normalizeRoleIdForWire,
  normalizeMembershipIdForWire,
  normalizePermissionIdForWire,
  normalizePolicyIdForWire,
  normalizeAuditEventIdForWire,
  normalizeExecutionIdForWire,
  normalizeCorrelationIdForWire,
  normalizeOwnershipInterestIdForWire,
  normalizeCustomerIdForWire,
  normalizeSupplierIdForWire,
  normalizeProductIdForWire,
  normalizeEmployeeIdForWire,
  normalizeWarehouseIdForWire,
  normalizeLocaleCodeForWire,
  normalizeTimezoneIdForWire,
  normalizeDateFormatForWire,
  normalizeNumberFormatForWire,
  normalizeCurrencyCodeForWire,
  normalizeCountryCodeForWire,
  normalizeUomCodeForWire,
  normalizeDocumentIdForWire,
  normalizeAssetIdForWire,
} as const satisfies Record<
  RegistryFamily["normalizeForWireFunction"],
  unknown
>;

/** Compile-time guard — every PAS §4.1 registry family exposes a wire normalizer. */
export type assertPlatformIdBoundaryRegistryCoverage =
  keyof typeof PLATFORM_ID_BOUNDARY_WIRE_NORMALIZERS extends RegistryFamily["normalizeForWireFunction"]
    ? RegistryFamily["normalizeForWireFunction"] extends keyof typeof PLATFORM_ID_BOUNDARY_WIRE_NORMALIZERS
      ? true
      : never
    : never;
