import { describe, expect, it } from "vitest";
import {
  extractMdxFrontmatterTitle,
  isGeneratedDocsMdx,
  mdxBodyDuplicatesFrontmatterTitle,
} from "@/lib/docs-writing-conventions";

describe("docs-writing-conventions", () => {
  it("detects duplicate frontmatter title headings", () => {
    const source = `---
title: Sign in
description: Summary
---

# Sign in

## Steps
`;

    expect(mdxBodyDuplicatesFrontmatterTitle(source)).toBe(true);
  });

  it("ignores generated MDX stubs", () => {
    const source = `---
title: Inventory
---

{/* DO NOT EDIT — generated by sync:product-docs */}

# Inventory
`;

    expect(isGeneratedDocsMdx(source)).toBe(true);
    expect(mdxBodyDuplicatesFrontmatterTitle(source)).toBe(false);
  });

  it("allows body starting at h2", () => {
    const source = `---
title: Sign in
description: Summary
---

## Overview

Body
`;

    expect(mdxBodyDuplicatesFrontmatterTitle(source)).toBe(false);
    expect(extractMdxFrontmatterTitle(source)).toBe("Sign in");
  });
});
