/**
 * CSS Authority PAS family path constants — composed SSOT + slice archive.
 */

export const CSS_AUTHORITY_PAS_COMPOSED =
  "docs/PAS/CSS-AUTHORITY/PAS-005-CSS-AUTHORITY-STANDARD.md" as const;

export const CSS_AUTHORITY_PAS_PRESENTATION_COMPOSED =
  "docs/PAS/CSS-AUTHORITY/PAS-005A-SHADCN-STUDIO-PRESENTATION-STANDARD.md" as const;

export const CSS_AUTHORITY_PAS_RETIREMENT_COMPOSED =
  "docs/PAS/CSS-AUTHORITY/PAS-005B-DESIGN-SYSTEM-RETIREMENT-STANDARD.md" as const;

export const CSS_AUTHORITY_SLICE_DIR = "docs/PAS/CSS-AUTHORITY/SLICE" as const;

export const CSS_AUTHORITY_FAMILY_README =
  "docs/PAS/CSS-AUTHORITY/README.md" as const;
