/**
 * Enterprise Knowledge PAS family path constants.
 */

export const EK_PAS_CHARTER =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/PAS-004-ENTERPRISE-KNOWLEDGE-STANDARD.md" as const;

export const EK_PAS_PLATFORM =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/PAS-004A-ENTERPRISE-KNOWLEDGE-PLATFORM-STANDARD.md" as const;

export const EK_PAS_KERNEL_CONSUMER =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/PAS-004B-ENTERPRISE-KNOWLEDGE-KERNEL-CONSUMER-STANDARD.md" as const;

export const EK_PAS_SEMANTIC_MODEL =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/PAS-004C-ENTERPRISE-KNOWLEDGE-SEMANTIC-MODEL-STANDARD.md" as const;

export const EK_PAS_OPERATIONAL_CLOSURE =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/PAS-004D-ENTERPRISE-KNOWLEDGE-OPERATIONAL-CLOSURE-STANDARD.md" as const;

export const EK_SLICE_DIR = "docs/PAS/ENTERPRISE-KNOWLEDGE/SLICE" as const;

export const EK_PAS_FAMILY_README =
  "docs/PAS/ENTERPRISE-KNOWLEDGE/README.md" as const;
