/**
 * Canonical FDR catalog — must match docs/delivery/fdr-status-index.md §FDR register (33 rows).
 * Used by scaffold-fdr-docs.mts and future drift validation.
 */

export type FdrCatalogStatus =
  | "Not started"
  | "Partially Implemented"
  | "Complete"
  | "Complete (authority only)"
  | "Maintain Only";

export interface FdrCatalogEntry {
  readonly archiveRuntimeHint: string;
  readonly cleanCore: "A" | "B" | "C" | "D";
  readonly domain: string;
  readonly evidence: readonly string[];
  readonly fdrId: string;
  readonly gaps: readonly { id: string; description: string; blocks: string }[];
  readonly gates: readonly string[];
  readonly lane: string;
  readonly legacyTips: readonly string[];
  readonly oracleControl: string;
  readonly packageName: string;
  readonly pkg: string;
  readonly primaryGate: string;
  readonly purpose: string;
  readonly registryEntry: string;
  readonly riskClass: "Low" | "Medium" | "High";
  readonly runtimeOwner: string;
  readonly sapControl: string;
  readonly scopeIn: readonly string[];
  readonly scopeOut: readonly string[];
  readonly slug: string;
  readonly title: string;
}

export const FDR_SCAFFOLD_DELIVERY_STATUS =
  "Not started" as const satisfies FdrCatalogStatus;

export const FDR_CATALOG_TOTAL = 33 as const;

export const fdrCatalogEntries = [
  {
    fdrId: "fdr-001-shell-composition",
    slug: "shell-composition",
    title: "Shell Composition",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-001",
    packageName: "@afenda/appshell",
    registryEntry: "PKG001_APPSHELL",
    lane: "amber-lane",
    domain: "shell-composition",
    runtimeOwner: "packages/appshell",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "Document and maintain ERP shell composition authority — contracts, layout wiring, and governed consumption of @afenda/ui.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-006-appshell-authority.md",
      "docs/delivery/tips/[Complete] tip-ui-05-erp-app-surfaces.md",
    ],
    evidence: [
      "packages/appshell/src/contracts/index.ts",
      "packages/appshell/src/index.ts",
    ],
    gates: [
      "pnpm --filter @afenda/appshell typecheck",
      "pnpm --filter @afenda/appshell check:governance",
    ],
    scopeIn: ["Shell contracts", "ERP protected layout wiring"],
    scopeOut: ["Accounting modules", "UI primitive authoring"],
    gaps: [
      {
        id: "appshell-studio-normalization",
        description: "Optional shadcn/studio block normalization backlog",
        blocks: "Amber lane promotion to green",
      },
    ],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm --filter @afenda/appshell check:governance",
  },
  {
    fdrId: "fdr-001-manifest-nav",
    slug: "manifest-nav",
    title: "Manifest Navigation",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-001",
    packageName: "@afenda/appshell",
    registryEntry: "PKG001_APPSHELL",
    lane: "amber-lane",
    domain: "manifest-nav",
    runtimeOwner: "packages/appshell",
    cleanCore: "B",
    riskClass: "Low",
    purpose:
      "Lock navigation projection from entitlements feature manifest — maintain only after TIP-007A delivery.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-007a-feature-manifest-governance.md",
    ],
    evidence: ["packages/entitlements/", "packages/appshell/"],
    gates: ["pnpm --filter @afenda/appshell typecheck"],
    scopeIn: ["Nav builder from manifest + permissions"],
    scopeOut: ["New module routes without entitlements registry update"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm check:documentation-drift",
  },
  {
    fdrId: "fdr-002-auth-disposition",
    slug: "auth-disposition",
    title: "Auth Disposition",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Not started)",
    pkg: "PKG-002",
    packageName: "@afenda/auth",
    registryEntry: "_(pending PKG002_AUTH)_",
    lane: "_(planned amber-lane)_",
    domain: "auth",
    runtimeOwner: "packages/auth",
    cleanCore: "B",
    riskClass: "High",
    purpose:
      "Research-first onboarding for @afenda/auth — session to operating-context bridge before registry promotion.",
    legacyTips: [],
    evidence: ["packages/auth/", "apps/erp/src/app/api/auth/"],
    gates: ["pnpm check:documentation-drift"],
    scopeIn: ["Better Auth audit", "Session→context bridge design"],
    scopeOut: ["Accounting identity", "Auth provider swap without ADR"],
    gaps: [
      {
        id: "auth-session-context-bridge",
        description: "Session→operating-context incomplete on all surfaces",
        blocks: "PKG002_AUTH registry onboarding",
      },
    ],
    sapControl: "Authorization Objects",
    oracleControl: "Identity Governance",
    primaryGate: "pnpm check:multi-tenancy-context-integration",
  },
  {
    fdrId: "fdr-003-persistence",
    slug: "persistence",
    title: "Persistence Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-003",
    packageName: "@afenda/database",
    registryEntry: "PKG003_DATABASE",
    lane: "green-lane",
    domain: "persistence",
    runtimeOwner: "packages/database",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Maintain Drizzle schema authority, migrations, and seeds — no hand-edited migrations.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-011-execution-foundation.md",
    ],
    evidence: [
      "packages/database/src/schema/index.ts",
      "packages/database/drizzle",
    ],
    gates: [
      "pnpm --filter @afenda/database typecheck",
      "pnpm quality:migrations",
      "pnpm check:database-tenant-rls-coverage",
    ],
    scopeIn: ["Schema barrels", "Migration pipeline"],
    scopeOut: ["Accounting tables without ADR"],
    gaps: [],
    sapControl: "CTS / no DDL",
    oracleControl: "Change management",
    primaryGate: "pnpm quality:migrations",
  },
  {
    fdrId: "fdr-003-tenant-rls",
    slug: "tenant-rls",
    title: "Tenant RLS",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-003",
    packageName: "@afenda/database",
    registryEntry: "PKG003_DATABASE",
    lane: "green-lane",
    domain: "tenant-rls",
    runtimeOwner: "packages/database",
    cleanCore: "A",
    riskClass: "Medium",
    purpose:
      "Document tenant RLS registry, artifact coverage, and live apply gates delivered under TIP-007/012.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-007-012-enterprise-group-operating-context.md",
    ],
    evidence: [
      "scripts/governance/check-database-tenant-rls-coverage.mts",
      "packages/database/src/schema/",
    ],
    gates: [
      "pnpm check:database-tenant-rls-coverage",
      "pnpm check:database-tenant-rls-live",
    ],
    scopeIn: ["RLS registry", "Schema parity gates"],
    scopeOut: ["Accounting RLS without ADR"],
    gaps: [],
    sapControl: "HANA RLS",
    oracleControl: "Data Security",
    primaryGate: "pnpm check:database-tenant-rls-coverage",
  },
  {
    fdrId: "fdr-004-design-authority",
    slug: "design-authority",
    title: "Design Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete (authority only))",
    pkg: "PKG-004",
    packageName: "@afenda/design-system",
    registryEntry: "—",
    lane: "—",
    domain: "design-authority",
    runtimeOwner: "packages/design-system",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Authority-only design tokens and recipes — no runtime UI components in design-system by design.",
    legacyTips: [
      "docs/delivery/tips/[Complete (authority only)] tip-003-design-system-authority.md",
      "docs/delivery/tips/[Complete (authority only)] tip-004-design-system-contracts.md",
    ],
    evidence: ["packages/design-system/"],
    gates: ["pnpm --filter @afenda/design-system typecheck"],
    scopeIn: ["Token registry", "Recipe contracts"],
    scopeOut: ["React components in design-system"],
    gaps: [],
    sapControl: "Fiori theme",
    oracleControl: "Fusion theme",
    primaryGate: "pnpm --filter @afenda/design-system typecheck",
  },
  {
    fdrId: "fdr-005-docs-app",
    slug: "docs-app",
    title: "Docs Application",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-005",
    packageName: "@afenda/docs",
    registryEntry: "—",
    lane: "—",
    domain: "docs-app",
    runtimeOwner: "apps/docs",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Fumadocs delivery surface — reference blocks, CI gate, deploy config.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-032-implementation-documentation.md",
    ],
    evidence: ["apps/docs/", "pnpm quality:docs"],
    gates: ["pnpm quality:docs"],
    scopeIn: ["MDX content", "Deploy config"],
    scopeOut: ["ERP runtime coupling"],
    gaps: [
      {
        id: "docs-live-dns",
        description: "Live DNS for docs.afenda.app — operator step",
        blocks: "Production docs URL only",
      },
    ],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm quality:docs",
  },
  {
    fdrId: "fdr-006-entitlements",
    slug: "entitlements",
    title: "Entitlements Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Not started)",
    pkg: "PKG-006",
    packageName: "@afenda/entitlements",
    registryEntry: "PKG006_ENTITLEMENTS",
    lane: "green-lane",
    domain: "entitlements",
    runtimeOwner: "packages/entitlements",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "Research and registry onboarding for entitlements evaluation authority beyond feature manifest.",
    legacyTips: [],
    evidence: ["packages/entitlements/"],
    gates: ["pnpm --filter @afenda/entitlements typecheck"],
    scopeIn: ["Entitlement evaluation contracts"],
    scopeOut: ["Accounting entitlement rules"],
    gaps: [],
    sapControl: "Authorization objects",
    oracleControl: "RBAC policies",
    primaryGate: "pnpm --filter @afenda/entitlements typecheck",
  },
  {
    fdrId: "fdr-006-feature-manifest",
    slug: "feature-manifest",
    title: "Feature Manifest",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-006",
    packageName: "@afenda/entitlements",
    registryEntry: "PKG006_FEATURE_MANIFEST",
    lane: "green-lane",
    domain: "feature-manifest",
    runtimeOwner: "packages/entitlements",
    cleanCore: "B",
    riskClass: "Low",
    purpose:
      "Maintain module/capability manifest registry delivered via TIP-007A.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-007a-feature-manifest-governance.md",
    ],
    evidence: [
      "packages/entitlements/",
      "apps/erp/src/lib/modules/generate-module-routes.ts",
    ],
    gates: ["pnpm --filter @afenda/entitlements typecheck"],
    scopeIn: ["Manifest registry", "Capability bindings"],
    scopeOut: ["New modules without manifest entry"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm check:documentation-drift",
  },
  {
    fdrId: "fdr-007-system-admin",
    slug: "system-admin",
    title: "System Admin Control Plane",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-007",
    packageName: "@afenda/erp",
    registryEntry: "PKG007_ADMIN",
    lane: "green-lane",
    domain: "system-admin",
    runtimeOwner: "apps/erp",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "System Admin layout, pages, governed API contracts, mutation audit coverage.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-013-system-admin-control-plane.md",
    ],
    evidence: [
      "apps/erp/src/app/(protected)/system-admin/",
      "apps/erp/src/lib/system-admin/system-admin-mutation-audit.registry.ts",
    ],
    gates: [
      "pnpm check:system-admin-mutation-audit",
      "pnpm --filter @afenda/erp test:run",
    ],
    scopeIn: ["Admin routes", "Governed admin mutations"],
    scopeOut: ["Accounting admin without ADR"],
    gaps: [
      {
        id: "system-admin-audit-pagination",
        description: "Audit list pagination enhancement",
        blocks: "None — maintain backlog",
      },
    ],
    sapControl: "Auth objects + audit",
    oracleControl: "Advanced Controls",
    primaryGate: "pnpm check:system-admin-mutation-audit",
  },
  {
    fdrId: "fdr-007-operating-context",
    slug: "operating-context",
    title: "Operating Context",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-007",
    packageName: "@afenda/erp",
    registryEntry: "PKG007_CONTEXT",
    lane: "green-lane",
    domain: "operating-context",
    runtimeOwner: "apps/erp",
    cleanCore: "B",
    riskClass: "High",
    purpose:
      "ERP operating context resolver pipeline — tenant, company, org scope.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-012-erp-operating-spine.md",
      "docs/delivery/tips/[Complete] tip-007-012-enterprise-group-operating-context.md",
    ],
    evidence: [
      "apps/erp/src/lib/context/resolve-operating-context.server.ts",
      "apps/erp/src/__tests__/operating-context-integration.test.ts",
    ],
    gates: [
      "pnpm check:multi-tenancy-context-integration",
      "pnpm quality:erp-context-surface",
    ],
    scopeIn: ["Context resolver", "Server action context binding"],
    scopeOut: ["Session-only tenant trust"],
    gaps: [],
    sapControl: "HANA RLS",
    oracleControl: "Data Security",
    primaryGate: "pnpm check:multi-tenancy-context-integration",
  },
  {
    fdrId: "fdr-007-api-governance",
    slug: "api-governance",
    title: "API Contract Governance",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-007",
    packageName: "@afenda/erp",
    registryEntry: "PKG007_CONTEXT",
    lane: "green-lane",
    domain: "api-governance",
    runtimeOwner: "apps/erp",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "Internal v1 API envelope, method policy, idempotency, pagination contracts.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-010a-api-contract-governance.md",
    ],
    evidence: ["apps/erp/src/server/api/contracts/", "scripts/api-contract/"],
    gates: ["pnpm check:api-contracts"],
    scopeIn: ["Contract registry", "Route coverage"],
    scopeOut: ["Durable idempotency store (deferred)"],
    gaps: [
      {
        id: "api-idempotency-store",
        description: "Durable idempotency store deferred",
        blocks: "None — documented deferral",
      },
    ],
    sapControl: "API governance",
    oracleControl: "Integration governance",
    primaryGate: "pnpm check:api-contracts",
  },
  {
    fdrId: "fdr-007-ux-surfaces",
    slug: "ux-surfaces",
    title: "ERP UX Surfaces",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-007",
    packageName: "@afenda/erp",
    registryEntry: "—",
    lane: "—",
    domain: "ux-surfaces",
    runtimeOwner: "apps/erp",
    cleanCore: "B",
    riskClass: "Low",
    purpose:
      "Governed ERP app surfaces — loading/error boundaries, admin UX, metadata pages.",
    legacyTips: ["docs/delivery/tips/[Complete] tip-ui-05-erp-app-surfaces.md"],
    evidence: ["apps/erp/src/app/(protected)/"],
    gates: ["pnpm --filter @afenda/erp test:run", "pnpm ui:guard:scan"],
    scopeIn: ["Protected routes UX", "Governed components"],
    scopeOut: ["Design-system primitive edits"],
    gaps: [],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm --filter @afenda/erp test:run",
  },
  {
    fdrId: "fdr-007-accounting-readiness",
    slug: "accounting-readiness",
    title: "Accounting Readiness Gate",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-007",
    packageName: "@afenda/erp",
    registryEntry: "—",
    lane: "green-lane",
    domain: "accounting-readiness",
    runtimeOwner: "apps/erp",
    cleanCore: "A",
    riskClass: "High",
    purpose:
      "Phase 9 accounting readiness orchestrator, diagnostics UI, sign-off record.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-013a-accounting-readiness-gate.md",
    ],
    evidence: [
      "scripts/governance/check-accounting-readiness-gate.mts",
      "docs/architecture/phase-9-accounting-readiness-sign-off.md",
    ],
    gates: ["pnpm check:accounting-readiness-gate"],
    scopeIn: ["Readiness gate orchestrator", "Diagnostics UI"],
    scopeOut: ["Ledger/posting runtime"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm check:accounting-readiness-gate",
  },
  {
    fdrId: "fdr-008-outbox-jobs",
    slug: "outbox-jobs",
    title: "Outbox Jobs",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-008",
    packageName: "@afenda/execution",
    registryEntry: "PKG008_EXECUTION",
    lane: "green-lane",
    domain: "outbox-jobs",
    runtimeOwner: "packages/execution",
    cleanCore: "A",
    riskClass: "Medium",
    purpose: "Durable outbox publish worker and Trigger.dev integration.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-011-execution-foundation.md",
    ],
    evidence: [
      "packages/execution/src/index.ts",
      "packages/database/src/schema/outbox.schema.ts",
    ],
    gates: [
      "pnpm --filter @afenda/execution typecheck",
      "pnpm --filter @afenda/execution test:run",
    ],
    scopeIn: ["Outbox worker", "Trigger.dev task"],
    scopeOut: ["Bypass outbox for mutations"],
    gaps: [],
    sapControl: "AIF / RFC",
    oracleControl: "Oracle AQ",
    primaryGate: "pnpm --filter @afenda/execution test:run",
  },
  {
    fdrId: "fdr-009-rollout-flags",
    slug: "rollout-flags",
    title: "Rollout Flags",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-009",
    packageName: "@afenda/feature-flags",
    registryEntry: "PKG009_FEATURE_FLAGS",
    lane: "blue-lane",
    domain: "rollout-flags",
    runtimeOwner: "packages/feature-flags",
    cleanCore: "B",
    riskClass: "Low",
    purpose:
      "Deployment flags package and ERP integration map — blue-lane incubation.",
    legacyTips: [],
    evidence: ["packages/feature-flags/src/index.ts"],
    gates: ["pnpm --filter @afenda/feature-flags typecheck"],
    scopeIn: ["Flag contracts", "ERP evaluation surfaces"],
    scopeOut: ["Gate-critical path dependency on flags"],
    gaps: [
      {
        id: "feature-flags-erp-wiring",
        description: "ERP integration incomplete",
        blocks: "Blue→green promotion",
      },
    ],
    sapControl: "Transport variants",
    oracleControl: "Oracle Profiles",
    primaryGate: "pnpm --filter @afenda/feature-flags typecheck",
  },
  {
    fdrId: "fdr-010-context-contracts",
    slug: "context-contracts",
    title: "Context Contracts",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-010",
    packageName: "@afenda/kernel",
    registryEntry: "PKG010_KERNEL",
    lane: "green-lane",
    domain: "operating-context-contracts",
    runtimeOwner: "packages/kernel",
    cleanCore: "A",
    riskClass: "Medium",
    purpose:
      "Kernel operating-context contract barrel — no resolver implementation in kernel.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-007-erp-platform-authority.md",
    ],
    evidence: [
      "packages/kernel/src/context/index.ts",
      "packages/kernel/src/index.ts",
    ],
    gates: [
      "pnpm --filter @afenda/kernel typecheck",
      "pnpm quality:kernel-context-surface",
    ],
    scopeIn: ["Context contracts", "Public barrel exports"],
    scopeOut: ["Resolver implementation in kernel"],
    gaps: [],
    sapControl: "Platform namespace",
    oracleControl: "Integration contracts",
    primaryGate: "pnpm quality:kernel-context-surface",
  },
  {
    fdrId: "fdr-010-platform-authority",
    slug: "platform-authority",
    title: "Platform Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-010",
    packageName: "@afenda/kernel",
    registryEntry: "PKG010_KERNEL",
    lane: "green-lane",
    domain: "platform-authority",
    runtimeOwner: "packages/kernel",
    cleanCore: "A",
    riskClass: "Low",
    purpose: "Platform entity authority registry frozen under TIP-007 Slice 1.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-007-erp-platform-authority.md",
    ],
    evidence: ["packages/kernel/src/contracts/platform/"],
    gates: ["pnpm --filter @afenda/kernel typecheck"],
    scopeIn: ["Platform entity authority contracts"],
    scopeOut: ["Domain package schemas"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm --filter @afenda/kernel typecheck",
  },
  {
    fdrId: "fdr-010-master-data-authority",
    slug: "master-data-authority",
    title: "Master Data Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete (authority only))",
    pkg: "PKG-010",
    packageName: "@afenda/kernel",
    registryEntry: "PKG010_KERNEL",
    lane: "green-lane",
    domain: "master-data-authority",
    runtimeOwner: "packages/kernel",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Business master data wire reference contracts (TIP-008B) — authority only.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-008-master-data-authority.md",
    ],
    evidence: ["packages/kernel/src/contracts/business-master-data/"],
    gates: ["pnpm --filter @afenda/kernel typecheck"],
    scopeIn: ["Authority map", "Wire reference contracts"],
    scopeOut: ["PKG-R02–R05 domain schemas"],
    gaps: [],
    sapControl: "MDG",
    oracleControl: "Product Hub",
    primaryGate: "pnpm --filter @afenda/kernel typecheck",
  },
  {
    fdrId: "fdr-011-metadata-authority",
    slug: "metadata-authority",
    title: "Metadata Authority",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete (authority only))",
    pkg: "PKG-011",
    packageName: "@afenda/metadata",
    registryEntry: "—",
    lane: "—",
    domain: "metadata-authority",
    runtimeOwner: "packages/metadata",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Metadata architecture contracts — no renderers in metadata package.",
    legacyTips: [
      "docs/delivery/tips/[Complete (authority only)] tip-005-metadata-authority.md",
    ],
    evidence: ["packages/metadata/"],
    gates: ["pnpm --filter @afenda/metadata typecheck"],
    scopeIn: ["Metadata contracts", "Validation tests"],
    scopeOut: ["UI renderers"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm --filter @afenda/metadata typecheck",
  },
  {
    fdrId: "fdr-012-metadata-renderers",
    slug: "metadata-renderers",
    title: "Metadata Renderers",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-012",
    packageName: "@afenda/metadata-ui",
    registryEntry: "—",
    lane: "—",
    domain: "metadata-renderers",
    runtimeOwner: "packages/metadata-ui",
    cleanCore: "B",
    riskClass: "Low",
    purpose: "Metadata-driven renderers and ERP production route wiring.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-ui-04-metadata-ui-renderers.md",
    ],
    evidence: [
      "packages/metadata-ui/",
      "apps/erp/src/app/(protected)/metadata-workspace/",
    ],
    gates: ["pnpm --filter @afenda/metadata-ui typecheck"],
    scopeIn: ["Renderers", "Production page wiring"],
    scopeOut: ["Metadata authority contracts"],
    gaps: [],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm --filter @afenda/metadata-ui typecheck",
  },
  {
    fdrId: "fdr-013-audit-coverage",
    slug: "audit-coverage",
    title: "Audit Coverage",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-013",
    packageName: "@afenda/observability",
    registryEntry: "PKG013_AUDIT",
    lane: "green-lane",
    domain: "audit-coverage",
    runtimeOwner: "packages/observability",
    cleanCore: "A",
    riskClass: "High",
    purpose:
      "Governed mutation audit registry and enforcement — close mutation coverage gaps.",
    legacyTips: [
      "docs/delivery/tips/[Superseded] tip-010-observability-audit.md",
    ],
    evidence: [
      "packages/observability/src/surface/governed-mutation-audit-registry.ts",
    ],
    gates: [
      "pnpm --filter @afenda/observability test:run",
      "pnpm quality:erp-observability",
    ],
    scopeIn: ["Audit registry", "Governed mutation enforcement"],
    scopeOut: ["Mock audit in production paths"],
    gaps: [
      {
        id: "audit-mutation-coverage",
        description: "Not all mutations emit audit events",
        blocks: "Full observability closeout",
      },
    ],
    sapControl: "SOLMAN diagnostics",
    oracleControl: "Advanced Controls",
    primaryGate: "pnpm quality:erp-observability",
  },
  {
    fdrId: "fdr-013-logging-tracing",
    slug: "logging-tracing",
    title: "Logging and Tracing",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-013",
    packageName: "@afenda/observability",
    registryEntry: "_(pending PKG013_LOGGING)_",
    lane: "green-lane",
    domain: "logging-tracing",
    runtimeOwner: "packages/observability",
    cleanCore: "A",
    riskClass: "Medium",
    purpose: "Pino logging, correlation IDs, ERP spine lifecycle evidence.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-012-erp-operating-spine.md",
      "docs/delivery/support/pino-erp-logger.md",
    ],
    evidence: [
      "packages/observability/",
      "docs/delivery/support/pino-erp-logger.md",
    ],
    gates: ["pnpm quality:erp-observability"],
    scopeIn: ["Structured logging", "Correlation ID pipeline"],
    scopeOut: ["Third-party APM without CSP approval"],
    gaps: [
      {
        id: "logging-spine-coverage",
        description: "Spine lifecycle proof not on all routes",
        blocks: "Logging FDR complete status",
      },
    ],
    sapControl: "SOLMAN",
    oracleControl: "Enterprise Manager",
    primaryGate: "pnpm quality:erp-observability",
  },
  {
    fdrId: "fdr-014-rbac",
    slug: "rbac",
    title: "RBAC",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-014",
    packageName: "@afenda/permissions",
    registryEntry: "PKG014_PERMISSIONS",
    lane: "green-lane",
    domain: "rbac",
    runtimeOwner: "packages/permissions",
    cleanCore: "A",
    riskClass: "High",
    purpose: "Permission registry, policy evaluation, scope/grants surface.",
    legacyTips: ["docs/delivery/tips/[Complete] tip-010-api-rbac-wiring.md"],
    evidence: ["packages/permissions/src/registry/permission-registry.ts"],
    gates: [
      "pnpm quality:permissions-scope-grants-surface",
      "pnpm check:api-contracts",
    ],
    scopeIn: ["PERMISSION_REGISTRY", "Policy evaluation"],
    scopeOut: ["Local permission constants in consumers"],
    gaps: [],
    sapControl: "Authorization objects",
    oracleControl: "RBAC policies",
    primaryGate: "pnpm check:api-contracts",
  },
  {
    fdrId: "fdr-015-tenant-storage",
    slug: "tenant-storage",
    title: "Tenant Storage",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-015",
    packageName: "@afenda/storage",
    registryEntry: "PKG015_STORAGE",
    lane: "green-lane",
    domain: "tenant-storage",
    runtimeOwner: "packages/storage",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "Tenant-scoped storage abstraction — contracts, R2/Blob providers, tenant denial tests (Slice 2 complete).",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-011-execution-foundation.md",
    ],
    evidence: [
      "packages/storage/src/index.ts",
      "packages/storage/src/contracts/storage.contract.ts",
      "packages/storage/src/services/storage.service.ts",
      "packages/storage/src/providers/r2.provider.ts",
      "packages/storage/src/providers/blob.provider.ts",
      "packages/storage/src/__tests__/storage.service.test.ts",
      "packages/storage/src/__tests__/provider-adapters.test.ts",
      "packages/storage/src/__tests__/tenant-denial.test.ts",
    ],
    gates: [
      "pnpm --filter @afenda/storage typecheck",
      "pnpm --filter @afenda/storage test:run",
      "pnpm quality:boundaries",
      "pnpm check:database-tenant-rls-coverage",
    ],
    scopeIn: [
      "Storage contracts",
      "Tenant scoping audit",
      "Cross-tenant denial tests",
    ],
    scopeOut: ["Accounting document storage without ADR"],
    gaps: [
      {
        id: "storage-database-bridge",
        description:
          "No repository layer linking storage_objects Drizzle rows to StorageService",
        blocks: "Metadata persistence integration",
      },
      {
        id: "storage-erp-consumer",
        description: "No ERP server action or route uses @afenda/storage",
        blocks: "Production consumer wiring",
      },
      {
        id: "storage-audit-coverage",
        description:
          "create/delete object mutations not in governed mutation audit registry",
        blocks: "Observability closeout",
      },
      {
        id: "storage-rls-live-proof",
        description:
          "RLS policy registered in contract; live apply not proven under storage FDR gates",
        blocks: "Full RLS attestation",
      },
    ],
    sapControl: "Storage partitioning",
    oracleControl: "Storage namespace",
    primaryGate: "pnpm check:database-tenant-rls-coverage",
  },
  {
    fdrId: "fdr-016-test-utilities",
    slug: "test-utilities",
    title: "Test Utilities",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-016",
    packageName: "@afenda/testing",
    registryEntry: "—",
    lane: "—",
    domain: "test-utilities",
    runtimeOwner: "packages/testing",
    cleanCore: "A",
    riskClass: "Low",
    purpose: "Shared test utilities, react setup, interaction patterns.",
    legacyTips: [],
    evidence: ["packages/testing/", "vitest.shared.ts"],
    gates: ["pnpm test:interaction"],
    scopeIn: ["Test helpers", "Vitest project wiring"],
    scopeOut: ["Production runtime imports"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm check:documentation-drift",
  },
  {
    fdrId: "fdr-017-ts-config",
    slug: "ts-config",
    title: "TypeScript Config",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-017",
    packageName: "@afenda/typescript-config",
    registryEntry: "—",
    lane: "—",
    domain: "ts-config",
    runtimeOwner: "packages/typescript-config",
    cleanCore: "A",
    riskClass: "Low",
    purpose: "Shared TS compiler presets — active-exempt tooling package.",
    legacyTips: [],
    evidence: ["packages/typescript-config/"],
    gates: ["pnpm typecheck"],
    scopeIn: ["TS config presets"],
    scopeOut: ["Runtime business logic"],
    gaps: [],
    sapControl: "ATC",
    oracleControl: "Quality standards",
    primaryGate: "pnpm typecheck",
  },
  {
    fdrId: "fdr-018-governed-primitives",
    slug: "governed-primitives",
    title: "Governed Primitives",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Partially Implemented)",
    pkg: "PKG-018",
    packageName: "@afenda/ui",
    registryEntry: "PKG018_UI",
    lane: "amber-lane",
    domain: "governed-primitives",
    runtimeOwner: "packages/ui",
    cleanCore: "B",
    riskClass: "Medium",
    purpose:
      "UI primitive governance — ADR-0008 ref-as-prop migration deferred.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-ui-02-component-library.md",
      "docs/delivery/tips/[Blocked] tip-ui-06-react19-ref-as-prop.md",
    ],
    evidence: ["packages/ui/src/governance/resolve-primitive-governance.ts"],
    gates: ["pnpm ui:guard:scan", "pnpm --filter @afenda/ui typecheck"],
    scopeIn: ["Primitive governance", "Component library"],
    scopeOut: ["forwardRef batch before ADR-0008"],
    gaps: [
      {
        id: "ui-adr-0008-ref-as-prop",
        description: "ADR-0008 ref-as-prop batch blocked",
        blocks: "Amber→green promotion",
      },
    ],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm ui:guard:scan",
  },
  {
    fdrId: "fdr-018-ui-consumption",
    slug: "ui-consumption",
    title: "UI Consumption",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-018",
    packageName: "@afenda/ui",
    registryEntry: "PKG018_UI",
    lane: "green-lane",
    domain: "ui-consumption",
    runtimeOwner: "packages/ui",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "TIP-004 consumer rules — zero className on @afenda/ui primitives in consumers.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-004-ui-consumption.md",
      "docs/governance/tip-004-policy.md",
    ],
    evidence: [
      "scripts/governance/ui-guard.mjs",
      "docs/governance/tip-004-policy.md",
    ],
    gates: ["pnpm ui:guard:scan"],
    scopeIn: ["Consumption gates D/F", "Governance policy"],
    scopeOut: ["Primitive authoring in consumers"],
    gaps: [],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm ui:guard:scan",
  },
  {
    fdrId: "fdr-019-architecture-maps",
    slug: "architecture-maps",
    title: "Architecture Maps",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-019",
    packageName: "@afenda/architecture-authority",
    registryEntry: "—",
    lane: "—",
    domain: "architecture-maps",
    runtimeOwner: "packages/architecture-authority",
    cleanCore: "A",
    riskClass: "Low",
    purpose:
      "Architecture validators, registries, foundation disposition enforcement.",
    legacyTips: [
      "docs/delivery/tips/[Complete] tip-001-architecture-authority.md",
    ],
    evidence: ["packages/architecture-authority/", "pnpm quality:architecture"],
    gates: ["pnpm check:foundation-disposition", "pnpm quality:architecture"],
    scopeIn: ["Validators", "Registry data"],
    scopeOut: ["Business domain logic"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "CEMLI",
    primaryGate: "pnpm check:foundation-disposition",
  },
  {
    fdrId: "fdr-020-ai-governance",
    slug: "ai-governance",
    title: "AI Governance",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete)",
    pkg: "PKG-020",
    packageName: "@afenda/ai-governance",
    registryEntry: "—",
    lane: "—",
    domain: "ai-governance",
    runtimeOwner: "packages/ai-governance",
    cleanCore: "A",
    riskClass: "Low",
    purpose: "AI-assisted development governance validators (ADR-0007).",
    legacyTips: [],
    evidence: ["packages/ai-governance/", "pnpm quality:ai-governance"],
    gates: ["pnpm quality:ai-governance"],
    scopeIn: ["Governance validators", "Change boundaries"],
    scopeOut: ["Runtime AI inference in ERP"],
    gaps: [],
    sapControl: "SOLMAN",
    oracleControl: "FDD",
    primaryGate: "pnpm quality:ai-governance",
  },
  {
    fdrId: "fdr-021-storybook",
    slug: "storybook",
    title: "Storybook",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Maintain Only)",
    pkg: "PKG-021",
    packageName: "@afenda/storybook",
    registryEntry: "—",
    lane: "—",
    domain: "storybook",
    runtimeOwner: "apps/storybook",
    cleanCore: "A",
    riskClass: "Low",
    purpose: "Visual gate delivery surface for UI, appshell, metadata-ui.",
    legacyTips: [],
    evidence: ["apps/storybook/"],
    gates: ["pnpm --filter @afenda/storybook test:run"],
    scopeIn: ["Stories", "Test runner"],
    scopeOut: ["Production ERP routes"],
    gaps: [],
    sapControl: "Fiori UX",
    oracleControl: "Fusion UX",
    primaryGate: "pnpm check:documentation-drift",
  },
  {
    fdrId: "fdr-r01-accounting-contracts",
    slug: "accounting-contracts",
    title: "Accounting Contracts",
    archiveRuntimeHint:
      "TIP/runtime archive — verify in Research Slice 1 (historical label: Complete (authority only))",
    pkg: "PKG-R01",
    packageName: "@afenda/accounting",
    registryEntry: "PKGR01_ACCOUNTING",
    lane: "green-lane",
    domain: "accounting-contracts",
    runtimeOwner: "packages/accounting",
    cleanCore: "A",
    riskClass: "High",
    purpose:
      "Contracts-only accounting authority (ADR-0015) — no ledger/posting runtime.",
    legacyTips: [
      "docs/delivery/tips/[Complete (authority only)] tip-014-accounting-core-contracts.md",
    ],
    evidence: [
      "packages/accounting/src/contracts/accounting-authority.contract.ts",
      "pnpm check:accounting-domain-contracts",
    ],
    gates: [
      "pnpm check:accounting-domain-contracts",
      "pnpm --filter @afenda/accounting test:run",
    ],
    scopeIn: [
      "Domain vocabulary",
      "Kernel bridge",
      "Audit/permission vocabulary",
    ],
    scopeOut: ["Drizzle COA/journal without TIP-015+ ADR"],
    gaps: [
      {
        id: "accounting-ledger-runtime",
        description: "COA schemas + posting runtime blocked until new ADR",
        blocks: "TIP-015+ runtime",
      },
    ],
    sapControl: "FI config (design)",
    oracleControl: "Financials setup",
    primaryGate: "pnpm check:accounting-domain-contracts",
  },
] as const satisfies readonly FdrCatalogEntry[];
