/** ERP-PROC-OP-001 — operational scaffold stub (no business runtime). */
export const PROCUREMENT_OPERATIONAL_SLICE_ID = "ERP-PROC-OP-001" as const;

export const PROCUREMENT_OPERATIONAL_STATUS = "scaffold_only" as const;

export const PROCUREMENT_OPERATIONAL_SCAFFOLD = {
  sliceId: PROCUREMENT_OPERATIONAL_SLICE_ID,
  status: PROCUREMENT_OPERATIONAL_STATUS,
  authorizedAt: "2026-06-30",
  runtimePath: "packages/features/erp-modules/src/procurement/",
} as const;

/** ERP-PROC-OP-006 — audit/outbox declaration (no writers). */
export {
  PROCUREMENT_AUDIT_OUTBOX_ATTESTATION,
  PROCUREMENT_AUDIT_OUTBOX_CONTRACT,
  PROCUREMENT_AUDIT_OUTBOX_SLICE_ID,
  PROCUREMENT_AUDIT_OUTBOX_STATUS,
  PROCUREMENT_MODULE_PREFIXED_AUDIT_ACTIONS,
  PROCUREMENT_PLANNED_OUTBOX_ENTRIES,
  PROCUREMENT_WIRE_AUDIT_ACTIONS,
} from "./procurement.audit-outbox.contract.js";
/** ERP-PROC-OP-005 — context spine consumer attestation (foundation readiness route). */
export {
  PROCUREMENT_CONTEXT_SPINE_CONSUMER_ATTESTATION,
  PROCUREMENT_CONTEXT_SPINE_CONSUMER_CONTRACT,
  PROCUREMENT_CONTEXT_SPINE_CONSUMER_SLICE_ID,
  PROCUREMENT_CONTEXT_SPINE_CONSUMER_STATUS,
  PROCUREMENT_CONTEXT_SPINE_FORBIDDEN_INGRESS,
  PROCUREMENT_CONTEXT_SPINE_REQUIRED_RESOLVERS,
  PROCUREMENT_FOUNDATION_READINESS_ROUTE,
} from "./procurement.context-spine-consumer.contract.js";
/** ERP-PROC-OP-003 — planned database boundary declaration (no migrations). */
export {
  PROCUREMENT_DATABASE_BOUNDARY_ATTESTATION,
  PROCUREMENT_DATABASE_BOUNDARY_CONTRACT,
  PROCUREMENT_DATABASE_BOUNDARY_SLICE_ID,
  PROCUREMENT_DATABASE_BOUNDARY_STATUS,
} from "./procurement.database-boundary.contract.js";
/** ERP-PROC-OP-002 — ADR-locked runtime ownership contract. */
export {
  PROCUREMENT_OWNERSHIP_ATTESTATION,
  PROCUREMENT_OWNERSHIP_CONTRACT,
  PROCUREMENT_OWNERSHIP_MATRIX,
  PROCUREMENT_OWNERSHIP_SLICE_ID,
  PROCUREMENT_OWNERSHIP_STATUS,
} from "./procurement.ownership.contract.js";
/** ERP-PROC-OP-004 — permission binding declaration (no registry wiring). */
export {
  PROCUREMENT_KERNEL_PERMISSION_KEYS,
  PROCUREMENT_PERMISSION_BINDING_ATTESTATION,
  PROCUREMENT_PERMISSION_BINDING_CONTRACT,
  PROCUREMENT_PERMISSION_BINDING_SLICE_ID,
  PROCUREMENT_PERMISSION_BINDING_STATUS,
} from "./procurement.permission-binding.contract.js";
