import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  patchUseErpIndexMdx,
  renderCasualAdminSectionsMdx,
  renderCasualAuthLanesMdx,
  renderCasualModulePageMdx,
  renderCasualModulesIndexMdx,
} from "../src/lib/docs-casual-feature-pages.ts";
import {
  listDeveloperEvidencePageIds,
  renderDeveloperEvidenceFiles,
  serializeFeatureEvidenceGraph,
} from "../src/lib/docs-developer-evidence-pages.ts";
import { applyFeatureCopyToManifest } from "../src/lib/docs-feature-copy.ts";
import { resolveDocsFeatureCopy } from "../src/lib/i18n/resolve-docs-locale-messages.ts";
import type {
  AuthRoutesCatalog,
  ModulesCatalog,
  PermissionsCatalog,
  SystemAdminCatalog,
} from "../src/lib/docs-product-catalog.contract.ts";
import {
  applyFeatureCoverageHardFail,
  applyFeatureManifestOverrides,
  applyOpenApiBindingHardFail,
  applyPermissionParityHardFail,
  buildDocsFeatureEvidenceGraph,
  buildDocsFeatureManifests,
  computeFeatureCoverageScore,
  validateFeatureCoverage,
  validatePermissionOpenApiParity,
} from "../src/lib/docs-feature-manifest.ts";
import type {
  FeatureCopyOverlay,
  FeatureManifestOverrides,
} from "../src/lib/docs-feature-manifest.contract.ts";
import { bindOpenApiOperationsToManifests } from "../src/lib/docs-openapi-manifest-bindings.ts";
import { mergeFeatureManifestsWithPlatformApi } from "../src/lib/docs-openapi-platform-manifests.ts";
import {
  buildRepoEvidenceGraph,
  discoverErpAppSurfaces,
  resolveDocsRepoRoot,
} from "../src/lib/docs-repo-evidence.ts";
import { type DocsLocale, docsLocales } from "../src/lib/i18n.ts";

const GENERATED_HEADER =
  "{/* DO NOT EDIT — generated by sync:product-docs / generate-feature-evidence */}";

const appDir = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const repoRoot = resolveDocsRepoRoot();
const docsDataDir = join(appDir, "data");

function readJson<T>(fileName: string): T {
  const path = join(docsDataDir, fileName);
  if (!existsSync(path)) {
    throw new Error(`Missing ${path}. Run catalog export first.`);
  }
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function readLocaleFeatureCopy(locale: string): FeatureCopyOverlay | undefined {
  if (!(docsLocales as readonly string[]).includes(locale)) {
    return undefined;
  }

  const featureCopy = resolveDocsFeatureCopy(locale as DocsLocale);
  return Object.keys(featureCopy).length > 0 ? featureCopy : undefined;
}

function readManifestOverrides(): FeatureManifestOverrides | undefined {
  const path = join(docsDataDir, "feature-manifest.overrides.json");
  if (!existsSync(path)) {
    return undefined;
  }

  const payload = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  const entries = Object.fromEntries(
    Object.entries(payload).filter(([key]) => !key.startsWith("_"))
  ) as FeatureManifestOverrides;

  return Object.keys(entries).length > 0 ? entries : undefined;
}

function localeContentRoot(locale: string): string {
  return join(appDir, "content/docs", locale);
}

function writeGeneratedMdx(
  contentRoot: string,
  relativePath: string,
  body: string
): void {
  const filePath = join(contentRoot, relativePath);
  mkdirSync(join(filePath, ".."), { recursive: true });

  const trimmed = body.trim();
  let content: string;

  if (trimmed.startsWith("---")) {
    const end = trimmed.indexOf("---", 3);
    if (end > 0) {
      const frontmatter = trimmed.slice(0, end + 3);
      const remainder = trimmed.slice(end + 3).trimStart();
      content = `${frontmatter}\n\n${GENERATED_HEADER}\n\n${remainder}\n`;
    } else {
      content = `${trimmed}\n`;
    }
  } else {
    content = `---\ntitle: "Generated"\n---\n\n${GENERATED_HEADER}\n\n${trimmed}\n`;
  }

  writeFileSync(filePath, content, "utf8");
  console.log(`[generate-feature-evidence] wrote ${filePath}`);
}

function renderGeneratedIntegrateIndexMdx(): string {
  return `---
title: "Generated reference"
description: "Machine-synced module tables and developer feature evidence from repo contracts."
---

Registry-driven reference pages generated from \`modules.catalog.json\`, \`permissions.catalog.json\`, and feature evidence manifests. Do not edit synced bodies marked \`DO NOT EDIT\`.

<Cards>
  <Card title="ERP modules reference" href="./modules" description="Module routes, permission keys, and entitlement requirements." />
  <Card title="Feature evidence" href="./evidence" description="Developer-facing evidence pages per manifest surface." />
</Cards>
`;
}

function ensureGeneratedIntegrateMeta(contentRoot: string): void {
  const metaPath = join(contentRoot, "integrate/generated/meta.json");
  mkdirSync(join(metaPath, ".."), { recursive: true });
  const existing = existsSync(metaPath)
    ? (JSON.parse(readFileSync(metaPath, "utf8")) as { title?: string; pages?: string[] })
    : { title: "Generated reference", pages: ["index", "modules"] };
  const pages = [...(existing.pages ?? ["index", "modules"])];
  if (!pages.includes("index")) {
    pages.unshift("index");
  }
  if (!pages.includes("evidence")) {
    pages.push("evidence");
  }
  writeFileSync(
    metaPath,
    `${JSON.stringify({ ...existing, pages }, null, 2)}\n`,
    "utf8"
  );
  console.log(`[generate-feature-evidence] updated ${metaPath}`);
}

function ensureMetaPages(
  metaPath: string,
  pages: readonly string[]
): void {
  if (!existsSync(metaPath)) {
    return;
  }

  const meta = JSON.parse(readFileSync(metaPath, "utf8")) as {
    pages?: string[];
  };
  const merged = [...(meta.pages ?? [])];
  let changed = false;

  for (const page of pages) {
    if (!merged.includes(page)) {
      merged.push(page);
      changed = true;
    }
  }

  if (changed) {
    writeFileSync(
      metaPath,
      `${JSON.stringify({ ...meta, pages: merged }, null, 2)}\n`,
      "utf8"
    );
    console.log(`[generate-feature-evidence] updated ${metaPath}`);
  }
}

function ensureModulesMeta(
  contentRoot: string,
  moduleIds: readonly string[]
): void {
  const metaPath = join(contentRoot, "use-erp/modules/meta.json");
  mkdirSync(join(metaPath, ".."), { recursive: true });
  writeFileSync(
    metaPath,
    `${JSON.stringify(
      {
        title: "ERP modules",
        pages: ["index", ...moduleIds],
      },
      null,
      2
    )}\n`,
    "utf8"
  );
  console.log(`[generate-feature-evidence] wrote ${metaPath}`);
}

function ensureEvidenceMeta(
  contentRoot: string,
  pageIds: readonly string[]
): void {
  const metaPath = join(contentRoot, "integrate/generated/evidence/meta.json");
  mkdirSync(join(metaPath, ".."), { recursive: true });
  writeFileSync(
    metaPath,
    `${JSON.stringify(
      {
        title: "Feature evidence",
        pages: pageIds,
      },
      null,
      2
    )}\n`,
    "utf8"
  );
  console.log(`[generate-feature-evidence] wrote ${metaPath}`);
}

function readCatalogCounts(): {
  authRoutes: number;
  permissions: number;
  modules: number;
  envVariables: number;
} {
  function count(fileName: string, keys: string[]): number {
    try {
      const payload = JSON.parse(
        readFileSync(join(docsDataDir, fileName), "utf8")
      ) as Record<string, unknown>;
      for (const key of keys) {
        if (Array.isArray(payload[key])) {
          return payload[key].length;
        }
      }
      return 0;
    } catch {
      return 0;
    }
  }

  return {
    authRoutes: count("auth-routes.catalog.json", ["routes"]),
    permissions: count("permissions.catalog.json", ["permissions"]),
    modules: count("modules.catalog.json", ["modules"]),
    envVariables: count("env.catalog.json", ["variables"]),
  };
}

function main(): void {
  const modules = readJson<ModulesCatalog>("modules.catalog.json");
  const authRoutes = readJson<AuthRoutesCatalog>("auth-routes.catalog.json");
  const systemAdmin = readJson<SystemAdminCatalog>("system-admin.catalog.json");
  const permissions = readJson<PermissionsCatalog>("permissions.catalog.json");
  const baseOverlay = readLocaleFeatureCopy("en");
  const overrides = readManifestOverrides();

  const surfaces = discoverErpAppSurfaces(repoRoot);
  const permissionKeys = permissions.permissions.map((entry) => entry.key);

  const compiled = buildDocsFeatureManifests({
    modules,
    authRoutes,
    systemAdmin,
    overlay: baseOverlay,
  });
  const withOverrides = applyFeatureManifestOverrides(compiled, overrides);
  const withPlatform = mergeFeatureManifestsWithPlatformApi({
    catalogManifests: withOverrides,
    root: repoRoot,
  });
  const openApiBinding = bindOpenApiOperationsToManifests({
    manifests: withPlatform,
    root: repoRoot,
  });

  for (const warning of openApiBinding.warnings) {
    console.warn(`[generate-feature-evidence] openapi: ${warning}`);
  }

  const initialCoverage = validateFeatureCoverage({
    manifests: openApiBinding.manifests,
    surfaces,
    permissionKeys,
  });
  const score = computeFeatureCoverageScore({
    manifests: openApiBinding.manifests,
    surfaces,
    permissionKeys,
    result: initialCoverage,
  });
  const coverage = applyFeatureCoverageHardFail(initialCoverage, score);
  const openApiBindingErrors = applyOpenApiBindingHardFail({
    warnings: openApiBinding.warnings,
    score,
  });
  const permissionParity = validatePermissionOpenApiParity(openApiBinding.manifests);
  const permissionParityErrors = applyPermissionParityHardFail({
    warnings: permissionParity.warnings,
    score,
  });

  for (const warning of permissionParity.warnings) {
    console.warn(`[generate-feature-evidence] permission-parity: ${warning}`);
  }

  if (
    coverage.errors.length > 0 ||
    openApiBindingErrors.length > 0 ||
    permissionParityErrors.length > 0
  ) {
    throw new Error(
      [...coverage.errors, ...openApiBindingErrors, ...permissionParityErrors].join(
        "\n"
      )
    );
  }

  for (const warning of coverage.warnings) {
    console.warn(`[generate-feature-evidence] coverage: ${warning}`);
  }

  const manifests = openApiBinding.manifests;
  const graph = buildDocsFeatureEvidenceGraph({
    manifests,
    coverage,
    score,
    openApiBindingWarnings: openApiBinding.warnings,
    permissionParityWarnings: permissionParity.warnings,
  });
  writeFileSync(
    join(docsDataDir, "feature-evidence.graph.json"),
    serializeFeatureEvidenceGraph(graph),
    "utf8"
  );

  const moduleManifests = manifests.filter((manifest) => manifest.kind === "module");
  const developerFiles = renderDeveloperEvidenceFiles({ manifests, surfaces });
  const evidencePageIds = listDeveloperEvidencePageIds(manifests);

  for (const locale of docsLocales) {
    const contentRoot = localeContentRoot(locale);
    const localeOverlay = readLocaleFeatureCopy(locale);

    writeGeneratedMdx(
      contentRoot,
      "use-erp/modules/index.mdx",
      renderCasualModulesIndexMdx(manifests)
    );
    writeGeneratedMdx(
      contentRoot,
      "use-erp/auth-lanes.mdx",
      renderCasualAuthLanesMdx(manifests, localeOverlay)
    );
    writeGeneratedMdx(
      contentRoot,
      "configure-tenant/generated/admin-sections.mdx",
      renderCasualAdminSectionsMdx(manifests, localeOverlay)
    );

    for (const moduleManifest of moduleManifests) {
      if (moduleManifest.suppressCasual) {
        continue;
      }
      const displayManifest = applyFeatureCopyToManifest(
        moduleManifest,
        localeOverlay
      );
      writeGeneratedMdx(
        contentRoot,
        `use-erp/modules/${moduleManifest.id}.mdx`,
        renderCasualModulePageMdx(displayManifest, localeOverlay)
      );
    }

    ensureMetaPages(join(contentRoot, "use-erp/meta.json"), [
      "modules",
      "auth-lanes",
    ]);
    ensureModulesMeta(
      contentRoot,
      moduleManifests
        .filter((manifest) => !manifest.suppressCasual)
        .map((manifest) => manifest.id)
    );
    ensureMetaPages(join(contentRoot, "configure-tenant/meta.json"), [
      "generated/admin-sections",
    ]);

    const indexPath = join(contentRoot, "use-erp/index.mdx");
    if (existsSync(indexPath)) {
      const patched = patchUseErpIndexMdx(
        readFileSync(indexPath, "utf8"),
        manifests
      );
      writeFileSync(indexPath, patched, "utf8");
      console.log(`[generate-feature-evidence] patched ${indexPath}`);
    }
  }

  for (const locale of docsLocales) {
    const contentRoot = localeContentRoot(locale);
    for (const file of developerFiles) {
      writeGeneratedMdx(contentRoot, file.relativePath, file.body);
    }
    ensureEvidenceMeta(contentRoot, evidencePageIds);
    writeGeneratedMdx(
      contentRoot,
      "integrate/generated/index.mdx",
      renderGeneratedIntegrateIndexMdx()
    );
    ensureGeneratedIntegrateMeta(contentRoot);
    ensureMetaPages(join(contentRoot, "integrate/meta.json"), ["generated"]);
  }

  const repoGraph = buildRepoEvidenceGraph(readCatalogCounts(), repoRoot);
  console.log(
    `[generate-feature-evidence] complete (${manifests.length} manifests, ${surfaces.length} surfaces, score=${score.score.toFixed(3)}, ${coverage.warnings.length} coverage warnings)`
  );
  console.log(
    `[generate-feature-evidence] graph hash surfaces=${repoGraph.erpAppSurfaces.length}`
  );
}

main();
