import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { zhCN } from "@fumadocs/language/zh-cn";

const GENERATED_HEADER =
  "Generated by pnpm generate:fumadocs-regional-packs from overlays/*.json — do not edit by hand.";

const appDir = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const overlaysDir = join(appDir, "src/lib/i18n/fumadocs-packs/overlays");
const packsDir = join(appDir, "src/lib/i18n/fumadocs-packs");

const regionalLocales = ["vi", "ms", "id", "th", "fil"] as const;
const canonicalKeys = Object.keys(zhCN().value);

function filterPackPayload(payload: Record<string, unknown>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(payload).filter(([key]) => !key.startsWith("_"))
  ) as Record<string, string>;
}

function main(): void {
  mkdirSync(packsDir, { recursive: true });

  for (const locale of regionalLocales) {
    const overlayPath = join(overlaysDir, `${locale}.json`);
    if (!existsSync(overlayPath)) {
      throw new Error(`Missing overlay ${overlayPath}. Add a full 169-key overlay first.`);
    }

    const overlay = filterPackPayload(
      JSON.parse(readFileSync(overlayPath, "utf8")) as Record<string, unknown>
    );
    const overlayKeys = Object.keys(overlay).sort();
    const expectedKeys = [...canonicalKeys].sort();

    if (JSON.stringify(overlayKeys) !== JSON.stringify(expectedKeys)) {
      throw new Error(
        `Overlay ${locale} key mismatch — expected ${expectedKeys.length} keys, got ${overlayKeys.length}.`
      );
    }

    const filePath = join(packsDir, `${locale}.json`);
    writeFileSync(
      filePath,
      `${JSON.stringify({ _generated: GENERATED_HEADER, ...overlay }, null, 2)}\n`,
      "utf8"
    );
    console.log(
      `[generate:fumadocs-regional-packs] synced ${overlayPath} -> ${filePath} (${canonicalKeys.length} keys)`
    );
  }
}

main();
