import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildRepoEvidenceGraph,
  renderRepoInventoryBody,
} from "../src/lib/docs-repo-evidence.ts";
import { docsLocales } from "../src/lib/i18n.ts";

const GENERATED_HEADER =
  "{/* DO NOT EDIT — generated by sync:product-docs / generate-repo-evidence */}";

const appDir = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const repoRoot = join(appDir, "../..");
const docsDataDir = join(appDir, "data");

function readCatalogCount(fileName: string): number {
  const path = join(docsDataDir, fileName);
  try {
    const payload = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    if (Array.isArray(payload.routes)) {
      return payload.routes.length;
    }
    if (Array.isArray(payload.permissions)) {
      return payload.permissions.length;
    }
    if (Array.isArray(payload.modules)) {
      return payload.modules.length;
    }
    if (Array.isArray(payload.variables)) {
      return payload.variables.length;
    }
    return 0;
  } catch {
    return 0;
  }
}

function localeContentRoot(locale: string): string {
  return join(appDir, "content/docs", locale);
}

function writeGeneratedMdx(
  contentRoot: string,
  relativePath: string,
  title: string,
  body: string
): void {
  const filePath = join(contentRoot, relativePath);
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(
    filePath,
    `---
title: ${JSON.stringify(title)}
noIndex: true
---

${GENERATED_HEADER}

${body.trim()}
`,
    "utf8"
  );
  console.log(`[generate-repo-evidence] wrote ${filePath}`);
}

function ensureMonorepoMapMetaIncludesInventory(contentRoot: string): void {
  const metaPath = join(contentRoot, "build-afenda/monorepo-map/meta.json");
  try {
    const meta = JSON.parse(readFileSync(metaPath, "utf8")) as {
      title?: string;
      icon?: string;
      pages?: string[];
    };
    const pages = [...(meta.pages ?? [])];
    if (pages.includes("repo-inventory")) {
      return;
    }
    pages.push("repo-inventory");
    writeFileSync(metaPath, `${JSON.stringify({ ...meta, pages }, null, 2)}\n`, "utf8");
    console.log(`[generate-repo-evidence] updated ${metaPath}`);
  } catch {
    // locale may not have monorepo-map yet
  }
}

function main(): void {
  const graph = buildRepoEvidenceGraph(
    {
      authRoutes: readCatalogCount("auth-routes.catalog.json"),
      permissions: readCatalogCount("permissions.catalog.json"),
      modules: readCatalogCount("modules.catalog.json"),
      envVariables: readCatalogCount("env.catalog.json"),
    },
    repoRoot
  );
  const body = renderRepoInventoryBody(graph);

  mkdirSync(docsDataDir, { recursive: true });
  writeFileSync(
    join(docsDataDir, "repo-evidence.graph.json"),
    `${JSON.stringify(graph, null, 2)}\n`,
    "utf8"
  );

  for (const locale of docsLocales) {
    const contentRoot = localeContentRoot(locale);
    writeGeneratedMdx(
      contentRoot,
      "build-afenda/monorepo-map/repo-inventory.mdx",
      "Monorepo runtime inventory",
      body
    );
    ensureMonorepoMapMetaIncludesInventory(contentRoot);
  }

  console.log(
    `[generate-repo-evidence] complete (${graph.erpAppSurfaces.length} ERP surfaces)`
  );
}

main();
