import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  AuthRoutesCatalog,
  EnvCatalog,
  ModuleCatalogEntry,
  ModulesCatalog,
  PermissionsCatalog,
  SystemAdminCatalog,
} from "../src/lib/docs-product-catalog.contract.ts";
import { docsDataDir } from "../../../scripts/docs/docs-catalog-paths.mts";
import { docsLocales } from "../src/lib/i18n.ts";

const GENERATED_HEADER =
  "{/* DO NOT EDIT — generated by sync:product-docs */}";

const appDir = join(fileURLToPath(import.meta.url), "..");

function localeContentRoot(locale: string): string {
  return join(appDir, "../content/docs", locale);
}

function readCatalog<T>(fileName: string): T {
  const path = join(docsDataDir, fileName);
  if (!existsSync(path)) {
    throw new Error(
      `Missing catalog ${path}. Run: pnpm sync:product-docs (export step first)`
    );
  }
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function writeGeneratedMdx(
  contentRoot: string,
  input: {
    readonly relativePath: string;
    readonly title: string;
    readonly body: string;
  }
): void {
  const filePath = join(contentRoot, input.relativePath);
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(
    filePath,
    `---
title: ${JSON.stringify(input.title)}
noIndex: true
---

${GENERATED_HEADER}

${input.body.trim()}
`,
    "utf8"
  );
  console.log(`Generated: ${filePath}`);
}

function renderAuthRoutesTable(catalog: AuthRoutesCatalog): string {
  const rows = catalog.routes
    .map(
      (route) =>
        `| \`${route.path}\` | ${route.lane} |`
    )
    .join("\n");

  return `# Auth routes reference

| Path | Lane |
| --- | --- |
${rows}
`;
}

function renderSystemAdminTable(catalog: SystemAdminCatalog): string {
  const rows = catalog.sections
    .map(
      (section) =>
        `| ${section.label} | \`${section.href}\` | \`${section.readPermissionKey}\` |`
    )
    .join("\n");

  return `# System admin sections reference

| Section | Path | Read permission |
| --- | --- | --- |
${rows}
`;
}

function renderPermissionsTable(catalog: PermissionsCatalog): string {
  const rows = catalog.permissions
    .map(
      (permission) =>
        `| \`${permission.key}\` | ${permission.domain} | ${permission.action} |`
    )
    .join("\n");

  return `# Permission keys reference

| Key | Domain | Action |
| --- | --- | --- |
${rows}
`;
}

function mdxSafeTableCell(value: string): string {
  return value
    .replace(/\|/g, "\\|")
    .replace(/\$\{/g, "\\${")
    .replace(/\b([\w.-]+@[\w.-]+)\b/g, "`$1`")
    .replace(/@([\w-]+)\/([\w/-]+)/g, "`@$1/$2`")
    .replace(/<([^>@]+@[^>]+)>/g, "`<$1>`")
    .replace(/\b([A-Z][A-Z0-9_]{2,})\b/g, "`$1`");
}

function renderEnvTable(catalog: EnvCatalog): string {
  const rows = catalog.variables
    .map((variable) => {
      const deprecated = variable.deprecated ? "Yes" : "No";
      const description = mdxSafeTableCell(variable.description ?? "—");
      return `| \`${variable.name}\` | ${variable.section} | ${description} | ${deprecated} |`;
    })
    .join("\n");

  return `# Environment variables reference

Names and descriptions only — never commit secret values.

| Variable | Section | Description | Deprecated |
| --- | --- | --- | --- |
${rows}
`;
}

function renderModulesTable(catalog: ModulesCatalog): string {
  const rows = catalog.modules
    .map((module) => {
      const entitlements =
        module.requiredEntitlements.length > 0
          ? module.requiredEntitlements.map((item) => `\`${item}\``).join(", ")
          : "—";
      return `| ${module.label} | \`${module.routePath}\` | \`${module.permissionKey}\` | ${entitlements} |`;
    })
    .join("\n");

  return `# ERP modules reference

| Module | Route | Permission | Required entitlements |
| --- | --- | --- | --- |
${rows}
`;
}

function renderModuleList(modules: readonly string[]): string {
  if (modules.length === 0) {
    return "—";
  }

  return modules.map((item) => `- \`${item}\``).join("\n");
}

function renderModuleStubPage(module: ModuleCatalogEntry): string {
  return `# ${module.label}

Machine-synced from \`modules.catalog.json\`. For narrative guides and API traceability, use the links below.

| Guide | Link |
| --- | --- |
| End-user guide | [/docs/use-erp/modules/${module.moduleId}](/docs/use-erp/modules/${module.moduleId}) |
| Developer evidence | [/docs/integrate/generated/evidence/${module.moduleId}](/docs/integrate/generated/evidence/${module.moduleId}) |

| Field | Value |
| --- | --- |
| Module ID | \`${module.moduleId}\` |
| Route | \`${module.routePath}\` |
| Permission | \`${module.permissionKey}\` |

## Required entitlements

${renderModuleList(module.requiredEntitlements)}

## Optional capabilities

${renderModuleList(module.optionalCapabilities)}
`;
}

function renderModulesIndex(catalog: ModulesCatalog): string {
  const rows = catalog.modules
    .map(
      (module) =>
        `| [${module.label}](./${module.moduleId}) | \`${module.routePath}\` | \`${module.permissionKey}\` |`
    )
    .join("\n");

  return `# ERP modules

Auto-generated module stubs from the entitlement manifest. Each module links to the searchable [Use ERP module guides](/docs/use-erp/modules) and [developer evidence](/docs/integrate/generated/evidence/index).

| Module | Route | Permission |
| --- | --- | --- |
${rows}
`;
}

function writeGeneratedMetaJson(
  contentRoot: string,
  relativePath: string,
  value: Record<string, unknown>
): void {
  const filePath = join(contentRoot, relativePath);
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  console.log(`Generated: ${filePath}`);
}

function ensureIntegrateMetaIncludesModules(contentRoot: string): void {
  const metaPath = join(contentRoot, "integrate/meta.json");
  if (!existsSync(metaPath)) {
    return;
  }

  const meta = JSON.parse(readFileSync(metaPath, "utf8")) as {
    title?: string;
    icon?: string;
    pages?: string[];
  };

  const pages = [...(meta.pages ?? [])];
  if (pages.includes("modules")) {
    return;
  }

  const internalV1Index = pages.indexOf("internal-v1");
  if (internalV1Index >= 0) {
    pages.splice(internalV1Index, 0, "modules");
  } else {
    pages.push("modules");
  }

  writeFileSync(
    metaPath,
    `${JSON.stringify({ ...meta, pages }, null, 2)}\n`,
    "utf8"
  );
  console.log(`Updated: ${metaPath}`);
}

function generateModulePages(
  contentRoot: string,
  catalog: ModulesCatalog
): void {
  const moduleIds = catalog.modules.map((module) => module.moduleId);

  for (const module of catalog.modules) {
    writeGeneratedMdx(contentRoot, {
      relativePath: `integrate/modules/${module.moduleId}.mdx`,
      title: module.label,
      body: renderModuleStubPage(module),
    });
  }

  writeGeneratedMdx(contentRoot, {
    relativePath: "integrate/modules/index.mdx",
    title: "ERP modules",
    body: renderModulesIndex(catalog),
  });

  writeGeneratedMetaJson(contentRoot, "integrate/modules/meta.json", {
    title: "ERP Modules",
    pages: ["index", ...moduleIds],
  });

  ensureIntegrateMetaIncludesModules(contentRoot);
}

function generateForLocale(contentRoot: string): void {
  const authRoutes = readCatalog<AuthRoutesCatalog>("auth-routes.catalog.json");
  const systemAdmin = readCatalog<SystemAdminCatalog>("system-admin.catalog.json");
  const permissions = readCatalog<PermissionsCatalog>("permissions.catalog.json");
  const env = readCatalog<EnvCatalog>("env.catalog.json");
  const modules = readCatalog<ModulesCatalog>("modules.catalog.json");

  writeGeneratedMdx(contentRoot, {
    relativePath: "use-erp/generated/auth-routes.mdx",
    title: "Auth routes reference",
    body: renderAuthRoutesTable(authRoutes),
  });
  writeGeneratedMdx(contentRoot, {
    relativePath: "configure-tenant/generated/system-admin.mdx",
    title: "System admin sections reference",
    body: renderSystemAdminTable(systemAdmin),
  });
  writeGeneratedMdx(contentRoot, {
    relativePath: "configure-tenant/generated/permissions.mdx",
    title: "Permission keys reference",
    body: renderPermissionsTable(permissions),
  });
  writeGeneratedMdx(contentRoot, {
    relativePath: "operate-tenant/generated/env.mdx",
    title: "Environment variables reference",
    body: renderEnvTable(env),
  });
  writeGeneratedMdx(contentRoot, {
    relativePath: "integrate/generated/modules.mdx",
    title: "ERP modules reference",
    body: renderModulesTable(modules),
  });
  generateModulePages(contentRoot, modules);
}

function main(): void {
  for (const locale of docsLocales) {
    const contentRoot = localeContentRoot(locale);
    console.log(`[generate-reference-pages] locale=${locale}`);
    generateForLocale(contentRoot);
  }
}

main();
