import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const LEGACY_REDIRECTS = [
  {
    source: "/:lang/docs/getting-started",
    destination: "/:lang/docs/build-afenda/getting-started",
  },
  {
    source: "/:lang/docs/monorepo-map",
    destination: "/:lang/docs/build-afenda/monorepo-map",
  },
  {
    source: "/:lang/docs/contributing",
    destination: "/:lang/docs/build-afenda/contributing",
  },
  {
    source: "/:lang/docs/apps/:path*",
    destination: "/:lang/docs/build-afenda/apps/:path*",
  },
  {
    source: "/:lang/docs/api-reference",
    destination: "/:lang/docs/integrate/internal-v1",
  },
  {
    source: "/:lang/docs/api-reference/:path*",
    destination: "/:lang/docs/integrate/internal-v1/:path*",
  },
] as const;

describe("@afenda/docs legacy URL redirects", () => {
  it("configures ARCH-DOCS-002 §6.5 redirects in next.config.ts", () => {
    const nextConfigSource = readFileSync(
      join(process.cwd(), "next.config.ts"),
      "utf8"
    );

    expect(nextConfigSource).toContain("async redirects()");
    expect(nextConfigSource).toContain("permanent: true");

    for (const expected of LEGACY_REDIRECTS) {
      expect(nextConfigSource).toContain(`source: ${JSON.stringify(expected.source)}`);
      expect(nextConfigSource).toContain(
        `destination: ${JSON.stringify(expected.destination)}`
      );
    }
  });

  it("marks generated reference MDX with do-not-edit header after sync", () => {
    const generatedPath = join(
      process.cwd(),
      "content/docs/en/use-erp/generated/auth-routes.mdx"
    );

    expect(existsSync(generatedPath)).toBe(true);
    const source = readFileSync(generatedPath, "utf8");
    expect(source).toContain("DO NOT EDIT — generated by sync:product-docs");
  });
});
