/**
 * @afenda/design-system CSS manifest.
 *
 * This file mirrors the CssEntrypointManifestItem interface from
 * @afenda/ui/governance. It cannot import from ui (cycle).
 * The governance script validates both against the shared interface.
 *
 * IMPORTANT: design-system CSS is GENERATED by scripts/generate-tokens-css.ts.
 * This manifest describes the generated outputs — do not add entries for files
 * that the generation script does not produce. If you need a new CSS output,
 * add it to the generation script first.
 *
 * Source of truth for: which CSS files design-system owns, who may import them,
 * and what authority each file carries.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Local interface mirror (kept in sync with packages/ui/src/governance/css-manifest.ts)
// ─────────────────────────────────────────────────────────────────────────────

interface CssEntrypointManifestItem {
  readonly packageName: string;
  readonly exportPath: string;
  readonly sourceFile: string;
  readonly purpose:
    | "tokens"
    | "theme-bridge"
    | "primitive-structural"
    | "renderer-structural"
    | "shell-structural"
    | "fixture";
  readonly productionSafe: boolean;
  readonly requiresTailwindTheme: boolean;
  readonly allowedImporters: readonly string[];
  readonly prohibitedImporters: readonly string[];
  readonly classNamespace: "data-attr-only" | "none" | "metadata-" | "metadata-fixture-" | "app-shell-";
  readonly propertyNamespace: "--afenda-" | "--app-shell-" | "--metadata-" | "none" | readonly ("--afenda-" | "--app-shell-" | "--metadata-" | "none")[];
  readonly generated?: boolean;
  readonly aliasOf?: string;
  readonly legacy?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Manifest
// ─────────────────────────────────────────────────────────────────────────────

export const designSystemCssManifest = [
  {
    packageName: "@afenda/design-system",
    exportPath: "./css/afenda-tokens.css",
    sourceFile: "src/css/afenda-tokens.css",
    purpose: "tokens",
    productionSafe: true,
    requiresTailwindTheme: false,
    allowedImporters: ["*"],
    prohibitedImporters: [],
    classNamespace: "none",
    propertyNamespace: "--afenda-",
    generated: true,
  },
  {
    packageName: "@afenda/design-system",
    exportPath: "./css/afenda-design-system.css",
    sourceFile: "src/css/afenda-design-system.css",
    purpose: "theme-bridge",
    productionSafe: true,
    requiresTailwindTheme: true,
    allowedImporters: ["apps/*", "@afenda/ui"],
    prohibitedImporters: ["@afenda/metadata", "@afenda/metadata-ui", "@afenda/appshell"],
    classNamespace: "none",
    propertyNamespace: "--afenda-",
    generated: true,
  },
] as const satisfies readonly CssEntrypointManifestItem[];

/**
 * CSS budget for @afenda/design-system.
 * Only generated files are allowed — no handwritten CSS.
 * globals.css is intentionally NOT used here — that name is reserved for apps.
 */
export const DESIGN_SYSTEM_CSS_BUDGET = {
  maxSourceFiles: 2,
  generatedOnly: true,
  allowedSourceFiles: [
    "src/css/afenda-tokens.css",
    "src/css/afenda-design-system.css",
  ] as const,
} as const;
