export {
  OBSERVABILITY_APPROVED_IMPORT_SUFFIXES,
  OBSERVABILITY_APPROVED_RUNTIME_DEPENDENCIES,
  OBSERVABILITY_CONSUMER_SCAN_ROOTS,
  OBSERVABILITY_CONTRACT_BARREL_DIRECTORY,
  OBSERVABILITY_ERP_AUDIT_BOOTSTRAP_SYMBOLS,
  OBSERVABILITY_ERP_INSTRUMENTATION_MODULE,
  OBSERVABILITY_FORBIDDEN_AUTHORITY_SYMBOLS,
  OBSERVABILITY_FORBIDDEN_DEPENDENCIES,
  OBSERVABILITY_REQUIRED_MODULES,
  OBSERVABILITY_SENSITIVE_AUDIT_POLICY_MODULES,
  OBSERVABILITY_SURFACE_RULE,
} from "./observability-surface-registry.js";
