import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export const GENERATED_HEADER = [
  "# Generated by pnpm env:sync — do not edit directly.",
  "# Edit .env.config or .env.secret, then run pnpm env:sync.",
  "",
].join("\n");

export const SOURCE_FILES = {
  config: ".env.config",
  secret: ".env.secret",
};

export const LOCAL_SYNC_TARGETS = [
  ".env",
  ".env.local",
  "apps/erp/.env.local",
  "apps/docs/.env.local",
  "packages/database/.env",
  "packages/execution/.env",
];

export const ENV_ALIASES = [
  { from: "NEON_DATABASE_URL", to: "DATABASE_URL" },
  { from: "NEON_PREVIEW_DATABASE_URL", to: "DATABASE_URL_PREVIEW" },
  { from: "SUPABASE_PROJECT_ID", to: "SUPABASE_PROJECT_REF" },
  { from: "BETTER_AUTH_IDENTIFY_URL", to: "BETTER_AUTH_KV_URL" },
  {
    from: "BETTER_AUTH_IDENTIFY_URL",
    to: "NEXT_PUBLIC_BETTER_AUTH_KV_URL",
  },
];

export const DEPRECATED_CONFIG_KEYS = [
  "SUPABASE_URL",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_JWKS_URL",
  "SUPABASE_PROJECT_ID",
  "STRIPE_PRICE_ID",
  "TURBO_TEAM",
];

export const DEPRECATED_SECRET_KEYS = [
  "SENTRY_DSN",
  "SUPABASE_JWT_KEY",
  "STRIPE_PUBLISHABLE_KEY",
];

const TRAILING_SLASH_PATTERN = /\/$/;

export const REQUIRED_KEYS = ["DATABASE_URL"];

export const NEXT_PUBLIC_ASSIGNMENT = /^(NEXT_PUBLIC_[A-Z0-9_]+)\s*=\s*(.*)$/;
export const NEXT_PUBLIC_PREFIX = /^NEXT_PUBLIC_/;

export const ALLOWED_KEY_FRAGMENTS = [
  "PUBLISHABLE",
  "ANON",
  "_URL",
  "APP_URL",
  "WEB_URL",
  "API_URL",
  "DOCS_URL",
];

export const FORBIDDEN_KEY_FRAGMENTS = [
  "SECRET",
  "PASSWORD",
  "PRIVATE",
  "SERVICE_ROLE",
  "DATABASE",
  "POSTGRES",
  "CONNECTION",
  "JWT",
  "SESSION",
  "SIGNING",
  "STRIPE_SK",
  "API_KEY",
  "ACCESS_TOKEN",
  "REFRESH_TOKEN",
];

export const FORBIDDEN_VALUE_PATTERNS = [
  /\bsk_live_[a-zA-Z0-9]+\b/,
  /\bsk_test_[a-zA-Z0-9]+\b/,
  /\bpostgresql:\/\//i,
  /\bmongodb(\+srv)?:\/\//i,
  /\beyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\./,
];

const QUOTE_ESCAPE_PATTERN = /[\s#"'\\]/;
const LINE_BREAK_PATTERN = /\r?\n/;
const ENV_ASSIGNMENT_PATTERN =
  /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/;
const BACKSLASH_PATTERN = /\\/g;
const DOUBLE_QUOTE_PATTERN = /"/g;

function unquote(rawValue) {
  const trimmed = rawValue.trim();

  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }

  return trimmed;
}

function quoteValue(value) {
  if (QUOTE_ESCAPE_PATTERN.test(value)) {
    return `"${value.replace(BACKSLASH_PATTERN, "\\\\").replace(DOUBLE_QUOTE_PATTERN, '\\"')}"`;
  }

  return value;
}

export function resolveRepoRoot(cwd = process.cwd()) {
  return cwd;
}

export function readOptionalEnvFile(repoRoot, relativePath) {
  const absolutePath = join(repoRoot, relativePath);

  if (!existsSync(absolutePath)) {
    return null;
  }

  return readFileSync(absolutePath, "utf8");
}

export function parseEnvFile(content) {
  const entries = new Map();
  const order = [];

  for (const line of content.split(LINE_BREAK_PATTERN)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const match = trimmed.match(ENV_ASSIGNMENT_PATTERN);

    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    const value = unquote(rawValue);

    if (!entries.has(key)) {
      order.push(key);
    }

    entries.set(key, value);
  }

  return { entries, order };
}

export function applyDerivedEnv(entries, order) {
  const publicSupabaseUrl = entries.get("NEXT_PUBLIC_SUPABASE_URL")?.trim();

  const derivedValues = [
    {
      key: "SUPABASE_URL",
      value: publicSupabaseUrl,
    },
    {
      key: "SUPABASE_PUBLISHABLE_KEY",
      value: entries.get("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY")?.trim(),
    },
    {
      key: "SUPABASE_JWKS_URL",
      value: publicSupabaseUrl
        ? `${publicSupabaseUrl.replace(TRAILING_SLASH_PATTERN, "")}/auth/v1/.well-known/jwks.json`
        : undefined,
    },
    {
      key: "SUPABASE_PROJECT_REF",
      value:
        entries.get("SUPABASE_PROJECT_REF")?.trim() ??
        entries.get("SUPABASE_PROJECT_ID")?.trim() ??
        (publicSupabaseUrl
          ? new URL(publicSupabaseUrl).hostname.split(".")[0]
          : undefined),
    },
  ];

  for (const { key, value } of derivedValues) {
    if (!value || entries.get(key)?.trim()) {
      continue;
    }

    entries.set(key, value);

    if (!order.includes(key)) {
      order.push(key);
    }
  }
}

export function applyAliases(entries, order) {
  for (const { from, to } of ENV_ALIASES) {
    const sourceValue = entries.get(from)?.trim();

    if (!sourceValue || entries.get(to)?.trim()) {
      continue;
    }

    entries.set(to, sourceValue);

    if (!order.includes(to)) {
      order.push(to);
    }
  }
}

export function findDeprecatedSourceKeys(entries, relativePath) {
  let deprecatedKeys = [];

  if (relativePath === SOURCE_FILES.config) {
    deprecatedKeys = DEPRECATED_CONFIG_KEYS;
  } else if (relativePath === SOURCE_FILES.secret) {
    deprecatedKeys = DEPRECATED_SECRET_KEYS;
  }

  return deprecatedKeys.filter((key) => entries.get(key) !== undefined);
}

export function mergeEnvSources(sources) {
  const entries = new Map();
  const order = [];

  for (const source of sources) {
    if (!source) {
      continue;
    }

    for (const key of source.order) {
      if (!entries.has(key)) {
        order.push(key);
      }

      entries.set(key, source.entries.get(key));
    }

    for (const [key, value] of source.entries) {
      if (!order.includes(key)) {
        order.push(key);
      }

      entries.set(key, value);
    }
  }

  applyAliases(entries, order);
  applyDerivedEnv(entries, order);

  return { entries, order };
}

export function loadMergedEnv(repoRoot, options = {}) {
  const overlays = Array.isArray(options.overlays) ? options.overlays : [];
  const sources = [];

  for (const relativePath of [
    SOURCE_FILES.config,
    ...overlays,
    SOURCE_FILES.secret,
  ]) {
    const content = readOptionalEnvFile(repoRoot, relativePath);

    if (content !== null) {
      sources.push(parseEnvFile(content));
    }
  }

  return mergeEnvSources(sources);
}

export function serializeEnvFile(
  { entries, order },
  header = GENERATED_HEADER
) {
  const lines = [header.trimEnd()];

  for (const key of order) {
    const value = entries.get(key);

    if (value === undefined) {
      continue;
    }

    lines.push(`${key}=${quoteValue(value)}`);
  }

  return `${lines.join("\n")}\n`;
}

export function hashContent(content) {
  return createHash("sha256").update(content).digest("hex");
}

export async function writeEnvTargets(
  repoRoot,
  content,
  targets = LOCAL_SYNC_TARGETS
) {
  const written = [];

  for (const relativePath of targets) {
    const absolutePath = join(repoRoot, relativePath);
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, content, "utf8");
    written.push(relativePath);
  }

  return written;
}

export async function readTargetContent(repoRoot, relativePath) {
  const absolutePath = join(repoRoot, relativePath);

  try {
    return await readFile(absolutePath, "utf8");
  } catch {
    return null;
  }
}

export function scanNextPublicViolations(content) {
  const violations = [];

  for (const line of content.split(LINE_BREAK_PATTERN)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const match = trimmed.match(NEXT_PUBLIC_ASSIGNMENT);

    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    const suffix = key.replace(NEXT_PUBLIC_PREFIX, "");
    const allowed = ALLOWED_KEY_FRAGMENTS.some((fragment) =>
      suffix.includes(fragment)
    );

    if (!allowed) {
      for (const fragment of FORBIDDEN_KEY_FRAGMENTS) {
        if (suffix.includes(fragment)) {
          violations.push(`${key} (forbidden key name — use server-only env)`);
          break;
        }
      }
    }

    const value = rawValue.replace(/^["']|["']$/g, "");

    for (const pattern of FORBIDDEN_VALUE_PATTERNS) {
      if (pattern.test(value)) {
        violations.push(`${key} (value looks like a secret — server-only env)`);
        break;
      }
    }
  }

  return violations;
}

const SUPABASE_DB_PASSWORD_ENV = "SUPABASE_DB_PASSWORD";
const SUPABASE_DB_REGION_ENV = "SUPABASE_DB_REGION";

export function findMissingRequiredKeys(entries) {
  if (entries.get("DATABASE_URL")?.trim()) {
    return [];
  }

  const missing = [];

  if (!entries.get(SUPABASE_DB_PASSWORD_ENV)?.trim()) {
    missing.push(SUPABASE_DB_PASSWORD_ENV);
  }

  if (!entries.get(SUPABASE_DB_REGION_ENV)?.trim()) {
    missing.push(SUPABASE_DB_REGION_ENV);
  }

  const hasProjectRef =
    entries.get("SUPABASE_PROJECT_REF")?.trim() ||
    entries.get("NEXT_PUBLIC_SUPABASE_URL")?.trim() ||
    entries.get("SUPABASE_URL")?.trim();

  if (!hasProjectRef) {
    missing.push("SUPABASE_PROJECT_REF (or NEXT_PUBLIC_SUPABASE_URL)");
  }

  if (missing.length > 0) {
    return [`DATABASE_URL or ${missing.join(" + ")}`];
  }

  return [];
}

export function findSupabaseConfigIssues(entries) {
  const issues = [];
  const publicUrl = entries.get("NEXT_PUBLIC_SUPABASE_URL")?.trim();
  const publicPublishableKey = entries
    .get("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY")
    ?.trim();
  const publicAnonKey = entries.get("NEXT_PUBLIC_SUPABASE_ANON_KEY")?.trim();
  const hasPublicKey = Boolean(publicPublishableKey || publicAnonKey);

  if (publicUrl && !hasPublicKey) {
    issues.push(
      "NEXT_PUBLIC_SUPABASE_URL is set but NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY (or legacy NEXT_PUBLIC_SUPABASE_ANON_KEY) is missing"
    );
  }

  if (hasPublicKey && !publicUrl) {
    issues.push(
      "Supabase public key is set but NEXT_PUBLIC_SUPABASE_URL is missing"
    );
  }

  const secretKey =
    entries.get("SUPABASE_SECRET_KEY")?.trim() ??
    entries.get("SUPABASE_SERVICE_ROLE_KEY")?.trim();

  if (secretKey && !publicUrl) {
    issues.push(
      "SUPABASE_SECRET_KEY is set but NEXT_PUBLIC_SUPABASE_URL is missing"
    );
  }

  const dbPassword = entries.get("SUPABASE_DB_PASSWORD")?.trim();
  const dbRegion = entries.get("SUPABASE_DB_REGION")?.trim();

  if (dbPassword && !dbRegion) {
    issues.push(
      "SUPABASE_DB_PASSWORD is set but SUPABASE_DB_REGION is missing (needed for pooler URLs)"
    );
  }

  if (dbRegion && !dbPassword && !entries.get("DATABASE_URL")?.trim()) {
    issues.push(
      "SUPABASE_DB_REGION is set but SUPABASE_DB_PASSWORD and DATABASE_URL are both missing"
    );
  }

  const jwtKid =
    entries.get("SUPABASE_JWT_KID")?.trim() ??
    entries.get("SUPABASE_JWT_KEY")?.trim();
  const jwksUrl =
    entries.get("SUPABASE_JWKS_URL")?.trim() ??
    (publicUrl
      ? `${publicUrl.replace(TRAILING_SLASH_PATTERN, "")}/auth/v1/.well-known/jwks.json`
      : undefined);

  if (jwtKid && !jwksUrl) {
    issues.push(
      "SUPABASE_JWT_KID is set but SUPABASE_JWKS_URL (or NEXT_PUBLIC_SUPABASE_URL) is missing"
    );
  }

  if (jwksUrl && publicUrl && !jwtKid) {
    issues.push(
      "SUPABASE_JWKS_URL is configured but SUPABASE_JWT_KID is missing (pin the active JWKS kid)"
    );
  }

  return issues;
}

export function findEmptyTrackedKeys(entries, order) {
  return order.filter((key) => entries.get(key) === "");
}

export async function compareSyncedTargets(repoRoot, expectedContent, targets) {
  const stale = [];

  for (const relativePath of targets) {
    const current = await readTargetContent(repoRoot, relativePath);

    if (current === null) {
      stale.push({ relativePath, reason: "missing" });
      continue;
    }

    if (hashContent(current) !== hashContent(expectedContent)) {
      stale.push({ relativePath, reason: "out of date" });
    }
  }

  return stale;
}
