/** Package public API surface — intentional aggregate export module. */

export { AuditValidationError } from "@afenda/observability";
export {
  createDatabaseAuditAdapter,
  type InsertAuditEventResult,
  insertAuditEvent,
} from "./audit/audit.writer.js";
export { buildAuditEventRow } from "./audit/audit-event.builder.js";
export {
  AUDIT_EVENT_VERSION,
  AUDIT_EVENT_VERSIONS,
  AUDIT_FIELD_LIMITS,
  type AuditEventInsertRow,
  type AuditEventMetadata,
  type AuditEventVersion,
  type AuditMetadataPrimitive,
  type AuditSource,
  type InsertAuditEventInput,
  SENSITIVE_METADATA_KEY_PATTERN,
} from "./audit/audit-event.contract.js";
export {
  assertAuditMetadata,
  auditActorTypeSchema,
  auditEventVersionSchema,
  auditMetadataPrimitiveSchema,
  auditResultSchema,
  auditSourceSchema,
  insertAuditEventInputSchema,
  parseInsertAuditEventInput,
} from "./audit/audit-event.validation.js";
export {
  AUTH_ACCOUNT_PUBLIC_COLUMNS,
  AUTH_ADAPTER_SENSITIVE_ACCOUNT_FIELDS,
  type AuthAccountRow,
  type AuthAdapterSensitiveAccountField,
  type PublicAuthAccount,
  toPublicAuthAccount,
} from "./auth/auth-account.boundary.js";
export {
  findPlatformUserIdByAuthUserId,
  type InsertAuthIdentityLinkInput,
  type InsertAuthIdentityLinkResult,
  insertAuthIdentityLink,
} from "./auth/auth-identity.service.js";
export {
  type AfendaAuthDatabase,
  type AfendaAuthDbClient,
  type CreateAuthDbOptions,
  createAuthDb,
  createAuthDbClient,
  getAuthDb,
  getAuthDbClient,
  resetAllDbClients,
  resetAuthDbClient,
} from "./auth-db.js";
export type { AfendaPgClient, CreatePgClientOptions } from "./client.types.js";
export {
  assertCompanySlug,
  assertIso3166Alpha2CountryCode,
  assertIso4217CurrencyCode,
  assertIsoDateOnly,
  assertLegalEntityCompanyType,
  buildCompanyInsertRow,
  buildCompanyUpdatePatch,
  type CompanyInsertRow,
  type CompanyUpdatePatch,
  type CompanyWriteInput,
  InvalidCompanySlugError,
  InvalidCountryCodeError,
  InvalidCurrencyCodeError,
  InvalidEffectiveDateError,
  InvalidLegalEntityCompanyTypeError,
  normalizeCompanySlug,
  normalizeOptionalIsoDateOnly,
} from "./company/company.contract.js";
export {
  type CompanyAuditContext,
  type CompanyMutationResult,
  type InsertCompanyInput,
  insertCompany,
  type UpdateCompanyInput,
  updateCompany,
} from "./company/company.service.js";
export {
  assertValidIsoRegistry,
  GOVERNED_ISO_REQUIRED_COUNTRY_CODES,
  GOVERNED_ISO_REQUIRED_CURRENCY_CODES,
  ISO_REGISTRY_ONBOARDING_STEPS,
  ISO3166_ALPHA2_COUNTRY_CODES,
  ISO3166_ALPHA2_REGISTRY_SCOPE,
  ISO4217_CURRENCY_CODES,
  ISO4217_REGISTRY_SCOPE,
  type IsoRegistryIntegrityIssue,
  type IsoRegistryIntegrityReport,
  isGovernedIso3166Alpha2CountryCode,
  isGovernedIso4217CurrencyCode,
  isIso3166Alpha2Format,
  isIso4217CurrencyFormat,
  validateIsoRegistryIntegrity,
} from "./company/iso-codes.js";
export {
  AUDIT_ACTOR_TYPES,
  type AuditActorType,
  type AuditResult,
  COMMERCIAL_PLAN_TEMPLATE_IDS,
  CONSOLIDATION_METHODS,
  type CommercialPlanTemplateId,
  type CompanyStatus,
  type ConsolidationMethod,
  ENTITLEMENT_SCOPES,
  ENTITLEMENT_TYPES,
  type EntitlementScope,
  type EntitlementType,
  FEATURE_FLAG_ROLLOUTS,
  type FeatureFlagRollout,
  KILL_SWITCH_SEVERITIES,
  type KillSwitchSeverity,
  LEGAL_ENTITY_COMPANY_TYPES,
  type LegalEntityCompanyType,
  MEMBERSHIP_SCOPE_TYPES,
  type MembershipScopeType,
  type MembershipStatus,
  ORGANIZATION_UNIT_TYPES,
  type OrganizationStatus,
  type OrganizationType,
  type OrganizationUnitType,
  OWNERSHIP_CONTROL_TYPES,
  OWNERSHIP_RELATIONSHIP_TYPES,
  type OwnershipControlType,
  type OwnershipRelationshipType,
  PLATFORM_LIFECYCLE_STATUSES,
  type PlatformLifecycleStatus,
  type PolicyEffect,
  type PolicyScope,
  type PolicyStatus,
  type RoleScope,
  type RoleStatus,
  type TenantStatus,
  USAGE_LIMIT_PERIODS,
  type UsageLimitPeriod,
  type UserStatus,
} from "./database.types.js";
export {
  type AfendaDatabase,
  type AfendaDbClient,
  type CreateDbOptions,
  createDb,
  createDbClient,
  createDbPool,
  getDb,
  getDbClient,
  resetDbClient,
  schema,
} from "./db.js";
export {
  assertValidPlanTemplateId,
  type CommercialPlanTemplate,
  type EntitlementGrantRecord,
  type EntitlementGrantTemplateRow,
  EntitlementProvisionError,
  InvalidPlanTemplateError,
  type ProvisionEntitlementBundleInput,
  type TenantEntitlementBundle,
  type UsageLimitRecord,
  type UsageLimitTemplateRow,
} from "./entitlement/entitlement.contract.js";
export { loadTenantEntitlementBundle } from "./entitlement/entitlement-load.service.js";
export {
  type EntitlementProvisionAuditContext,
  type ProvisionTenantEntitlementsInput,
  type ProvisionTenantEntitlementsResult,
  provisionTenantEntitlements,
} from "./entitlement/entitlement-provision.service.js";
export {
  commercialPlanTemplateList,
  commercialPlanTemplates,
  getCommercialPlanTemplate,
} from "./entitlement/plan-templates.js";
export {
  type FeatureFlagRecord,
  type KillSwitchRecord,
  type PlatformRolloutBundle,
  parseFeatureFlagAllowlist,
  parseFeatureFlagEnvironments,
} from "./entitlement/rollout.contract.js";
export { loadPlatformRolloutBundle } from "./entitlement/rollout-load.service.js";
export {
  type SyncPlatformRolloutResult,
  syncPlatformRolloutCatalog,
} from "./entitlement/rollout-sync.service.js";
export {
  assertEntityGroupSlug,
  buildEntityGroupInsertRow,
  buildEntityGroupUpdatePatch,
  type EntityGroupInsertRow,
  type EntityGroupUpdatePatch,
  type EntityGroupWriteInput,
  InvalidEntityGroupSlugError,
  normalizeEntityGroupSlug,
} from "./entity-group/entity-group.contract.js";
export {
  type EntityGroupAuditContext,
  type EntityGroupMutationResult,
  EntityGroupScopeMismatchError,
  type InsertEntityGroupInput,
  insertEntityGroup,
  type UpdateEntityGroupInput,
  updateEntityGroup,
} from "./entity-group/entity-group.service.js";
export {
  buildSupabaseDatabaseUrl,
  DATABASE_CONFIG_ISSUES,
  type DatabaseConfigIssue,
  type DatabaseConfigSource,
  type DatabaseConfigStatus,
  getDatabaseConfigStatus,
  getDatabaseUrl,
  getDatabaseUrlForMethod,
  getDedicatedDatabaseUrl,
  getDirectDatabaseUrl,
  getSessionDatabaseUrl,
  getSupabaseDbPassword,
  getSupabaseDbRegion,
  getSupabasePoolerHost,
  getSupabaseProjectRef,
  getTransactionDatabaseUrl,
  hasDatabaseUrl,
  hasSupabaseDatabaseConfig,
  InvalidSupabaseDbPoolerHostError,
  InvalidSupabaseProjectUrlError,
  MissingDatabaseUrlError,
  MissingMigrationDatabaseUrlError,
  MissingSupabaseDbPasswordError,
  MissingSupabaseDbRegionError,
  MissingSupabaseProjectRefError,
  resolveMigrationDatabaseUrl,
  type SupabaseConnectionMethod,
} from "./env.js";
export {
  actorUserIdRef,
  auditEventId,
  companyId,
  companyIdRef,
  type EntityRefColumn,
  entityRefId,
  membershipId,
  organizationId,
  organizationIdRef,
  type PrimaryIdColumn,
  parentOrganizationIdRef,
  permissionId,
  policyId,
  primaryId,
  roleId,
  roleIdRef,
  tenantId,
  tenantIdRef,
  userId,
  userIdRef,
} from "./ids.js";
export {
  hashMemberInvitationToken,
  type MemberInvitationRow,
  verifyMemberInvitationToken,
} from "./membership/member-invitation.contract.js";
export {
  consumeMemberInvitation,
  findPendingMemberInvitationForEmail,
  listPendingMemberInvitationsForTenant,
  type MemberInvitationRecord,
  MemberInvitationRejectedError,
  type RegisterMemberInvitationInput,
  registerMemberInvitation,
  resendMemberInvitationById,
  resetMemberInvitationsForTests,
  revokeMemberInvitation,
  revokeMemberInvitationById,
  type ValidateMemberInvitationInput,
  type ValidateMemberInvitationResult,
  validateMemberInvitation,
} from "./membership/member-invitation.service.js";
export {
  assertMembershipScopeShape,
  assertRoleMatchesMembershipScope,
  buildMembershipInsertRow,
  buildMembershipScopeKey,
  buildMembershipUpdatePatch,
  MembershipDuplicateGrantError,
  type MembershipInsertRow,
  MembershipRoleScopeError,
  MembershipScopeMismatchError,
  MembershipScopeValidationError,
  type MembershipUpdatePatch,
  type MembershipWriteInput,
} from "./membership/membership.contract.js";
export {
  type CompanyMemberListRow,
  type DeactivateMembershipInput,
  deactivateMembership,
  findMembershipById,
  type InsertMembershipInput,
  insertMembership,
  listCompanyMembers,
  type MembershipAuditContext,
  type MembershipLookupRow,
  type MembershipMutationResult,
  type UpdateMembershipInput,
  updateMembership,
} from "./membership/membership.service.js";
export {
  assertValidMigrationJournal,
  type MigrationJournalEntry,
  type MigrationJournalFile,
  type MigrationJournalIssue,
  type MigrationJournalValidationResult,
  type ValidatedMigrationJournalEntry,
  validateMigrationJournal,
} from "./migrations/journal.contract.js";
export {
  assertNoOrganizationCycle,
  assertOrganizationSlug,
  buildOrganizationInsertRow,
  buildOrganizationUpdatePatch,
  InvalidOrganizationSlugError,
  normalizeOrganizationSlug,
  OrganizationCycleError,
  OrganizationHasChildrenError,
  type OrganizationInsertRow,
  OrganizationParentNotFoundError,
  OrganizationScopeMismatchError,
  type OrganizationUnitAuthorityRecord,
  type OrganizationUpdatePatch,
  OrganizationValidationError,
  type OrganizationWriteInput,
  resolveLegalEntityId,
  resolveOrganizationUnitType,
  resolveParentOrganizationUnitId,
  toOrganizationUnitAuthorityRecord,
} from "./organization/organization.contract.js";
export {
  type DeleteOrganizationInput,
  deleteOrganization,
  type InsertOrganizationInput,
  insertOrganization,
  type OrganizationAuditContext,
  type OrganizationMutationResult,
  type UpdateOrganizationInput,
  updateOrganization,
} from "./organization/organization.service.js";
export {
  CONSOLIDATION_TREATMENTS,
  type ConsolidationTreatment,
  consolidationMethodToTreatment,
  consolidationTreatmentToMethod,
  isConsolidationTreatment,
} from "./ownership-interest/ownership-interest.consolidation-treatment.js";
export {
  assertDistinctLegalEntities,
  buildOwnershipInterestInsertRow,
  type OwnershipInterestAuthorityRecord,
  OwnershipInterestCycleError,
  type OwnershipInterestInsertRow,
  OwnershipInterestValidationError,
  type OwnershipInterestWriteInput,
  resolveInvesteeLegalEntityId,
  resolveNonControllingInterestApplicable,
  toOwnershipInterestAuthorityRecord,
} from "./ownership-interest/ownership-interest.contract.js";
export {
  type InsertOwnershipInterestInput,
  insertOwnershipInterest,
  type OwnershipInterestAuditContext,
  type OwnershipInterestMutationResult,
  OwnershipInterestScopeMismatchError,
} from "./ownership-interest/ownership-interest.service.js";
export {
  type FindOwnershipInterestsInput,
  findOwnershipInterestsByEntityGroup,
} from "./ownership-interest/ownership-interest-lookup.service.js";
export {
  buildPermissionInsertRow,
  buildPermissionUpdatePatch,
  type PermissionCatalogWriteInput,
  type PermissionInsertRow,
  PermissionKeyImmutableError,
  type PermissionRecord,
  type PermissionUpdatePatch,
} from "./permission/permission.contract.js";
export {
  type InsertPermissionInput,
  insertPermission,
  type PermissionAuditContext,
  type PermissionMutationResult,
  type UpdatePermissionInput,
  updatePermission,
} from "./permission/permission.service.js";
export {
  assertPermissionKey,
  createPermissionKey,
  InvalidPermissionKeyError,
  isPermissionKey,
  type PermissionKey,
} from "./permission-key.contract.js";
export {
  assertPlatformSlug,
  InvalidPlatformSlugError,
  MAX_PLATFORM_SLUG_LENGTH,
  normalizePlatformSlug,
} from "./platform-slug.js";
export {
  assertPolicyKey,
  assertPolicyPriority,
  assertPolicyScopeMatchesTenant,
  buildPolicyInsertRow,
  buildPolicyUpdatePatch,
  DEFAULT_POLICY_PRIORITY,
  InvalidPolicyKeyError,
  InvalidPolicyPriorityError,
  isPolicyOperational,
  normalizePolicyKey,
  type PolicyInsertRow,
  PolicyKeyImmutableError,
  type PolicyRecord,
  PolicyScopeTenantMismatchError,
  type PolicyUpdatePatch,
  type PolicyWriteInput,
} from "./policy/policy.contract.js";
export {
  type ArchivePolicyInput,
  archivePolicy,
  type InsertPolicyInput,
  insertPolicy,
  type PolicyAuditContext,
  type PolicyMutationResult,
  type UpdatePolicyInput,
  updatePolicy,
} from "./policy/policy.service.js";
export {
  assertPolicyConditionForEffect,
  InvalidPolicyConditionError,
  POLICY_CONDITION_VERSION,
  type PolicyCondition,
  type PolicyConditionMatch,
  type PolicyConditionV1,
  type PolicyGateDecision,
  parsePolicyCondition,
  policyConditionMatches,
} from "./policy/policy.validation.js";
export { createPgPool, DEFAULT_POOL_CONFIG } from "./pool.js";
export {
  assertProjectSlug,
  buildProjectInsertRow,
  buildProjectUpdatePatch,
  normalizeProjectSlug,
  PROJECT_DOMAIN_STATUS,
  PROJECT_LIFECYCLE_STATUSES,
  type ProjectAuthorityRecord,
  type ProjectDomainStatus,
  type ProjectInsertRow,
  type ProjectLifecycleStatus,
  type ProjectUpdatePatch,
  type ProjectWriteInput,
} from "./project/project.contract.js";
export {
  type InsertProjectInput,
  insertProject,
  type ProjectAuditContext,
  type ProjectMutationResult,
  ProjectScopeMismatchError,
  type UpdateProjectInput,
  updateProject,
} from "./project/project.service.js";
export {
  assertRlsTenantFilter,
  DEFAULT_RLS_GRANT_ELEVATION_FLAGS,
  type MembershipScopeMatchInput,
  membershipMatchesGrantScope,
  PERSISTED_MEMBERSHIP_SCOPE_TYPES,
  PLANNED_MEMBERSHIP_SCOPE_TYPES,
  type ResolvedRlsGrantScope,
  type ResolveRlsGrantScopeInput,
  RLS_GRANT_ELEVATION_KINDS,
  RLS_GRANT_SCOPE_TYPES,
  type RlsFilterContext,
  type RlsGrantElevationFlags,
  type RlsGrantElevationKind,
  type RlsGrantScopeType,
  RlsGrantScopeValidationError,
  resolveRlsGrantElevations,
  resolveRlsGrantScope,
  resolveRlsGrantScopeType,
  toRlsFilterContext,
} from "./rls/rls-grant.contract.js";
export {
  RLS_SESSION_KEYS,
  type RlsSessionContext,
} from "./rls/rls-session-context.contract.js";
export { withRlsSessionContext } from "./rls/with-rls-session-context.js";
export {
  assertRoleKey,
  assertRoleScopeMatchesTenant,
  buildRoleInsertRow,
  buildRoleUpdatePatch,
  InvalidRoleKeyError,
  isRoleOperational,
  normalizeRoleKey,
  type RoleInsertRow,
  RoleKeyImmutableError,
  type RoleRecord,
  RoleScopeTenantMismatchError,
  type RoleUpdatePatch,
  type RoleWriteInput,
} from "./role/role.contract.js";
export {
  type ArchiveRoleInput,
  archiveRole,
  type InsertRoleInput,
  insertRole,
  type RoleAuditContext,
  RoleHasActiveMembershipsError,
  type RoleMutationResult,
  type UpdateRoleInput,
  updateRole,
} from "./role/role.service.js";
export {
  assertRolePermissionGrantBoundaries,
  type RolePermissionGrantBoundaryInput,
  RolePermissionGrantError,
  type RolePermissionGrantPermissionSnapshot,
  type RolePermissionGrantRoleSnapshot,
  RolePermissionTenantMismatchError,
} from "./role-permission/role-permission.contract.js";
export {
  type GrantPermissionToRoleInput,
  type GrantPermissionToRoleResult,
  grantPermissionToRole,
  type RolePermissionAuditContext,
} from "./role-permission/role-permission.service.js";
export { resetRuntimeSingleton } from "./runtime-singleton.js";
export {
  type AuthSchema,
  auditEvents,
  auditResultEnum,
  auditSourceEnum,
  authAccount,
  authIdentityLinks,
  authPasskey,
  authSchema,
  authSession,
  authSsoProvider,
  authTwoFactor,
  authUser,
  authVerification,
  companies,
  companyStatusEnum,
  consolidationMethodEnum,
  entitlementGrants,
  entitlementScopeEnum,
  entitlementTypeEnum,
  entityGroups,
  executionRuns,
  executionStatusEnum,
  featureFlagRolloutEnum,
  killSwitchSeverityEnum,
  legalEntityOwnership,
  memberInvitations,
  membershipScopeEnum,
  membershipStatusEnum,
  memberships,
  OUTBOX_STATUSES,
  type OutboxStatus,
  organizationStatusEnum,
  organizations,
  organizationTypeEnum,
  outboxEvents,
  outboxStatusEnum,
  ownershipControlTypeEnum,
  ownershipRelationshipTypeEnum,
  type PlatformSchema,
  permissions,
  platformFeatureFlags,
  platformKillSwitches,
  platformSchema,
  policies,
  policyEffectEnum,
  policyScopeEnum,
  policyStatusEnum,
  projectLifecycleStatusEnum,
  projects,
  rolePermissions,
  roleScopeEnum,
  roleStatusEnum,
  roles,
  storageObjects,
  storageProviderEnum,
  teams,
  tenantCommercialPlans,
  tenantSettings,
  tenantSsoProviders,
  tenantStatusEnum,
  tenants,
  usageLimitCounters,
  usageLimitPeriodEnum,
  userPreferences,
  userStatusEnum,
  users,
} from "./schema/index.js";
export { PLATFORM_PERMISSION_CATALOG } from "./seeds/platform-permissions.catalog.js";
export {
  PLATFORM_FEATURE_FLAG_CATALOG,
  PLATFORM_KILL_SWITCH_CATALOG,
} from "./seeds/platform-rollout.catalog.js";
export type {
  SeedProfile,
  SeedVerificationResult,
} from "./seeds/seed-types.js";
export { verifyPlatformSeed } from "./seeds/seed-verify.js";
export {
  assertDatabaseConnectionConsumer,
  DATABASE_CONNECTION_CONSUMERS,
  DATABASE_CONNECTION_ROUTING,
  type DatabaseConnectionConsumer,
  InvalidDatabaseConnectionConsumerError,
  isDatabaseConnectionConsumer,
  resolveConnectionMethodForConsumer,
  resolveDatabaseUrlForConsumer,
} from "./supabase/connection-routing.contract.js";
export {
  isSupabaseExcludedProductionCapability,
  SUPABASE_EXCLUDED_PRODUCTION_CAPABILITIES,
  type SupabaseExcludedProductionCapability,
} from "./supabase/excluded-production-capabilities.contract.js";
export { TEAM_ORGANIZATION_UNIT_TYPE } from "./team/team.constants.js";
export {
  assertTeamSlug,
  buildTeamInsertRow,
  buildTeamUpdatePatch,
  normalizeTeamSlug,
  type TeamAuthorityRecord,
  type TeamInsertRow,
  type TeamUpdatePatch,
  type TeamWriteInput,
} from "./team/team.contract.js";
export {
  type InsertTeamInput,
  insertTeam,
  type TeamAuditContext,
  type TeamMutationResult,
  TeamScopeMismatchError,
  type UpdateTeamInput,
  updateTeam,
} from "./team/team.service.js";
export {
  findTeamByCompanyAndSlug,
  findTeamById,
  isTeamOrganizationRow,
  type TeamLookupRow,
} from "./team/team-lookup.service.js";
export {
  assertTenantSlug,
  buildTenantInsertRow,
  buildTenantUpdatePatch,
  getTenantAccessBlockReason,
  InvalidTenantSlugError,
  isTenantOperational,
  normalizeTenantSlug,
  type TenantInsertRow,
  type TenantRecord,
  type TenantUpdatePatch,
  type TenantWriteInput,
} from "./tenant/tenant.contract.js";
export {
  type ArchiveTenantInput,
  archiveTenant,
  type InsertTenantInput,
  insertTenant,
  type TenantAuditContext,
  type TenantMutationResult,
  type UpdateTenantInput,
  updateTenant,
} from "./tenant/tenant.service.js";
export {
  DATABASE_TENANT_DOMAIN_BARREL_DIRECTORIES,
  DATABASE_TENANT_DOMAIN_MODULES,
  type DatabaseTenantDomainImplementationStatus,
  type DatabaseTenantDomainModule,
} from "./tenant-domain/tenant-domain-registry.js";
export {
  parseTenantBillingSettings,
  parseTenantIntegrationsSettings,
  parseTenantNotificationsSettings,
  parseTenantWorkspaceSettings,
  type TenantBillingSettings,
  type TenantIntegrationsSettings,
  type TenantNotificationsSettings,
  type TenantSettingsRecord,
  type TenantSettingsSectionKey,
  type TenantWorkspaceSettings,
  tenantBillingSettingsSchema,
  tenantIntegrationsSettingsSchema,
  tenantNotificationsSettingsSchema,
  tenantWorkspaceSettingsSchema,
} from "./tenant-settings/tenant-settings.contract.js";
export {
  getTenantSettingsByTenantId,
  type TenantSettingsAuditContext,
  type TenantSettingsMutationResult,
  type UpsertTenantSettingsSectionInput,
  upsertTenantSettingsSection,
} from "./tenant-settings/tenant-settings.service.js";
export {
  type GetEnabledTenantSsoProviderForTenantDomainInput,
  type GetTenantSsoProviderByIdInput,
  type GetTenantSsoProviderByProviderIdInput,
  getEnabledTenantSsoProviderForTenantDomainInputSchema,
  getTenantSsoProviderByIdInputSchema,
  getTenantSsoProviderByProviderIdInputSchema,
  parseTenantSsoOidcMetadata,
  parseTenantSsoProviderMetadata,
  parseTenantSsoProviderSummary,
  type SetTenantSsoProviderEnabledInput,
  setTenantSsoProviderEnabledInputSchema,
  TENANT_SSO_CLIENT_SECRET_ENV_KEY,
  TENANT_SSO_PROTOCOLS,
  type TenantSsoOidcMetadata,
  type TenantSsoProtocol,
  type TenantSsoProviderMetadata,
  type TenantSsoProviderSummary,
  tenantSsoProtocolSchema,
  toTenantSsoProviderSummary,
  type UpsertTenantSsoOidcProviderInput,
  upsertTenantSsoOidcProviderInputSchema,
} from "./tenant-sso/tenant-sso-provider.contract.js";
export {
  getEnabledTenantSsoProviderForTenantDomain,
  getTenantSsoProviderById,
  getTenantSsoProviderByProviderId,
  listTenantSsoProvidersByTenantId,
  resetTenantSsoProvidersForTests,
  resolveTenantIdFromSsoEmailDomain,
  setTenantSsoProviderEnabled,
  TenantSsoProviderNotFoundError,
  upsertTenantSsoOidcProvider,
} from "./tenant-sso/tenant-sso-provider.service.js";
export {
  type CreatedAtColumn,
  createdAtColumn,
  type UpdatedAtColumn,
  updatedAtColumn,
} from "./timestamps.js";
export {
  assertEmail,
  buildUserInsertRow,
  buildUserUpdatePatch,
  InvalidEmailError,
  isPlatformUserActive,
  normalizeEmail,
  type PlatformUserRecord,
  type PlatformUserUpdatePatch,
  type PlatformUserWriteInput,
} from "./user/user.contract.js";
export {
  type DeactivateUserInput,
  deactivateUser,
  type InsertUserInput,
  insertUser,
  type UpdateUserInput,
  type UserAuditContext,
  type UserMutationResult,
  updateUser,
} from "./user/user.service.js";
export {
  defaultUserDisplayPreferences,
  parseUserDisplayPreferences,
  parseUserNotificationsPreferences,
  USER_DISPLAY_DENSITY_VALUES,
  USER_DISPLAY_THEME_VALUES,
  type UserDisplayPreferences,
  type UserNotificationsPreferences,
  type UserPreferencesRecord,
  type UserPreferencesSectionKey,
  userDisplayPreferencesSchema,
  userNotificationsPreferencesSchema,
} from "./user-preferences/user-preferences.contract.js";
export {
  getUserPreferencesByUserId,
  type UpsertUserPreferencesSectionInput,
  type UserPreferencesAuditContext,
  type UserPreferencesMutationResult,
  upsertUserPreferencesSection,
} from "./user-preferences/user-preferences.service.js";
export type {
  CompanyLookupRow as LegalEntityLookupRow,
  OrganizationLookupRow as OrganizationUnitLookupRow,
} from "./workspace/workspace-lookup.service.js";
export {
  type CompanyLookupRow,
  type EntityGroupLookupRow,
  findActiveCompaniesByEntityGroupId,
  findCompanyById,
  findCompanyByTenantAndSlug,
  findEntityGroupById,
  findOrganizationByCompanyAndSlug,
  findOrganizationById,
  findTenantById,
  findTenantBySlug,
  type OrganizationLookupRow,
  type TenantLookupRow,
} from "./workspace/workspace-lookup.service.js";
