/** Platform kernel — cross-package vocabulary, wire-safe contracts, and context shapes (PAS-001). */

export const PACKAGE_NAME = "@afenda/kernel" as const;

export function getPackageName(): typeof PACKAGE_NAME {
  return PACKAGE_NAME;
}

export {
  type AccountingReadinessContext,
  type AccountingReadinessWireContext,
  type assertAccountingReadinessContextJsonSerializable,
  type assertLocalizationContextWireSerializable,
  CONSOLIDATION_TREATMENTS,
  type ConsolidationEntityScope,
  type ConsolidationScopeContext,
  type ConsolidationTreatment,
  compareEnterpriseHierarchyTierOrder,
  compareOperatingContextLayerOrder,
  DEFAULT_PERMISSION_GRANT_ELEVATION_FLAGS,
  type DeriveConsolidationScopeInput,
  deriveConsolidationScopeContext,
  ENTERPRISE_HIERARCHY_TIER_DEFINITIONS,
  ENTERPRISE_HIERARCHY_TIERS,
  type EnterpriseHierarchyPersistence,
  type EnterpriseHierarchyTier,
  type EnterpriseHierarchyTierDefinition,
  type EntityGroupContext,
  findUntrustedClientAuthorityFields,
  getOperatingContextLayer,
  isEnterpriseHierarchyTier,
  isOperatingContextLayerId,
  isOwnershipInterestEffectiveAt,
  isPermissionGrantScopeType,
  isUntrustedClientAuthorityFieldKey,
  KERNEL_OPERATING_CONTEXT_REQUIRED_MODULES,
  KERNEL_OPERATING_CONTEXT_SUPPORT_MODULES,
  type KernelOperatingContextPrimaryType,
  type KernelOperatingContextRequiredModule,
  LEGAL_ENTITY_COMPANY_TYPES,
  type LegalEntityCompanyType,
  type LegalEntityContext,
  type LocalizationContext,
  normalizeRuntimeModulePath,
  OPERATING_CONTEXT_ERROR_CODES,
  OPERATING_CONTEXT_LAYER_IDS,
  OPERATING_CONTEXT_LAYERS,
  OPERATING_CONTEXT_OWNERSHIP_SPLIT,
  OPERATING_CONTEXT_POLICY,
  type OperatingContext,
  type OperatingContextActor,
  type OperatingContextError,
  type OperatingContextErrorCode,
  type OperatingContextFieldMap,
  type OperatingContextLayerDefinition,
  type OperatingContextLayerId,
  type OperatingContextLayerKind,
  type OperatingContextProhibitedKernelBehavior,
  type OperatingContextResult,
  type OperatingContextSelection,
  ORGANIZATION_UNIT_TYPES,
  type OrganizationUnitContext,
  type OrganizationUnitType,
  OWNERSHIP_CONTROL_TYPES,
  type OwnershipControlType,
  type OwnershipInterestContext,
  PERMISSION_GRANT_SCOPE_TYPES,
  type PermissionGrantElevationFlags,
  type PermissionGrantScopeType,
  type PermissionScopeContext,
  PLATFORM_LIFECYCLE_STATUSES,
  type PlatformLifecycleStatus,
  PROJECT_LIFECYCLE_STATUSES,
  type ProjectContext,
  type ProjectLifecycleStatus,
  parseLocalizationContext,
  parseSurfaceId,
  parseWorkflowId,
  type SurfaceContext,
  type SurfaceId,
  serializeLocalizationContext,
  type TeamContext,
  type TenantContext,
  toSurfaceContext,
  toWorkflowContext,
  UNTRUSTED_CLIENT_AUTHORITY_FIELD_KEYS,
  type UntrustedClientAuthorityFieldKey,
  type WireLocalizationContext,
  type WorkflowContext,
  type WorkflowId,
  type WorkspaceContext,
} from "./context/index.js";
export {
  ACCOUNT_TYPES,
  ACCOUNTING_AUDIT_ACTIONS,
  ACCOUNTING_AUTHORITY_ADR,
  ACCOUNTING_AUTHORITY_FINGERPRINT,
  ACCOUNTING_CONTRACTS_OWNER,
  ACCOUNTING_PACKAGE_LIFECYCLE,
  ACCOUNTING_PERMISSION_KEY_VOCABULARY,
  ACCOUNTING_REGISTRY_ID,
  type AccountId,
  type AccountingAuditAction,
  type AccountingDomainWireContext,
  type AccountType,
  FISCAL_PERIOD_STATES,
  JOURNAL_DOCUMENT_TYPES,
  POSTING_STATUSES,
  toAccountingDomainContext,
} from "./contracts/accounting-domain/index.js";
export {
  type AppError,
  type AppErrorCode,
  AppErrors,
  type ValidationFieldError,
} from "./contracts/app-error.contract.js";
export {
  BUSINESS_MASTER_DATA_AUTHORITY_REGISTRY,
  BUSINESS_MASTER_DATA_ENTITY_IDS,
  type BusinessMasterDataAuthorityEntry,
  type BusinessMasterDataEntityId,
  type BusinessMasterDataIdentityScope,
  type BusinessMasterDataPkgCode,
  getBusinessMasterDataAuthority,
  isBusinessMasterDataEntityId,
  type ProductWireReference,
  TBD_BUSINESS_MASTER_DATA_ENTITIES,
  type WarehouseWireReference,
} from "./contracts/business-master-data/index.js";
export {
  assertExecutionContext,
  createExecutionContext,
  EXECUTION_CONTEXT_SOURCES,
  type ExecutionContext,
  type ExecutionContextInput,
  type ExecutionContextSource,
} from "./contracts/execution-context.contract.js";
export {
  EXECUTION_CONTEXT_POLICY,
  EXECUTION_CONTEXT_REQUIRED_FIELDS,
  type ExecutionContextRequiredField,
  isExecutionContext,
  isExecutionContextSource,
} from "./contracts/execution-context.policy.contract.js";
export type {
  JsonObject,
  JsonPrimitive,
  JsonValue,
} from "./contracts/json-wire.contract.js";
export {
  isKernelPackageCurrentSrcTopLevel,
  isKernelPackageSubpathExport,
  KERNEL_PACKAGE_CURRENT_SRC_TOP_LEVEL,
  KERNEL_PACKAGE_LAYOUT_POLICY,
  KERNEL_PACKAGE_LAYOUT_PROHIBITED_PATTERNS,
  KERNEL_PACKAGE_PROHIBITED_PATHS,
  KERNEL_PACKAGE_SRC_ROOT_BARREL,
  KERNEL_PACKAGE_SUBPATH_EXPORTS,
  KERNEL_PACKAGE_TARGET_PATHS,
  type KernelPackageCurrentSrcTopLevel,
  type KernelPackageLayoutProhibitedPattern,
  type KernelPackageProhibitedPath,
  type KernelPackageSubpathExport,
  type KernelPackageTargetPath,
} from "./contracts/kernel-package-layout.contract.js";
export {
  getPlatformEntityAuthority,
  isPlatformEntityId,
  PLATFORM_ENTITY_AUTHORITY_REGISTRY,
  PLATFORM_ENTITY_IDS,
  type PlatformEntityAuthorityEntry,
  type PlatformEntityId,
  type RepoRelativePath,
} from "./contracts/platform/index.js";
export type { ProblemDetail } from "./contracts/problem-detail.contract.js";
export {
  err,
  isErr,
  isOk,
  ok,
  type Result,
  type ResultFailure,
  type ResultSuccess,
} from "./contracts/result.contract.js";
export type { DomainEvent } from "./events/domain-event.contract.js";
export {
  getKernelDecisionMatrixRow,
  getKernelImplementationSequenceStep,
  getKernelProhibitedOwnershipConcern,
  isKernelDecisionMatrixRowId,
  isKernelImplementationSequenceStepId,
  isKernelProhibitedOwnershipConcernId,
  KERNEL_DECISION_MATRIX_POLICY,
  KERNEL_DECISION_MATRIX_ROW_IDS,
  KERNEL_DECISION_MATRIX_ROWS,
  KERNEL_IMPLEMENTATION_SEQUENCE_DEFERRED_ADDITIONS,
  KERNEL_IMPLEMENTATION_SEQUENCE_DEFERRED_PATHS,
  KERNEL_IMPLEMENTATION_SEQUENCE_POLICY,
  KERNEL_IMPLEMENTATION_SEQUENCE_STEP_IDS,
  KERNEL_IMPLEMENTATION_SEQUENCE_STEPS,
  KERNEL_PROHIBITED_OWNERSHIP_CATEGORIES,
  KERNEL_PROHIBITED_OWNERSHIP_CONCERN_IDS,
  KERNEL_PROHIBITED_OWNERSHIP_CONCERNS,
  KERNEL_PROHIBITED_OWNERSHIP_POLICY,
  type KernelDecisionMatrixBelongsInKernel,
  type KernelDecisionMatrixRow,
  type KernelDecisionMatrixRowId,
  type KernelImplementationSequenceDeferredAddition,
  type KernelImplementationSequenceStep,
  type KernelImplementationSequenceStepId,
  type KernelProhibitedOwnershipCategory,
  type KernelProhibitedOwnershipConcern,
  type KernelProhibitedOwnershipConcernId,
  kernelOwnsBoundaryConcern,
  listKernelDecisionMatrixRows,
  listKernelImplementationSequenceSteps,
  listKernelProhibitedOwnershipConcerns,
} from "./governance/index.js";
export {
  type Brand,
  unbrand,
} from "./identity/brand/index.js";
export {
  type AssetId,
  type AssetNo,
  type AuditEntityIdentity,
  type AuditEventId,
  type assertPlatformIdBoundaryRegistryCoverage,
  assertRegisteredEnterpriseIdPrefix,
  brandCountryCode,
  brandCurrencyCode,
  brandDateFormat,
  brandLocaleCode,
  brandNumberFormat,
  brandRequiredCountryCode,
  brandRequiredCurrencyCode,
  brandRequiredUomCode,
  brandTimezoneId,
  brandUomCode,
  buildCanonicalEnterpriseIdCheckPattern,
  type CanonicalEnterpriseId,
  type CanonicalId,
  type CanonicalIdBodyGenerator,
  type CompanyId,
  type CorrelationId,
  type CountryCode,
  type CurrencyCode,
  type CustomerId,
  type CustomerNo,
  createAssetId,
  createAuditEventId,
  createCanonicalId,
  createCompanyId,
  createCorrelationId,
  createCustomerId,
  createDocumentId,
  createEmployeeId,
  createEntityGroupId,
  createExecutionId,
  createFixtureCanonicalIdBodyGenerator,
  createMembershipId,
  createOrganizationId,
  createOwnershipInterestId,
  createPermissionId,
  createPolicyId,
  createProductId,
  createProjectId,
  createRoleId,
  createSupplierId,
  createTeamId,
  createTenantId,
  createTestEnterpriseId,
  createUserId,
  createWarehouseId,
  type DateFormat,
  type DocumentId,
  type DocumentNo,
  type EmployeeId,
  type EmployeeNo,
  ENTERPRISE_ID_FAMILIES,
  ENTERPRISE_ID_FAMILY_KEYS,
  ENTERPRISE_ID_FAMILY_PREFIX_AUTHORITY,
  ENTERPRISE_ID_PREFIX_TO_FAMILY,
  ENTERPRISE_ID_TYPE_NAMES,
  type EnterpriseBrand,
  type EnterpriseIdFamily,
  type EnterpriseIdPrefix,
  type EntityGroupId,
  type ExecutionId,
  extractCanonicalEnterpriseIdPrefix,
  FORBIDDEN_PLATFORM_FLOOR_ID_SYMBOLS,
  type ForbiddenPlatformFloorIdSymbol,
  getEnterpriseIdFamiliesByCategory,
  getIdentityStackLayer,
  getIdFamilyDefinition,
  getPlatformIdFamilyDefinition,
  ID_FAMILIES,
  ID_FAMILY_CATEGORIES,
  ID_FAMILY_COUNT,
  IDENTITY_AUTHORITY_ADR,
  IDENTITY_AUTHORITY_PAS,
  IDENTITY_AUTHORITY_SECTION,
  IDENTITY_BOUNDARY_POLICY,
  IDENTITY_BOUNDARY_PROHIBITED_PATTERNS,
  IDENTITY_GOVERNANCE_AUTHORITY,
  IDENTITY_PROHIBITED_PATTERNS,
  IDENTITY_PROMOTION_REQUIREMENTS,
  IDENTITY_STACK_LAYER_IDS,
  IDENTITY_STACK_LAYERS,
  IDENTITY_STACK_POLICY,
  IDENTITY_TRUST_BOUNDARY_POLICY,
  IDENTITY_TRUST_BOUNDARY_PROHIBITED_PATTERNS,
  type IdentityStackLayerDefinition,
  type IdentityStackLayerId,
  type IdentityStackProhibitedCrossLayerPattern,
  type IdentityTrustBoundaryProhibitedPattern,
  type IdFamily,
  type IdFamilyCategory,
  type IdFamilyDefinition,
  type InternalEntityPk,
  isCanonicalEnterpriseId,
  isCanonicalEnterpriseIdForFamily,
  isEnterpriseIdFamily,
  isIdentityProhibitedPatternId,
  isIdentityStackLayerId,
  isKernelIdentityGovernanceGateId,
  isRegisteredCanonicalEnterpriseId,
  isRegisteredEnterpriseIdPrefix,
  KERNEL_IDENTITY_GOVERNANCE_BUNDLE,
  KERNEL_IDENTITY_GOVERNANCE_GATES,
  type LocaleCode,
  type MembershipId,
  type NumberFormat,
  normalizeAssetNoForWire,
  normalizeCompanyIdForWire,
  normalizeCorrelationIdForWire,
  normalizeCustomerNoForWire,
  normalizeDocumentNoForWire,
  normalizeEmployeeNoForWire,
  normalizeMembershipIdForWire,
  normalizeRoleIdForWire,
  normalizeSkuNoForWire,
  normalizeSupplierNoForWire,
  normalizeTenantHumanReferenceForWire,
  normalizeTenantIdForWire,
  normalizeWarehouseCodeForWire,
  type OrganizationId,
  type OwnershipInterestId,
  type ParsedRegisteredCanonicalEnterpriseId,
  type PermissionId,
  PLATFORM_ID_AUTHORITY_PAS,
  PLATFORM_ID_AUTHORITY_SECTION,
  PLATFORM_ID_BOUNDARY_WIRE_NORMALIZERS,
  PLATFORM_ID_FAMILY_REGISTRY,
  PLATFORM_ID_FAMILY_TYPE_NAMES,
  type PlatformIdCategory,
  type PlatformIdFamilyDefinition,
  type PolicyId,
  PRIMITIVE_ID_FAMILY_COUNT,
  type ProductId,
  type ProjectId,
  parseAssetId,
  parseAssetNo,
  parseAuditEntityIdentity,
  parseAuditEventId,
  parseCanonicalId,
  parseCompanyId,
  parseCorrelationId,
  parseCountryCode,
  parseCurrencyCode,
  parseCustomerId,
  parseCustomerNo,
  parseDateFormat,
  parseDocumentId,
  parseDocumentNo,
  parseEmployeeId,
  parseEmployeeNo,
  parseEntityGroupId,
  parseExecutionId,
  parseInternalEntityPk,
  parseLocaleCode,
  parseMembershipId,
  parseNumberFormat,
  parseOptionalAssetId,
  parseOptionalAssetNo,
  parseOptionalAuditEventId,
  parseOptionalCompanyId,
  parseOptionalCustomerId,
  parseOptionalCustomerNo,
  parseOptionalDocumentId,
  parseOptionalDocumentNo,
  parseOptionalEmployeeId,
  parseOptionalEmployeeNo,
  parseOptionalEntityGroupId,
  parseOptionalMembershipId,
  parseOptionalOrganizationId,
  parseOptionalOwnershipInterestId,
  parseOptionalPermissionId,
  parseOptionalPolicyId,
  parseOptionalProductId,
  parseOptionalProjectId,
  parseOptionalRoleId,
  parseOptionalSkuNo,
  parseOptionalSupplierId,
  parseOptionalSupplierNo,
  parseOptionalTeamId,
  parseOptionalTenantHumanReference,
  parseOptionalTenantId,
  parseOptionalUserId,
  parseOptionalWarehouseCode,
  parseOptionalWarehouseId,
  parseOrganizationId,
  parseOwnershipInterestId,
  parsePermissionId,
  parsePolicyId,
  parseProductId,
  parseProjectId,
  parseRegisteredCanonicalEnterpriseId,
  parseRoleId,
  parseSkuNo,
  parseSupplierId,
  parseSupplierNo,
  parseTeamId,
  parseTenantHumanReference,
  parseTenantId,
  parseTimezoneId,
  parseUomCode,
  parseUserId,
  parseWarehouseCode,
  parseWarehouseId,
  parseWireCanonicalId,
  parseWireRegisteredCanonicalId,
  REGISTERED_ENTERPRISE_ID_PREFIXES,
  REGISTRY_FAMILY_COUNT,
  type RegisteredEnterpriseIdPrefix,
  type RoleId,
  resolveEnterpriseIdFamilyFromPrefix,
  type SkuNo,
  type SupplierId,
  type SupplierNo,
  serializeAuditEntityIdentity,
  serializeCanonicalId,
  TENANT_HUMAN_REFERENCE_SCOPE_DEFINITIONS,
  TENANT_HUMAN_REFERENCE_SCOPES,
  type TeamId,
  type TenantHumanReference,
  type TenantHumanReferenceScope,
  type TenantId,
  type TimezoneId,
  toAssetId,
  toAuditEventId,
  toCompanyId,
  toCorrelationId,
  toCountryCode,
  toCurrencyCode,
  toCustomerId,
  toDateFormat,
  toDocumentId,
  toEmployeeId,
  toEntityGroupId,
  toExecutionId,
  toInternalEntityPk,
  toLocaleCode,
  toMembershipId,
  toNumberFormat,
  toOrganizationId,
  toOwnershipInterestId,
  toPermissionId,
  toPolicyId,
  toProductId,
  toProjectId,
  toRoleId,
  toSupplierId,
  toTeamId,
  toTenantId,
  toTimezoneId,
  toUomCode,
  toUserId,
  toWarehouseId,
  tryParseCanonicalId,
  tryParseRegisteredCanonicalEnterpriseId,
  type UomCode,
  type UserId,
  type WarehouseCode,
  type WarehouseId,
  type WireAuditEntityIdentity,
  type WireCanonicalId,
} from "./identity/index.js";
export type {
  assertPermissionModelDescriptorJsonSerializable,
  PermissionAction,
  PermissionModelDescriptor,
  PermissionModelScope,
} from "./permission/index.js";
export {
  composeModuleActionWireKey,
  getPermissionAction,
  getPermissionModelScope,
  isPermissionAction,
  isPermissionModelDescriptor,
  isPermissionModelScope,
  PERMISSION_ACTIONS,
  PERMISSION_MODEL_PATTERN,
  PERMISSION_MODEL_SCOPE_GRANT_ALIASES,
  PERMISSION_MODEL_SCOPES,
  PERMISSION_VOCABULARY_AUTHORITY,
  PERMISSION_VOCABULARY_OWNERSHIP,
} from "./permission/index.js";
export type {
  PolicyDecision,
  PolicyDecisionKind,
  PolicyDenialReason,
} from "./policy/index.js";
export {
  getPolicyDecisionKind,
  getPolicyDenialReason,
  isPolicyDecision,
  isPolicyDecisionKind,
  isPolicyDenialReason,
  POLICY_DECISION_KINDS,
  POLICY_DENIAL_REASONS,
  POLICY_VOCABULARY_AUTHORITY,
  POLICY_VOCABULARY_OWNERSHIP,
} from "./policy/index.js";
export type { KernelContextFrame } from "./propagation/index.js";
export { kernelContext } from "./propagation/index.js";
