/** Platform kernel and shared contracts — placeholder export for TIP-001 foundation. */

export const PACKAGE_NAME = "@afenda/kernel" as const;

export function getPackageName(): typeof PACKAGE_NAME {
  return PACKAGE_NAME;
}

export {
  type AccountingReadinessContext,
  type ApplicationShellAllowedContextOptions,
  type ApplicationShellContextSwitchTarget,
  CONSOLIDATION_TREATMENTS,
  type ConsolidationEntityScope,
  type ConsolidationScopeContext,
  type ConsolidationTreatment,
  compareEnterpriseHierarchyTierOrder,
  DEFAULT_PERMISSION_GRANT_ELEVATION_FLAGS,
  type DeriveConsolidationScopeInput,
  deriveConsolidationScopeContext,
  ENTERPRISE_HIERARCHY_TIER_DEFINITIONS,
  ENTERPRISE_HIERARCHY_TIERS,
  type EnterpriseHierarchyPersistence,
  type EnterpriseHierarchyTier,
  type EnterpriseHierarchyTierDefinition,
  type EntityGroupContext,
  findUntrustedClientAuthorityFields,
  formatWorkspaceDisplayLabel,
  isCostCenterOrganizationUnit,
  isEnterpriseHierarchyTier,
  isOwnershipInterestEffectiveAt,
  isUntrustedClientAuthorityFieldKey,
  KERNEL_OPERATING_CONTEXT_REQUIRED_MODULES,
  KERNEL_OPERATING_CONTEXT_SUPPORT_MODULES,
  type KernelOperatingContextPrimaryType,
  type KernelOperatingContextRequiredModule,
  LEGAL_ENTITY_COMPANY_TYPES,
  type LegalEntityCompanyType,
  type LegalEntityContext,
  normalizeRuntimeModulePath,
  OPERATING_CONTEXT_ERROR_CODES,
  type OperatingContext,
  type OperatingContextActor,
  type OperatingContextError,
  type OperatingContextErrorCode,
  type OperatingContextResult,
  type OperatingContextSelection,
  ORGANIZATION_UNIT_TYPES,
  type OrganizationUnitContext,
  type OrganizationUnitType,
  OWNERSHIP_CONTROL_TYPES,
  type OwnershipControlType,
  type OwnershipInterestContext,
  PERMISSION_GRANT_SCOPE_TYPES,
  type PermissionGrantElevationFlags,
  type PermissionGrantScopeType,
  type PermissionScopeContext,
  PLATFORM_LIFECYCLE_STATUSES,
  type PlatformLifecycleStatus,
  PROJECT_LIFECYCLE_STATUSES,
  type ProjectContext,
  type ProjectLifecycleStatus,
  parseSurfaceId,
  parseWorkflowId,
  resolveReportingCurrency,
  type SurfaceContext,
  type SurfaceId,
  type TeamContext,
  type TenantContext,
  toAccountingReadinessContext,
  toSurfaceContext,
  toWorkflowContext,
  UNTRUSTED_CLIENT_AUTHORITY_FIELD_KEYS,
  type UntrustedClientAuthorityFieldKey,
  type WorkflowContext,
  type WorkflowId,
  type WorkspaceContext,
  type WorkspaceDisplayLabelInput,
} from "./context/index.js";
export {
  type AppError,
  type AppErrorCode,
  AppErrors,
  type ValidationFieldError,
} from "./contracts/app-error.contract.js";
export {
  type Brand,
  brandOptionalId,
  brandRequiredId,
  unbrand,
} from "./contracts/brand.contract.js";
export {
  assertExecutionContext,
  createExecutionContext,
  createExecutionId,
  EXECUTION_CONTEXT_SOURCES,
  type ExecutionContext,
  type ExecutionContextInput,
  type ExecutionContextSource,
} from "./contracts/execution-context.contract.js";
export {
  type AuditEventId,
  brandAuditEventId,
  brandCompanyId,
  brandCorrelationId,
  brandEntityGroupId,
  brandExecutionId,
  brandMembershipId,
  brandOrganizationId,
  brandPermissionId,
  brandPolicyId,
  brandProjectId,
  brandRoleId,
  brandTeamId,
  brandTenantId,
  brandUserId,
  type CompanyId,
  type CorrelationId,
  type EntityGroupId,
  type ExecutionId,
  type MembershipId,
  type OrganizationId,
  type PermissionId,
  type PolicyId,
  type ProjectId,
  type RoleId,
  type TeamId,
  type TenantId,
  toCompanyId,
  toCorrelationId,
  toExecutionId,
  toOrganizationId,
  toTenantId,
  toUserId,
  type UserId,
} from "./contracts/platform-id.contract.js";
export {
  err,
  isErr,
  isOk,
  ok,
  type Result,
  type ResultFailure,
  type ResultSuccess,
} from "./contracts/result.contract.js";
