/**
 * Commercial plan templates — provisioning boundary only.
 *
 * Product code must never branch on planTemplateId. These templates exist solely
 * for the provisioning service to materialize entitlement grants at activation.
 */
import type { CommercialPlanTemplate } from "./entitlement.contract.js";

const BASIC_USAGE_LIMITS = [
  {
    key: "users.max",
    scope: "tenant",
    period: "instant",
    maximum: 10,
    used: 0,
    unit: "users",
  },
  {
    key: "companies.max",
    scope: "tenant",
    period: "instant",
    maximum: 1,
    used: 0,
    unit: "companies",
  },
  {
    key: "organizations.max",
    scope: "tenant",
    period: "instant",
    maximum: 3,
    used: 0,
    unit: "organizations",
  },
  {
    key: "api.calls.daily",
    scope: "tenant",
    period: "daily",
    maximum: 500,
    used: 0,
    unit: "requests",
  },
  {
    key: "storage.gb.max",
    scope: "tenant",
    period: "instant",
    maximum: 5,
    used: 0,
    unit: "gb",
  },
  {
    key: "ai.tokens.monthly",
    scope: "tenant",
    period: "monthly",
    maximum: 0,
    used: 0,
    unit: "tokens",
  },
  {
    key: "einvoice.volume.monthly",
    scope: "tenant",
    period: "monthly",
    maximum: 0,
    used: 0,
    unit: "documents",
  },
  {
    key: "automation.runs.monthly",
    scope: "tenant",
    period: "monthly",
    maximum: 0,
    used: 0,
    unit: "runs",
  },
] as const satisfies CommercialPlanTemplate["usageLimits"];

const ENTERPRISE_USAGE_LIMITS = [
  { ...BASIC_USAGE_LIMITS[0], maximum: 500 },
  { ...BASIC_USAGE_LIMITS[1], maximum: 50 },
  { ...BASIC_USAGE_LIMITS[2], maximum: 200 },
  { ...BASIC_USAGE_LIMITS[3], maximum: 100_000 },
  { ...BASIC_USAGE_LIMITS[4], maximum: 1000 },
  { ...BASIC_USAGE_LIMITS[5], maximum: 10_000_000 },
  { ...BASIC_USAGE_LIMITS[6], maximum: 50_000 },
  { ...BASIC_USAGE_LIMITS[7], maximum: 10_000 },
] as const satisfies CommercialPlanTemplate["usageLimits"];

export const commercialPlanTemplates = {
  basic: {
    planTemplateId: "basic",
    entitlementGrants: [
      {
        key: "module.accounting.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
    ],
    usageLimits: BASIC_USAGE_LIMITS,
  },
  pro: {
    planTemplateId: "pro",
    entitlementGrants: [
      {
        key: "module.accounting.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "module.mrp.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.e_invoice.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.lot_tracking.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "localization.vn.enabled",
        type: "localization",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
    ],
    usageLimits: [
      { ...BASIC_USAGE_LIMITS[0], maximum: 50 },
      { ...BASIC_USAGE_LIMITS[1], maximum: 5 },
      { ...BASIC_USAGE_LIMITS[2], maximum: 20 },
      { ...BASIC_USAGE_LIMITS[3], maximum: 5000 },
      { ...BASIC_USAGE_LIMITS[4], maximum: 50 },
      { ...BASIC_USAGE_LIMITS[5], maximum: 100_000 },
      { ...BASIC_USAGE_LIMITS[6], maximum: 500 },
      { ...BASIC_USAGE_LIMITS[7], maximum: 200 },
    ],
  },
  enterprise: {
    planTemplateId: "enterprise",
    entitlementGrants: [
      {
        key: "module.accounting.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "module.mrp.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "module.ai_copilot.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.e_invoice.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.lot_tracking.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.forecasting.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.audit_export.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "localization.vn.enabled",
        type: "localization",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "localization.my.enabled",
        type: "localization",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "deployment.self_hosted.enabled",
        type: "deployment",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "deployment.managed_cloud.enabled",
        type: "deployment",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "support.sla_24_7.enabled",
        type: "support",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "security.sso.enabled",
        type: "security",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
    ],
    usageLimits: ENTERPRISE_USAGE_LIMITS,
  },
  beta: {
    planTemplateId: "beta",
    entitlementGrants: [
      {
        key: "module.accounting.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "module.mrp.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "module.ai_copilot.enabled",
        type: "module",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.e_invoice.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.lot_tracking.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.forecasting.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "feature.audit_export.enabled",
        type: "feature",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "localization.vn.enabled",
        type: "localization",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "localization.my.enabled",
        type: "localization",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "deployment.self_hosted.enabled",
        type: "deployment",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "deployment.managed_cloud.enabled",
        type: "deployment",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "support.sla_24_7.enabled",
        type: "support",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "security.sso.enabled",
        type: "security",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
      {
        key: "beta.ai_recommendations.enabled",
        type: "beta",
        enabled: true,
        scope: "tenant",
        companyId: null,
        environment: null,
        metadata: {},
      },
    ],
    usageLimits: ENTERPRISE_USAGE_LIMITS,
  },
} as const satisfies Record<string, CommercialPlanTemplate>;

export const commercialPlanTemplateList = Object.values(
  commercialPlanTemplates
);

export function getCommercialPlanTemplate(
  planTemplateId: string
): CommercialPlanTemplate | null {
  return (
    commercialPlanTemplateList.find(
      (template) => template.planTemplateId === planTemplateId
    ) ?? null
  );
}
